import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { currencyCopper, eligibleCatalogItems, iconForItem, parseCopper, quoteItem } from '../../shared/vendorEconomy.ts';
import { executeVendorTrade } from '../../shared/vendorTradeCore.ts';
const PROTECTED = ['6a6825cd07a490fa70a46852', '6a6825edd695bd65a4322256', '6a767f23ec36fe219063ae49', '6a77463582a26b50018110ea'];
export default async function testVendorEconomyRegression(req) {
  const fixtures = []; const cleanup = []; const results = []; let output;
  try {
    await req.json(); const base44 = createClientFromRequest(req); const user = await base44.auth.me(); if (!user || user.role !== 'admin') return Response.json({ error: 'Admin access required' }, { status: 403 });
    const tag = `VendorQA_${Date.now()}`; const dagger = { name: 'Dagger', category: 'Weapon', rarity: 'common', base_price: '2 gp', stock: 4, stackable: false };
    const character = await base44.entities.Character.create({ name: tag, race: 'Human', class: 'Rogue', level: 3, hp_max: 20, hp_current: 20, gold: 20, inventory: [{ ...dagger, quantity: 2 }], long_rest_abilities: {}, is_active: false });
    const session = await base44.asServiceRole.entities.GameSession.create({ character_id: character.id, title: tag, story_log: [], is_active: false });
    const mismatchSession = await base44.asServiceRole.entities.GameSession.create({ character_id: 'wrong-character', title: `${tag}:mismatch`, story_log: [], is_active: false });
    const vendor = await base44.asServiceRole.entities.Vendor.create({ name: tag, type: 'blacksmith', gold_reserve: 50, is_active: false, items: [dagger, { name: 'Cheap', category: 'Weapon', rarity: 'common', base_price: '1 cp', stock: 2, stackable: true }, { name: 'Expensive', category: 'Weapon', rarity: 'rare', base_price: '2 pp', stock: 2, stackable: false }, { name: 'Arrows (20)', category: 'Ammunition', rarity: 'common', base_price: '1 gp', stock: 2, stackable: true }] }); fixtures.push({ character: character.id, session: session.id, mismatchSession: mismatchSession.id, vendor: vendor.id });
    const sellQuote = quoteItem({ vendor, item: dagger, direction: 'sell_to_vendor' }); results.push({ name: '2 gp Dagger baseline sell quote is 1 gp without fallback', pass: sellQuote.unit_copper === 100 && sellQuote.unit_display === '1 gp' && sellQuote.unit_copper !== 500 });
    results.push({ name: 'currency parser supports cp sp ep gp pp and decimal-safe copper rounding', pass: parseCopper('12 cp') === 12 && parseCopper('2 sp') === 20 && parseCopper('1 ep') === 50 && parseCopper('2.5 gp') === 250 && parseCopper({ pp: 1, gp: 2 }) === 1200 && parseCopper('0.009 gp') === 0 });
    results.push({ name: 'buy and sell direction remains correct for cheap normal and expensive items', pass: quoteItem({ vendor, item: vendor.items[1], direction: 'buy_from_vendor' }).unit_copper === 1 && quoteItem({ vendor, item: vendor.items[1], direction: 'sell_to_vendor' }).unit_copper === 1 && quoteItem({ vendor, item: dagger, direction: 'buy_from_vendor' }).unit_copper === 200 && sellQuote.unit_copper === 100 && quoteItem({ vendor, item: vendor.items[2], direction: 'buy_from_vendor' }).unit_copper === 2000 && quoteItem({ vendor, item: vendor.items[2], direction: 'sell_to_vendor' }).unit_copper === 1000 });
    results.push({ name: 'invalid price fails closed', pass: quoteItem({ vendor, item: { name: 'Bad', base_price: 'unknown' }, direction: 'sell_to_vendor' }).status === 'price_unavailable' });
    const catalog = Array.from({ length: 65 }, (_, index) => ({ name: `Catalog ${String(index).padStart(2, '0')}`, category: 'Weapon', rarity: index % 2 ? 'common' : 'uncommon', base_price: 1, vendor_types: ['blacksmith'] })); const eligible = eligibleCatalogItems(vendor, catalog); const pages = [eligible.slice(0, 24), eligible.slice(24, 48), eligible.slice(48, 72)].flat(); results.push({ name: 'eligible catalog paging reaches first middle and last without truncation', pass: eligible.length === 65 && pages.length === 65 && pages[0].name === 'Catalog 00' && pages[32].name === 'Catalog 32' && pages[64].name === 'Catalog 64', eligible_count: eligible.length, reachable_count: pages.length }); results.push({ name: 'category rarity icons exist for every displayed fixture item', pass: pages.every((item) => iconForItem(item).length > 0) });
    const trade = (data) => executeVendorTrade({ db: base44.asServiceRole, user, characterId: character.id, sessionId: session.id, vendorId: vendor.id, ...data });
    const buyQuote = quoteItem({ vendor, item: dagger, direction: 'buy_from_vendor' }); const buy = await trade({ itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 1, quoteId: buyQuote.quote_id, requestId: `${tag}:buy` }); const afterBuy = await base44.asServiceRole.entities.Character.get(character.id); const vendorAfterBuy = await base44.asServiceRole.entities.Vendor.get(vendor.id); const replayBuy = await trade({ itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 1, quoteId: buyQuote.quote_id, requestId: `${tag}:buy` });
    results.push({ name: 'buy updates currency inventory and stock exactly once; replay is inert', pass: buy.status === 200 && currencyCopper(afterBuy) === 1800 && vendorAfterBuy.items.find((item) => item.name === 'Dagger').stock === 3 && replayBuy.body.already_processed });
    const liveVendor = await base44.asServiceRole.entities.Vendor.get(vendor.id); const liveCharacter = await base44.asServiceRole.entities.Character.get(character.id); const liveSell = quoteItem({ vendor: liveVendor, item: liveCharacter.inventory.find((item) => item.name === 'Dagger'), direction: 'sell_to_vendor' }); const sell = await trade({ itemName: 'Dagger', direction: 'sell_to_vendor', quantity: 1, quoteId: liveSell.quote_id, requestId: `${tag}:sell` }); const afterSell = await base44.asServiceRole.entities.Character.get(character.id); const vendorAfterSell = await base44.asServiceRole.entities.Vendor.get(vendor.id); const replaySell = await trade({ itemName: 'Dagger', direction: 'sell_to_vendor', quantity: 1, quoteId: liveSell.quote_id, requestId: `${tag}:sell` });
    results.push({ name: 'sell updates currency inventory and reserve exactly once; replay is inert', pass: sell.status === 200 && currencyCopper(afterSell) === 1900 && Math.round(vendorAfterSell.gold_reserve * 100) === 5100 && replaySell.body.already_processed });
    const arrowSource = vendorAfterSell.items.find((item) => item.name === 'Arrows (20)'); const arrowQuote = quoteItem({ vendor: vendorAfterSell, item: arrowSource, direction: 'buy_from_vendor' }); const arrowBuy = await trade({ itemName: 'Arrows (20)', direction: 'buy_from_vendor', quantity: 1, quoteId: arrowQuote.quote_id, requestId: `${tag}:arrows` }); const afterArrowBuy = await base44.asServiceRole.entities.Character.get(character.id);
    results.push({ name: 'vendor acquisition normalizes one Arrows (20) pack to twenty individual arrows', pass: arrowBuy.status === 200 && afterArrowBuy.inventory.some((item) => item.name === 'Arrows' && item.quantity === 20 && item.unit === 'arrow' && item.stack_semantics === 'individual' && item.pack_size === 20) });
    const vendorAfterArrowBuy = await base44.asServiceRole.entities.Vendor.get(vendor.id); const snapshot = JSON.stringify({ currency: currencyCopper(afterArrowBuy), inventory: afterArrowBuy.inventory, vendor: vendorAfterArrowBuy.items, reserve: vendorAfterArrowBuy.gold_reserve }); const expensiveQuote = quoteItem({ vendor: vendorAfterArrowBuy, item: vendorAfterArrowBuy.items.find((item) => item.name === 'Expensive'), direction: 'buy_from_vendor' }); const stockQuote = quoteItem({ vendor: vendorAfterArrowBuy, item: vendorAfterArrowBuy.items.find((item) => item.name === 'Dagger'), direction: 'buy_from_vendor' }); const rejects = await Promise.all([trade({ itemName: 'Expensive', direction: 'buy_from_vendor', quantity: 1, quoteId: expensiveQuote.quote_id, requestId: `${tag}:funds` }), trade({ itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 99, quoteId: stockQuote.quote_id, requestId: `${tag}:stock` }), trade({ itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 0, quoteId: stockQuote.quote_id, requestId: `${tag}:quantity` }), trade({ itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 1, quoteId: 'stale', requestId: `${tag}:stale` }), executeVendorTrade({ db: base44.asServiceRole, user, characterId: character.id, sessionId: fixtures[0].mismatchSession, vendorId: vendor.id, itemName: 'Dagger', direction: 'buy_from_vendor', quantity: 1, quoteId: 'bad', requestId: `${tag}:link` })]); const unchanged = await base44.asServiceRole.entities.Character.get(character.id); const unchangedVendor = await base44.asServiceRole.entities.Vendor.get(vendor.id); results.push({ name: 'funds stock quantity stale quote and linkage rejections have zero partial writes', pass: rejects[0].body.error === 'insufficient_funds' && rejects[1].body.error === 'insufficient_stock' && rejects[2].body.error === 'invalid_trade_request' && rejects[3].body.error === 'stale_quote' && rejects[4].body.error === 'linkage_mismatch' && snapshot === JSON.stringify({ currency: currencyCopper(unchanged), inventory: unchanged.inventory, vendor: unchangedVendor.items, reserve: unchangedVendor.gold_reserve }) });
    const passed = results.filter((result) => result.pass).length; output = { passed, failed: results.length - passed, total: results.length, all_pass: passed === results.length, results, protected_state: { ids: PROTECTED, read_or_mutated: false } };
  } catch (error) { output = { error: error.message, results }; }
  finally { const base44 = createClientFromRequest(req); for (const fixture of fixtures.reverse()) for (const [entity, id] of [['Vendor', fixture.vendor], ['GameSession', fixture.mismatchSession], ['GameSession', fixture.session], ['Character', fixture.character]]) { let deleted = false; let verified_absent = false; try { await base44.asServiceRole.entities[entity].delete(id); deleted = true; } catch {} try { verified_absent = !(await base44.asServiceRole.entities[entity].get(id)); } catch { verified_absent = true; } cleanup.push({ entity, id, deleted, verified_absent }); } }
  const cleanupPassed = cleanup.every((entry) => entry.deleted && entry.verified_absent); return Response.json({ cleanup, cleanup_passed: cleanupPassed, ...(output || { error: 'No output' }) }, { status: cleanupPassed && output?.all_pass ? 200 : 500 });
}