// Tower configuration data — pure JS, no R3F dependencies

export const TOWER_CONFIGS = {
  wooden: {
    name: 'Tavern Box',
    emoji: '🪵',
    dieColor: '#c9a96e',
    ambientColor: '#ff9944',
    fogColor: '#1a0a02',
    description: 'A battered tavern dice box',
    sparkles: null,
    unlocked: true,
  },
  arcane: {
    name: 'Arcane Tower',
    emoji: '🔮',
    dieColor: '#b084fc',
    ambientColor: '#8844ff',
    fogColor: '#0e0020',
    description: 'Pulsing with arcane energy',
    sparkles: { color: '#aa66ff', count: 60, size: 2, speed: 0.4 },
    unlocked: true,
  },
  infernal: {
    name: 'Infernal Forge',
    emoji: '🔥',
    dieColor: '#ff6644',
    ambientColor: '#ff2200',
    fogColor: '#1a0000',
    description: 'Forged in hellfire',
    sparkles: { color: '#ff4400', count: 50, size: 3, speed: 0.9 },
    unlocked: true,
  },
  crystal: {
    name: 'Crystal Vault',
    emoji: '💎',
    dieColor: '#60c8ff',
    ambientColor: '#00aaff',
    fogColor: '#000e1a',
    description: 'Carved from glacial crystal',
    sparkles: { color: '#00ccff', count: 70, size: 1.5, speed: 0.2 },
    unlocked: true,
  },
  elven: {
    name: 'Elven Glade',
    emoji: '🌿',
    dieColor: '#86efac',
    ambientColor: '#22c55e',
    fogColor: '#010e01',
    description: 'Woven from living wood',
    sparkles: { color: '#88ff44', count: 40, size: 1.5, speed: 0.3 },
    unlocked: true,
  },
  shadow: {
    name: 'Shadow Realm',
    emoji: '🌑',
    dieColor: '#888',
    ambientColor: '#6633cc',
    fogColor: '#020005',
    description: 'From the void between worlds',
    sparkles: { color: '#9933ff', count: 80, size: 1, speed: 0.6 },
    unlocked: true,
  },
};

export default TOWER_CONFIGS;