import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { applyDruidCraftingIncidentRepair, createDruidRepairApplyToken, discoverDruidCraftingIncidentRepair, DRUID_CRAFTING_RECEIPT_KEY, DRUID_CRAFTING_REPAIR_VERSION } from '../../shared/repairs/druidAmmunitionCraftingRepair.ts';
import { hashValue,readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const requestId='story-action:6a6825edd695bd65a4322256:1788408540111:inn7cv';
const stable=(record,omit=[])=>Object.fromEntries(Object.entries(record||{}).filter(([key])=>!['updated_date',...omit].includes(key)));
export default async function(req){
  try{
    const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user||user.role!=='admin')return Response.json({error:'Admin required'},{status:403});await req.json().catch(()=>({}));
    const db=base44.asServiceRole,fixtures=[],tests=[],record=(name,pass)=>tests.push({name,pass:!!pass}),protectedBefore=await hashValue(await readProtectedDndState(db));
    const make=async(label)=>{
      const tag=`DruidRepair_${label}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
      const inv18=[{name:'Arrows',category:'Ammunition',quantity:18,unit:'arrow',stack_semantics:'individual',stackable:true},{name:'Rope',quantity:1}],inv17=inv18.map((item)=>item.name==='Arrows'?{...item,quantity:17}:item),inv16=inv18.map((item)=>item.name==='Arrows'?{...item,quantity:16}:item);
      const first={immutable:true,request_id:`${tag}:shot1`,ammo_name:'Arrows',consumed:1,quantity_before:18,quantity_after:17,inventory_before_hash:await hashValue(inv18),inventory_after_hash:await hashValue(inv17),at:'2026-09-03T03:28:20.957Z'};
      const second={immutable:true,request_id:`${tag}:shot2`,ammo_name:'Arrows',consumed:1,quantity_before:17,quantity_after:16,inventory_before_hash:await hashValue(inv17),inventory_after_hash:await hashValue(inv16),at:'2026-09-03T04:01:18.424Z'};
      const character=await db.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:5,hp_max:52,hp_current:52,gold:296,silver:955,copper:2255,spell_slots:{level_2:1},inventory:inv16,long_rest_abilities:{__ammo_attack_receipts:[first,second]},is_active:false});
      const fillers=Array.from({length:59},(_,index)=>({request_id:`${tag}:filler:${index}`,text:`Scene ${index}`,choices:[]}));
      const skill={id:requestId,request_id:requestId,skill:'Nature',raw_d20:17,all_rolls:[17],dc:12,modifier_total:3,final_total:20,success:true,unified_story_skill_resolution:true};
      const recovery={type:'arrows',quantity:20},choices=['Move','Commune','Confront','Consult'].map((text,index)=>({text,action_type:index===1?'skill_check':'movement',recovery:{...recovery}}));
      const incident={timestamp:'2026-09-03T04:09:08.572Z',request_id:requestId,player_choice:'Ask the druids to make arrow shafts from stone or ironwood tree heart.',text:'The druids shape heartwood and black flint, binding each shaft with natural resin. As the final arrow is balanced and set into your quiver, you have secured the means to strike.',skill_check:skill,choices};
      const session=await db.entities.GameSession.create({character_id:character.id,title:tag,story_log:[...fillers,incident],world_state:{},in_combat:false,combat_state:{},is_active:false});fixtures.push(['GameSession',session.id],['Character',character.id]);return {character,session};
    };
    try{
      const fixture=await make('apply'),discover=await discoverDruidCraftingIncidentRepair({db,characterId:fixture.character.id,sessionId:fixture.session.id});
      record('discover is compact zero-write and under 8KB',discover.status===200&&discover.body.writes===0&&JSON.stringify(discover.body).length<8192&&!('inventory'in discover.body)&&!('narration'in discover.body)&&!('choices'in discover.body));
      record('discover exact repair readiness',discover.body.safe_to_repair&&discover.body.repair_eligible&&discover.body.quantity_before===16&&discover.body.quantity_after===36&&discover.body.ingredient_debit===0&&discover.body.failed_guards.length===0&&!!discover.body.apply_token);
      const beforeCharacter=await db.entities.Character.get(fixture.character.id),beforeSession=await db.entities.GameSession.get(fixture.session.id),beforeNoninventory=await hashValue(stable(beforeCharacter,['inventory','long_rest_abilities']));
      const tampered=await applyDruidCraftingIncidentRepair({db,characterId:fixture.character.id,sessionId:fixture.session.id,applyToken:`${discover.body.apply_token}x`});record('tampered token fails closed',tampered.status===403&&tampered.body.writes===0);
      const tokenPayload={v:DRUID_CRAFTING_REPAIR_VERSION,character_id:fixture.character.id,session_id:fixture.session.id,request_id:requestId,story_index:59,award_quantity:20,expected_hashes:discover.body.expected_hashes,iat:1,exp:2};const staleToken=await createDruidRepairApplyToken(tokenPayload),stale=await applyDruidCraftingIncidentRepair({db,characterId:fixture.character.id,sessionId:fixture.session.id,applyToken:staleToken,now:3});record('expired token fails closed',stale.status===403&&stale.body.error==='expired_apply_token'&&stale.body.writes===0);
      const applied=await applyDruidCraftingIncidentRepair({db,characterId:fixture.character.id,sessionId:fixture.session.id,applyToken:discover.body.apply_token}),afterCharacter=await db.entities.Character.get(fixture.character.id),afterSession=await db.entities.GameSession.get(fixture.session.id),receipt=afterCharacter.long_rest_abilities?.[DRUID_CRAFTING_RECEIPT_KEY]?.[0];
      record('apply increments ordinary Arrows sixteen to thirty-six once',applied.status===200&&applied.body.writes===1&&afterCharacter.inventory.filter((item)=>item.name==='Arrows').length===1&&afterCharacter.inventory.find((item)=>item.name==='Arrows').quantity===36);
      record('receipt is exact immutable guarded reconciliation',receipt?.immutable===true&&receipt?.original_request_id===requestId&&receipt?.story_index===59&&receipt?.award_quantity===20&&receipt?.ingredient_debit===0&&receipt?.provenance==='guarded_repair_of_misattached_recovery_metadata');
      record('story and noninventory mechanics unchanged',JSON.stringify(afterSession.story_log)===JSON.stringify(beforeSession.story_log)&&await hashValue(stable(afterCharacter,['inventory','long_rest_abilities']))===beforeNoninventory&&afterCharacter.hp_current===52&&afterCharacter.gold===296&&afterCharacter.spell_slots.level_2===1&&afterSession.in_combat===false);
      const replay=await applyDruidCraftingIncidentRepair({db,characterId:fixture.character.id,sessionId:fixture.session.id,applyToken:discover.body.apply_token});record('replay is zero-write',replay.status===200&&replay.body.replay===true&&replay.body.writes===0&&(await db.entities.Character.get(fixture.character.id)).inventory.find((item)=>item.name==='Arrows').quantity===36);
      const conflict=await make('conflict'),conflictDiscover=await discoverDruidCraftingIncidentRepair({db,characterId:conflict.character.id,sessionId:conflict.session.id});const changed=(await db.entities.Character.get(conflict.character.id)).inventory.concat({name:'Potion',quantity:1});await db.entities.Character.update(conflict.character.id,{inventory:changed});const conflictApply=await applyDruidCraftingIncidentRepair({db,characterId:conflict.character.id,sessionId:conflict.session.id,applyToken:conflictDiscover.body.apply_token});record('conflicting later inventory fails exact hashes',conflictApply.status===409&&conflictApply.body.writes===0&&conflictApply.body.error==='stale_live_precondition_hashes');
    }catch(error){record(`execution: ${error.message}`,false);}finally{for(const [entity,id] of fixtures.reverse())try{await db.entities[entity].delete(id);}catch{}}
    record('fixture cleanup and protected live records unchanged',protectedBefore===await hashValue(await readProtectedDndState(db)));const passed=tests.filter((test)=>test.pass).length,all=passed===tests.length;return Response.json({function_version:'test-druid-crafting-incident-repair-v1.0.0',repair_version:DRUID_CRAFTING_REPAIR_VERSION,passed,failed:tests.length-passed,total:tests.length,all_pass:all,tests},{status:all?200:500});
  }catch(error){return Response.json({error:error.message||'Druid repair regression failed.'},{status:500});}
}