import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { executeAskDungeonMasterCore } from '../../shared/askDungeonMasterCore.ts';
import { finalizeGeneratedStoryResult } from '../../shared/story/storyBootstrap.ts';
import { acceptSequencedStoryPayload, canonicalStoryResponsePayload, commitStoryTransition, hashStoryValue, hydrateLatestStoryEntry, storyPayloadFromCommit } from '../../shared/story/storyTransition.ts';
import { resolveUnifiedStorySkillCheck } from '../../shared/story/unifiedStorySkillResolution.ts';
import { staleChoiceTransitionRepairCore } from '../../shared/repairs/staleChoiceTransition.ts';
import { guardAndCommitNarratedRecovery } from '../../shared/story/storyRecoveryGuard.ts';
import { hashValue, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const choices = (prefix) => [1,2,3,4].map((n) => ({ text: `${prefix} grounded option ${n}`, skill_check: n % 2 ? 'Perception' : 'Investigation', dc: 10 + n, risk_level: n > 2 ? 'medium' : 'low' }));

export default async function testConsecutiveStoryChoiceRegression(req) {
  try {
    const base44 = createClientFromRequest(req); const user = await base44.auth.me();
    if (!user || user.role !== 'admin') return Response.json({ error: 'Admin access required' }, { status: 403 });
    await req.json().catch(() => ({}));
    const protectedBefore = await hashValue(await readProtectedDndState(base44.asServiceRole));
    const results=[]; const fixtures=[]; const cleanup=[]; const record=(name,pass)=>results.push({name,pass:!!pass});
    try {
      const character=await base44.entities.Character.create({name:`Consecutive_${Date.now()}`,race:'Human',class:'Ranger',level:5,wisdom:16,strength:12,dexterity:14,proficiency_bonus:3,skills:{Perception:false,Investigation:true},hp_current:40,hp_max:40,inventory:[{name:'Arrows',quantity:18}],is_active:false}); fixtures.push(['Character',character.id]);
      const repaired=choices('repaired');
      const session=await base44.entities.GameSession.create({character_id:character.id,title:'Consecutive transition fixture',current_location:'fogbound shrine',story_log:[{timestamp:'2026-09-01T00:00:00.000Z',request_id:'existing-repair',action:'choice',text:'Existing repaired scene.',choices:repaired,repair_origin:'fixture'}],world_state:{__skill_check_receipts:[]},in_combat:false,combat_state:{},is_active:false}); fixtures.push(['GameSession',session.id]);
      const repairedBytes=JSON.stringify(session.story_log[0]); const inventoryBefore=await hashValue(character.inventory); const capturedNarration='Your Survival check succeeds and you regain focus, recover your footing, and find a safer route through the fens.'; const falsePositiveGuard=await guardAndCommitNarratedRecovery({base44,sessionId:session.id,characterId:character.id,requestId:'captured-survival-idiom',check:{success:true},narrative:capturedNarration,recovery:{}}); record('captured Survival idioms bypass inventory transaction',falsePositiveGuard.body.reason==='not_applicable'&&falsePositiveGuard.body.writes===0&&inventoryBefore===await hashValue((await base44.asServiceRole.entities.Character.get(character.id)).inventory)); const concreteGuard=await guardAndCommitNarratedRecovery({base44,sessionId:session.id,characterId:character.id,requestId:'missing-actual-item',check:{success:true},narrative:'You recover exactly 7 arrows from the mud.',recovery:null}); record('actual unstructured acquisition fails closed',concreteGuard.status===409&&concreteGuard.body.reason==='missing_exact_structured_recovery'&&concreteGuard.body.writes===0); const structuredGuard=await guardAndCommitNarratedRecovery({base44,sessionId:session.id,characterId:character.id,requestId:'structured-actual-item',check:{success:true},narrative:'You recover exactly 2 arrows from the mud.',recovery:{type:'arrows',quantity:2}}); record('actual structured acquisition commits once',structuredGuard.body.applied&&structuredGuard.body.writes===1&&structuredGuard.body.recovery_transaction.status==='committed');
      const firstId='fixture-first-transition';
      const firstRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:firstId,skill:'Investigation',dc:12,raw_d20:15,all_rolls:[15]}});
      const firstGuard=finalizeGeneratedStoryResult({narrative:'The first investigation changes the scene.',choices:choices('first'),combat_trigger:false},{location:'fogbound shrine',requestId:firstId,previousChoices:repaired});
      const firstFresh=await base44.asServiceRole.entities.GameSession.get(session.id); const firstEntry={timestamp:'2026-09-01T00:01:00.000Z',request_id:firstId,action:'choice',player_choice:'Investigate',text:firstGuard.narrative,choices:firstGuard.choices,skill_check:firstRoll.body.receipt}; const firstCommit=commitStoryTransition(firstFresh.story_log,firstEntry,firstId); await base44.asServiceRole.entities.GameSession.update(session.id,{story_log:firstCommit.story_log});
      record('first consecutive transition commits fresh choices',firstCommit.entry.choices.length===4&&JSON.stringify(firstCommit.entry.choices)!==JSON.stringify(repaired));
      const secondId='fixture-failed-perception';
      const secondRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:secondId,skill:'Perception',dc:12,raw_d20:4,all_rolls:[4]}});
      record('second Perception receipt is authoritative failure',secondRoll.body.receipt?.raw_d20===4&&secondRoll.body.receipt?.modifier_total===3&&secondRoll.body.receipt?.final_total===7&&secondRoll.body.receipt?.success===false);
      const identicalModelChoices=firstGuard.choices;
      const secondGuard=finalizeGeneratedStoryResult({narrative:'The failed search reveals no safe opening.',choices:identicalModelChoices,combat_trigger:false},{location:'fogbound shrine',requestId:secondId,previousChoices:firstGuard.choices});
      record('production guard replaces identical model choices',secondGuard.choice_guard.reason==='identical_to_preceding'&&JSON.stringify(secondGuard.choices)!==JSON.stringify(firstGuard.choices)&&secondGuard.choices.length===4);
      const beforeSecond=await base44.asServiceRole.entities.GameSession.get(session.id); const secondEntry={timestamp:'2026-09-01T00:02:00.000Z',request_id:secondId,action:'choice',player_choice:'Look carefully',text:secondGuard.narrative,choices:secondGuard.choices,skill_check:secondRoll.body.receipt}; secondEntry.choice_evidence={previous_choice_hash:await hashStoryValue(firstGuard.choices),current_choice_hash:await hashStoryValue(secondGuard.choices),response_payload_hash:await hashStoryValue(canonicalStoryResponsePayload({requestId:secondId,text:secondEntry.text,choices:secondEntry.choices,skillCheck:secondEntry.skill_check}))}; const secondCommit=commitStoryTransition(beforeSecond.story_log,secondEntry,secondId); await base44.asServiceRole.entities.GameSession.update(session.id,{story_log:secondCommit.story_log});
      const response={...storyPayloadFromCommit({...secondCommit,persistence_confirmed:true}),persistence_confirmed:true}; const accepted=acceptSequencedStoryPayload(response,2,2); const afterSecond=await base44.asServiceRole.entities.GameSession.get(session.id); const hydration=hydrateLatestStoryEntry(afterSecond);
      record('response equals persisted latest pair',accepted.accepted&&accepted.hydration.text===afterSecond.story_log.at(-1).text&&JSON.stringify(accepted.hydration.choices)===JSON.stringify(afterSecond.story_log.at(-1).choices));
      record('reload hydrates exact latest pair',hydration.request_id===secondId&&hydration.text===secondEntry.text&&JSON.stringify(hydration.choices)===JSON.stringify(secondGuard.choices));
      record('existing repaired entry remains byte identical',JSON.stringify(afterSecond.story_log[0])===repairedBytes);
      const replayRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:secondId,skill:'Perception',dc:12}}); const replayCommit=commitStoryTransition(afterSecond.story_log,afterSecond.story_log.at(-1),secondId);
      record('failed receipt replay reuses roll',replayRoll.body.writes===0&&replayRoll.body.replayed===true&&replayRoll.body.raw===4&&replayRoll.body.final===7);
      record('story replay writes zero logical entries',replayCommit.replayed&&replayCommit.story_log.length===afterSecond.story_log.length&&JSON.stringify(replayCommit.story_log)===JSON.stringify(afterSecond.story_log));
      record('late sequence cannot overwrite',acceptSequencedStoryPayload(response,1,2).accepted===false);
      const missedPersistence=acceptSequencedStoryPayload({...response,persistence_confirmed:false},2,2); record('unconfirmed narration is not shown as committed',!missedPersistence.accepted&&missedPersistence.reason==='persistence_unconfirmed');
      const mobile={narrative:hydration.text?[{type:'narration',text:hydration.text}]:[],choices:hydration.choices,in_combat:false}; record('mobile hydration is actionable',mobile.narrative.length===1&&mobile.choices.length===4&&!mobile.in_combat);
      for(const [label,value] of [['missing',undefined],['empty',[]],['malformed',[{text:''},{nope:true}]]]){const guarded=finalizeGeneratedStoryResult({narrative:`${label} choices`,choices:value,combat_trigger:false},{location:'fogbound shrine',requestId:`${secondId}-${label}`,previousChoices:secondGuard.choices});record(`${label} consecutive choices get safe replacement`,guarded.choice_guard.reason==='missing_or_malformed'&&guarded.choices.length===4&&JSON.stringify(guarded.choices)!==JSON.stringify(secondGuard.choices));}
      const wrong=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:'missing',character_id:character.id,request_id:'wrong',skill:'Perception',dc:12}}); record('wrong linkage rejects 403',wrong.status===403);
      const beforeAsk=await base44.asServiceRole.entities.GameSession.get(session.id); const ask=await executeAskDungeonMasterCore(base44,{session_id:session.id,character_id:character.id,question:'What is visible?',request_id:'ask-consecutive'}); const afterAsk=await base44.asServiceRole.entities.GameSession.get(session.id); record('Ask DM remains read only',ask.body?.read_only===true&&JSON.stringify(beforeAsk.story_log)===JSON.stringify(afterAsk.story_log));
      const staleReceipt={...secondRoll.body.receipt,request_id:'auditor-stale',id:'auditor-stale'}; const staleSession=await base44.entities.GameSession.create({character_id:character.id,title:'Dynamic auditor fixture',current_location:'fogbound shrine',story_log:[{timestamp:'2026-09-01T00:03:00.000Z',request_id:'auditor-source',text:'Source scene',choices:choices('auditor-old')},{timestamp:'2026-09-01T00:04:00.000Z',request_id:'auditor-stale',text:'Preserved failed narration',choices:choices('auditor-old'),skill_check:staleReceipt}],world_state:{__skill_check_receipts:[staleReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',staleSession.id]);
      const scope={characterId:character.id,sessionId:staleSession.id,receiptKey:'auditor-fixture'}; const dry=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope}); record('dynamic auditor classifies server persisted stale choices',dry.body.classification==='server_persisted_stale_choices'&&dry.body.safe_to_repair&&!!dry.body.apply_token);
      const applied=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:dry.body.apply_token,scope}); const replay=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:dry.body.apply_token,scope}); record('auditor applies at most one guarded write',applied.body.writes===1&&applied.body.postconditions?.narration_preserved&&applied.body.postconditions?.skill_result_preserved); record('auditor replay writes zero',replay.body.writes===0&&replay.body.replayed===true);
      const orphanReceipt={...secondRoll.body.receipt,request_id:'auditor-orphan-failure',id:'auditor-orphan-failure'}; const orphanChoices=[{text:'Pause and study the safest route forward.',skill_check:'Perception',dc:12,risk_level:'low'},...choices('orphan').slice(1)]; const orphanSession=await base44.entities.GameSession.create({character_id:character.id,title:'Sequential orphan fixture',current_location:'fogbound shrine',story_log:[{request_id:'orphan-source',timestamp:'2026-09-01T00:05:00.000Z',text:'Latest committed pair',choices:orphanChoices}],world_state:{__skill_check_receipts:[orphanReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',orphanSession.id]); const orphanScope={characterId:character.id,sessionId:orphanSession.id}; const orphanDry=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope:orphanScope}); record('failed orphan is universally repairable',orphanDry.body.classification==='orphan_browser_narration_with_skill_receipt'&&orphanDry.body.safe_to_repair&&orphanDry.body.proposed_choice_count===4&&!!orphanDry.body.apply_token);
      const tampered=`${orphanDry.body.apply_token.slice(0,-1)}${orphanDry.body.apply_token.endsWith('a')?'b':'a'}`; const tamperedResult=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:tampered,scope:orphanScope}); record('noncanonical tampered failure token rejects',tamperedResult.status===409&&tamperedResult.body.writes===0);
      const orphanApply=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:orphanDry.body.apply_token,scope:orphanScope}); const afterFailure=await base44.asServiceRole.entities.GameSession.get(orphanSession.id); const failureReplay=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:orphanDry.body.apply_token,scope:orphanScope}); record('failed orphan appends one atomic pair',orphanApply.body.writes===1&&afterFailure.story_log.length===2&&afterFailure.story_log.at(-1).skill_check.success===false&&afterFailure.story_log.at(-1).choices.length===4&&JSON.stringify(afterFailure.story_log.at(-1).choices)!==JSON.stringify(orphanChoices)); record('failed orphan replay writes zero',failureReplay.body.replayed&&failureReplay.body.writes===0);
      const successReceipt={...orphanReceipt,id:'auditor-orphan-success',request_id:'auditor-orphan-success',skill:'Survival',dc:10,raw_d20:11,modifier_total:9,final_total:20,success:true,at:'2026-09-01T00:06:00.000Z'}; await base44.asServiceRole.entities.GameSession.update(orphanSession.id,{world_state:{...(afterFailure.world_state||{}),__skill_check_receipts:[orphanReceipt,successReceipt]}}); const successDry=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope:orphanScope}); record('successful orphan is independently repairable',successDry.body.classification==='orphan_browser_narration_with_skill_receipt'&&successDry.body.safe_to_repair&&successDry.body.repair_receipt_key!==orphanDry.body.repair_receipt_key&&!!successDry.body.apply_token);
      const successTampered=`${successDry.body.apply_token.slice(0,-1)}${successDry.body.apply_token.endsWith('a')?'b':'a'}`; const successTamperedResult=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:successTampered,scope:orphanScope}); record('noncanonical tampered success token rejects',successTamperedResult.status===409&&successTamperedResult.body.writes===0); const successApply=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:successDry.body.apply_token,scope:orphanScope}); const afterSuccess=await base44.asServiceRole.entities.GameSession.get(orphanSession.id); const latest=hydrateLatestStoryEntry(afterSuccess); const successReplay=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:successDry.body.apply_token,scope:orphanScope}); const repairReceipts=afterSuccess.world_state.__stale_choice_transition_repairs||[];
      record('successful orphan appends one atomic pair',successApply.body.writes===1&&afterSuccess.story_log.length===3&&latest.request_id==='auditor-orphan-success'&&latest.entry.skill_check.raw_d20===11&&latest.entry.skill_check.final_total===20&&latest.entry.skill_check.success===true&&latest.choices.length===4&&JSON.stringify(latest.choices)!==JSON.stringify(afterFailure.story_log.at(-1).choices)); record('two incidents have distinct immutable receipts',repairReceipts.length===2&&repairReceipts.every((item)=>item.immutable)&&new Set(repairReceipts.map((item)=>item.receipt_key)).size===2); record('both immutable outcomes remain exact',afterSuccess.story_log[1].skill_check.success===false&&afterSuccess.story_log[1].skill_check.final_total===7&&afterSuccess.story_log[2].skill_check.success===true&&afterSuccess.story_log[2].skill_check.final_total===20); record('success reload is exact latest pair',latest.text===afterSuccess.story_log.at(-1).text&&JSON.stringify(latest.choices)===JSON.stringify(afterSuccess.story_log.at(-1).choices)); record('successful orphan replay writes zero',successReplay.body.replayed&&successReplay.body.writes===0);
      const successResponse={...storyPayloadFromCommit({entry:latest.entry,index:latest.index,persistence_confirmed:true}),persistence_confirmed:true}; record('successful repair response equals persisted pair',acceptSequencedStoryPayload(successResponse,4,4).accepted); record('late repaired response is rejected',!acceptSequencedStoryPayload(successResponse,3,4).accepted); const badPair={...successResponse,narrative:'uncommitted browser text'}; record('mismatched persisted pair is rejected',acceptSequencedStoryPayload(badPair,4,4).reason==='persisted_pair_mismatch');
      const conflictReceipt={...orphanReceipt,request_id:'auditor-conflict',id:'auditor-conflict'}; const conflictSession=await base44.entities.GameSession.create({character_id:character.id,title:'Later conflict fixture',story_log:[{request_id:'conflict-source',timestamp:'2026-09-01T00:06:00.000Z',text:'Source',choices:orphanChoices},{request_id:'later-entry',timestamp:'2026-09-01T00:07:00.000Z',text:'Later authoritative event',choices:choices('later')}],world_state:{__skill_check_receipts:[conflictReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',conflictSession.id]); const conflict=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope:{characterId:character.id,sessionId:conflictSession.id}}); record('later conflict refuses orphan repair',conflict.body.classification==='orphan_browser_narration_with_skill_receipt'&&!conflict.body.safe_to_repair&&!conflict.body.apply_token&&conflict.body.writes===0);
      const incomplete=await base44.entities.GameSession.create({character_id:character.id,title:'Incomplete proposal fixture',current_location:'fogbound shrine',story_log:[{request_id:'incomplete-source',text:'Source',choices:orphanChoices}],world_state:{__skill_check_receipts:[{...orphanReceipt,request_id:'incomplete-receipt',id:'incomplete-receipt'}]},is_active:false});fixtures.push(['GameSession',incomplete.id]); const incompleteAudit=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope:{characterId:character.id,sessionId:incomplete.id},proposalFactory:async()=>({narrative:'Incomplete',choices:[]})}); record('auditor zero-choice proposal fails closed',incompleteAudit.body.classification==='unsafe_incomplete_proposal'&&!incompleteAudit.body.safe_to_repair&&incompleteAudit.body.proposed_choice_count===0&&!incompleteAudit.body.apply_token&&incompleteAudit.body.writes===0); const auditorWrong=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'discover',scope:{characterId:character.id,sessionId:'missing'}}); record('auditor wrong linkage rejects 403',auditorWrong.status===403);
    } finally { for(const [entity,id] of fixtures.reverse()){let absent=false;try{await base44.asServiceRole.entities[entity].delete(id);}catch{}try{absent=!(await base44.asServiceRole.entities[entity].get(id));}catch{absent=true;}cleanup.push({entity,id,absent});} }
    record('cleanup fixtures absent',cleanup.every((item)=>item.absent)); const protectedAfter=await hashValue(await readProtectedDndState(base44.asServiceRole)); record('protected live IDs unchanged',protectedBefore===protectedAfter); const passed=results.filter((item)=>item.pass).length,allPass=passed===results.length; return Response.json({function_version:'test-consecutive-story-choice-v1.3.0',passed,failed:results.length-passed,total:results.length,all_pass:allPass,results,cleanup},{status:allPass?200:500});
  } catch(error){return Response.json({error:error.message||'Consecutive transition regression failed'},{status:500});}
}