import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { executeAskDungeonMasterCore } from '../../shared/askDungeonMasterCore.ts';
import { finalizeGeneratedStoryResult } from '../../shared/story/storyBootstrap.ts';
import { acceptSequencedStoryPayload, canonicalStoryResponsePayload, commitStoryTransition, hashStoryValue, hydrateLatestStoryEntry, storyPayloadFromCommit } from '../../shared/story/storyTransition.ts';
import { resolveUnifiedStorySkillCheck } from '../../shared/story/unifiedStorySkillResolution.ts';
import { staleChoiceTransitionRepairCore } from '../../shared/repairs/staleChoiceTransition.ts';
import { hashValue, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const choices = (prefix) => [1,2,3,4].map((n) => ({ text: `${prefix} grounded option ${n}`, skill_check: n % 2 ? 'Perception' : 'Investigation', dc: 10 + n, risk_level: n > 2 ? 'medium' : 'low' }));

export default async function testConsecutiveStoryChoiceRegression(req) {
  try {
    const base44 = createClientFromRequest(req); const user = await base44.auth.me();
    if (!user || user.role !== 'admin') return Response.json({ error: 'Admin access required' }, { status: 403 });
    await req.json().catch(() => ({}));
    const protectedBefore = await hashValue(await readProtectedDndState(base44.asServiceRole));
    const results=[]; const fixtures=[]; const cleanup=[]; const record=(name,pass)=>results.push({name,pass:!!pass});
    try {
      const character=await base44.entities.Character.create({name:`Consecutive_${Date.now()}`,race:'Human',class:'Ranger',level:5,wisdom:16,strength:12,dexterity:14,proficiency_bonus:3,skills:{Perception:false,Investigation:true},hp_current:40,hp_max:40,inventory:[{name:'Arrows',quantity:18}],is_active:false}); fixtures.push(['Character',character.id]);
      const repaired=choices('repaired');
      const session=await base44.entities.GameSession.create({character_id:character.id,title:'Consecutive transition fixture',current_location:'fogbound shrine',story_log:[{timestamp:'2026-09-01T00:00:00.000Z',request_id:'existing-repair',action:'choice',text:'Existing repaired scene.',choices:repaired,repair_origin:'fixture'}],world_state:{__skill_check_receipts:[]},in_combat:false,combat_state:{},is_active:false}); fixtures.push(['GameSession',session.id]);
      const repairedBytes=JSON.stringify(session.story_log[0]);
      const firstId='fixture-first-transition';
      const firstRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:firstId,skill:'Investigation',dc:12,raw_d20:15,all_rolls:[15]}});
      const firstGuard=finalizeGeneratedStoryResult({narrative:'The first investigation changes the scene.',choices:choices('first'),combat_trigger:false},{location:'fogbound shrine',requestId:firstId,previousChoices:repaired});
      const firstFresh=await base44.asServiceRole.entities.GameSession.get(session.id); const firstEntry={timestamp:'2026-09-01T00:01:00.000Z',request_id:firstId,action:'choice',player_choice:'Investigate',text:firstGuard.narrative,choices:firstGuard.choices,skill_check:firstRoll.body.receipt}; const firstCommit=commitStoryTransition(firstFresh.story_log,firstEntry,firstId); await base44.asServiceRole.entities.GameSession.update(session.id,{story_log:firstCommit.story_log});
      record('first consecutive transition commits fresh choices',firstCommit.entry.choices.length===4&&JSON.stringify(firstCommit.entry.choices)!==JSON.stringify(repaired));
      const secondId='fixture-failed-perception';
      const secondRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:secondId,skill:'Perception',dc:12,raw_d20:4,all_rolls:[4]}});
      record('second Perception receipt is authoritative failure',secondRoll.body.receipt?.raw_d20===4&&secondRoll.body.receipt?.modifier_total===3&&secondRoll.body.receipt?.final_total===7&&secondRoll.body.receipt?.success===false);
      const identicalModelChoices=firstGuard.choices;
      const secondGuard=finalizeGeneratedStoryResult({narrative:'The failed search reveals no safe opening.',choices:identicalModelChoices,combat_trigger:false},{location:'fogbound shrine',requestId:secondId,previousChoices:firstGuard.choices});
      record('production guard replaces identical model choices',secondGuard.choice_guard.reason==='identical_to_preceding'&&JSON.stringify(secondGuard.choices)!==JSON.stringify(firstGuard.choices)&&secondGuard.choices.length===4);
      const beforeSecond=await base44.asServiceRole.entities.GameSession.get(session.id); const secondEntry={timestamp:'2026-09-01T00:02:00.000Z',request_id:secondId,action:'choice',player_choice:'Look carefully',text:secondGuard.narrative,choices:secondGuard.choices,skill_check:secondRoll.body.receipt}; secondEntry.choice_evidence={previous_choice_hash:await hashStoryValue(firstGuard.choices),current_choice_hash:await hashStoryValue(secondGuard.choices),response_payload_hash:await hashStoryValue(canonicalStoryResponsePayload({requestId:secondId,text:secondEntry.text,choices:secondEntry.choices,skillCheck:secondEntry.skill_check}))}; const secondCommit=commitStoryTransition(beforeSecond.story_log,secondEntry,secondId); await base44.asServiceRole.entities.GameSession.update(session.id,{story_log:secondCommit.story_log});
      const response=storyPayloadFromCommit(secondCommit); const accepted=acceptSequencedStoryPayload(response,2,2); const afterSecond=await base44.asServiceRole.entities.GameSession.get(session.id); const hydration=hydrateLatestStoryEntry(afterSecond);
      record('response equals persisted latest pair',accepted.accepted&&accepted.hydration.text===afterSecond.story_log.at(-1).text&&JSON.stringify(accepted.hydration.choices)===JSON.stringify(afterSecond.story_log.at(-1).choices));
      record('reload hydrates exact latest pair',hydration.request_id===secondId&&hydration.text===secondEntry.text&&JSON.stringify(hydration.choices)===JSON.stringify(secondGuard.choices));
      record('existing repaired entry remains byte identical',JSON.stringify(afterSecond.story_log[0])===repairedBytes);
      const replayRoll=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:session.id,character_id:character.id,request_id:secondId,skill:'Perception',dc:12}}); const replayCommit=commitStoryTransition(afterSecond.story_log,afterSecond.story_log.at(-1),secondId);
      record('failed receipt replay reuses roll',replayRoll.body.writes===0&&replayRoll.body.replayed===true&&replayRoll.body.raw===4&&replayRoll.body.final===7);
      record('story replay writes zero logical entries',replayCommit.replayed&&replayCommit.story_log.length===afterSecond.story_log.length&&JSON.stringify(replayCommit.story_log)===JSON.stringify(afterSecond.story_log));
      record('late sequence cannot overwrite',acceptSequencedStoryPayload(response,1,2).accepted===false);
      const mobile={narrative:hydration.text?[{type:'narration',text:hydration.text}]:[],choices:hydration.choices,in_combat:false}; record('mobile hydration is actionable',mobile.narrative.length===1&&mobile.choices.length===4&&!mobile.in_combat);
      for(const [label,value] of [['missing',undefined],['empty',[]],['malformed',[{text:''},{nope:true}]]]){const guarded=finalizeGeneratedStoryResult({narrative:`${label} choices`,choices:value,combat_trigger:false},{location:'fogbound shrine',requestId:`${secondId}-${label}`,previousChoices:secondGuard.choices});record(`${label} consecutive choices get safe replacement`,guarded.choice_guard.reason==='missing_or_malformed'&&guarded.choices.length===4&&JSON.stringify(guarded.choices)!==JSON.stringify(secondGuard.choices));}
      const wrong=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user,payload:{session_id:'missing',character_id:character.id,request_id:'wrong',skill:'Perception',dc:12}}); record('wrong linkage rejects 403',wrong.status===403);
      const beforeAsk=await base44.asServiceRole.entities.GameSession.get(session.id); const ask=await executeAskDungeonMasterCore(base44,{session_id:session.id,character_id:character.id,question:'What is visible?',request_id:'ask-consecutive'}); const afterAsk=await base44.asServiceRole.entities.GameSession.get(session.id); record('Ask DM remains read only',ask.body?.read_only===true&&JSON.stringify(beforeAsk.story_log)===JSON.stringify(afterAsk.story_log));
      const staleReceipt={...secondRoll.body.receipt,request_id:'auditor-stale',id:'auditor-stale'}; const staleSession=await base44.entities.GameSession.create({character_id:character.id,title:'Dynamic auditor fixture',current_location:'fogbound shrine',story_log:[{timestamp:'2026-09-01T00:03:00.000Z',request_id:'auditor-source',text:'Source scene',choices:choices('auditor-old')},{timestamp:'2026-09-01T00:04:00.000Z',request_id:'auditor-stale',text:'Preserved failed narration',choices:choices('auditor-old'),skill_check:staleReceipt}],world_state:{__skill_check_receipts:[staleReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',staleSession.id]);
      const scope={characterId:character.id,sessionId:staleSession.id,receiptKey:'auditor-fixture'}; const dry=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'dry_run',responseFormat:'guard_only',scope}); record('dynamic auditor classifies server persisted stale choices',dry.body.classification==='server_persisted_stale_choices'&&dry.body.safe_to_repair&&!!dry.body.apply_token);
      const applied=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:dry.body.apply_token,scope}); const replay=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'apply',applyToken:dry.body.apply_token,scope}); record('auditor applies at most one guarded write',applied.body.writes===1&&applied.body.postconditions?.narration_preserved&&applied.body.postconditions?.failed_result_preserved); record('auditor replay writes zero',replay.body.writes===0&&replay.body.replayed===true);
      const orphanReceipt={...secondRoll.body.receipt,request_id:'auditor-orphan',id:'auditor-orphan'}; const orphanSession=await base44.entities.GameSession.create({character_id:character.id,title:'Frontend hydration fixture',story_log:[{request_id:'orphan-source',timestamp:'2026-09-01T00:05:00.000Z',text:'Latest committed pair',choices:choices('orphan')}],world_state:{__skill_check_receipts:[orphanReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',orphanSession.id]); const orphan=await staleChoiceTransitionRepairCore({db:base44.asServiceRole,mode:'discover',scope:{characterId:character.id,sessionId:orphanSession.id,receiptKey:'orphan-fixture'}}); record('orphan receipt classifies frontend hydration stale',orphan.body.classification==='frontend_hydration_stale_choices'&&!orphan.body.safe_to_repair&&orphan.body.writes===0);
    } finally { for(const [entity,id] of fixtures.reverse()){let absent=false;try{await base44.asServiceRole.entities[entity].delete(id);}catch{}try{absent=!(await base44.asServiceRole.entities[entity].get(id));}catch{absent=true;}cleanup.push({entity,id,absent});} }
    record('cleanup fixtures absent',cleanup.every((item)=>item.absent)); const protectedAfter=await hashValue(await readProtectedDndState(base44.asServiceRole)); record('protected live IDs unchanged',protectedBefore===protectedAfter); const passed=results.filter((item)=>item.pass).length,allPass=passed===results.length; return Response.json({function_version:'test-consecutive-story-choice-v1.0.0',passed,failed:results.length-passed,total:results.length,all_pass:allPass,results,cleanup},{status:allPass?200:500});
  } catch(error){return Response.json({error:error.message||'Consecutive transition regression failed'},{status:500});}
}