export const CLASS_CHOICE_REVIEW_VERSION='class-choice-review-2014-v1.0.0';
export const RANGER_SKILLS=['Animal Handling','Athletics','Insight','Investigation','Nature','Perception','Stealth','Survival'];
export const ROGUE_SKILLS=['Acrobatics','Athletics','Deception','Insight','Intimidation','Investigation','Perception','Performance','Persuasion','Sleight of Hand','Stealth'];
export const FAVORED_ENEMIES=['Aberrations','Beasts','Celestials','Constructs','Dragons','Elementals','Fey','Fiends','Giants','Monstrosities','Oozes','Plants','Undead','Humanoids'];
export const FAVORED_TERRAINS=['Arctic','Coast','Desert','Forest','Grassland','Mountain','Swamp','Underdark'];
export const RANGER_STYLES=['archery','defense','dueling','two_weapon'];
export const HUNTER_PREY=['colossus_slayer','giant_killer','horde_breaker'];
const normal=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const unique=a=>[...new Set(Array.isArray(a)?a:[])];
export function classLevels(character={}){const secondary=(character.multiclass||[]).reduce((sum,e)=>sum+Number(e?.levels||0),0);const levels={[character.class]:Math.max(1,Number(character.level||1)-secondary)};for(const entry of character.multiclass||[])levels[entry.class]=(levels[entry.class]||0)+Number(entry.levels||0);return levels;}
const hasRogue=character=>Number(classLevels(character).Rogue||0)>=1;
const option=(value,allowed)=>allowed.some(item=>normal(item)===normal(value));
const confirmed=(choices,id)=>choices?.__review_confirmed?.[id]===true;
export function buildClassChoiceStatus(character={}){const levels=classLevels(character),choices=character.class_choices||{},requirements=[];const add=(id,label,count,options,mechanics)=>requirements.push({id,label,count,options,mechanics,status:confirmed(choices,id)?'confirmed':choices[id]!=null?'legacy_unconfirmed':'pending',value:choices[id]??null});
 if((levels.Ranger||0)>=1){add('ranger_skills','Ranger class skills',3,RANGER_SKILLS,'Selected skills add proficiency.');add('favored_enemy','Favored Enemy',1,FAVORED_ENEMIES,'Tracking and lore advantage when the check context names the confirmed enemy type.');add('favored_terrain','Natural Explorer terrain',1,FAVORED_TERRAINS,'Doubles proficiency for proficient Intelligence/Wisdom checks when context names the confirmed terrain.');}
 if((levels.Ranger||0)>=2)add('fighting_style','Ranger Fighting Style',1,RANGER_STYLES,'Archery, Defense, Dueling, and Two-Weapon Fighting use authoritative combat fields.');
 if((levels.Ranger||0)>=3&&normal(character.subclass).includes('hunter'))add('hunters_prey',"Hunter's Prey",1,HUNTER_PREY,'Colossus Slayer and Horde Breaker are implemented; Giant Killer remains descriptive because reaction range/trigger timing is unsupported.');
 if(hasRogue(character)){add('rogue_skill','Rogue multiclass skill',1,ROGUE_SKILLS,'Adds exactly one Rogue-list skill proficiency.');add('expertise','Rogue Expertise',2,Object.keys(character.skills||{}),'Doubles proficiency for exactly two confirmed proficient skills. Thieves’ tools Expertise is not represented by the current skill model.');}
 const legacy=(character.features||[]).filter(feature=>/favored enemy|natural explorer|fighting style|hunter.s prey|horde breaker|colossus slayer|giant killer|sneak attack|thieves. cant/i.test(String(feature)));
 return{version:CLASS_CHOICE_REVIEW_VERSION,edition:'2014/SRD 5.1',class_levels:levels,requirements,pending:requirements.filter(r=>r.status!=='confirmed').map(r=>r.id),legacy_unconfirmed:legacy,unsupported:[...((levels.Ranger||0)>=3&&normal(character.subclass).includes('hunter')?['Giant Killer reaction automation']:[]),...(hasRogue(character)?['Thieves’ tools Expertise selection']:[])],writes:0};}
export function validateClassChoice(character,id,value,workingChoices=character.class_choices||{},workingSkills=character.skills||{}){const levels=classLevels(character);if(id==='ranger_skills'){const values=unique(value);return values.length===3&&values.every(v=>option(v,RANGER_SKILLS))?{ok:true,value:values}:{ok:false,error:'Choose exactly 3 different Ranger skills.'};}
 if(id==='favored_enemy')return(levels.Ranger||0)>=1&&option(value,FAVORED_ENEMIES)?{ok:true,value:FAVORED_ENEMIES.find(v=>normal(v)===normal(value))}:{ok:false,error:'Choose 1 eligible favored enemy at Ranger level 1+.'};
 if(id==='favored_terrain')return(levels.Ranger||0)>=1&&option(value,FAVORED_TERRAINS)?{ok:true,value:FAVORED_TERRAINS.find(v=>normal(v)===normal(value))}:{ok:false,error:'Choose 1 eligible favored terrain at Ranger level 1+.'};
 if(id==='fighting_style')return(levels.Ranger||0)>=2&&RANGER_STYLES.includes(value)?{ok:true,value}:{ok:false,error:'Choose 1 eligible Ranger fighting style at Ranger level 2+.'};
 if(id==='hunters_prey')return(levels.Ranger||0)>=3&&normal(character.subclass).includes('hunter')&&HUNTER_PREY.includes(value)?{ok:true,value}:{ok:false,error:"Hunter's Prey requires Hunter Ranger level 3+."};
 if(id==='rogue_skill')return hasRogue(character)&&option(value,ROGUE_SKILLS)?{ok:true,value:ROGUE_SKILLS.find(v=>normal(v)===normal(value))}:{ok:false,error:'Choose 1 eligible Rogue skill at Rogue level 1+.'};
 if(id==='expertise'){const values=unique(value);const proficient=new Set(Object.entries(workingSkills).filter(([,rank])=>['proficient','expert',true].includes(rank)).map(([name])=>name));for(const name of workingChoices.ranger_skills||[])proficient.add(name);if(workingChoices.rogue_skill)proficient.add(workingChoices.rogue_skill);return hasRogue(character)&&values.length===2&&values.every(v=>proficient.has(v))?{ok:true,value:values}:{ok:false,error:'Choose exactly 2 different proficient skills for Rogue Expertise.'};}
 return{ok:false,error:'Unsupported class choice.'};}
const featureFor=(id,value)=>id==='favored_enemy'?`Favored Enemy: ${value}`:id==='favored_terrain'?`Natural Explorer: ${value}`:id==='hunters_prey'?`Hunter's Prey: ${String(value).split('_').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')}`:null;
export function planClassChoiceConfirmation(character={},selections={},requestId=''){const current=character.class_choices||{},receipts=current.__review_receipts||[];const prior=receipts.find(r=>r.request_id===requestId);if(prior)return{ok:true,replay:true,updates:{},receipt:prior};if(!requestId)return{ok:false,error:'request_id is required.'};const ids=Object.keys(selections);if(!ids.length)return{ok:false,error:'At least one explicit selection is required.'};let choices={...current};let skills={...(character.skills||{})};let features=[...(character.features||[])];const confirmedMap={...(current.__review_confirmed||{})};for(const id of ids){if(confirmedMap[id])return{ok:false,error:`${id} is already confirmed and cannot be silently respecced.`};const checked=validateClassChoice(character,id,selections[id],choices,skills);if(!checked.ok)return checked;choices[id]=checked.value;confirmedMap[id]=true;if(id==='ranger_skills')for(const skill of checked.value)if(skills[skill]!=='expert')skills[skill]='proficient';if(id==='rogue_skill'&&skills[checked.value]!=='expert')skills[checked.value]='proficient';if(id==='expertise')for(const skill of checked.value)skills[skill]='expert';if(id==='fighting_style'){}const feature=featureFor(id,checked.value);if(feature&&!features.some(v=>normal(v)===normal(feature)))features.push(feature);}
 const receipt={request_id:requestId,version:CLASS_CHOICE_REVIEW_VERSION,selections:Object.fromEntries(ids.map(id=>[id,choices[id]])),confirmed_ids:ids};choices={...choices,__review_confirmed:confirmedMap,__review_receipts:[...receipts.slice(-24),receipt]};const updates={class_choices:choices,skills,features,...(ids.includes('fighting_style')?{fighting_style:choices.fighting_style}:{})};return{ok:true,replay:false,updates,receipt};}
export function classChoiceSkillEffects(character={},skill='',context=''){const choices=character.class_choices||{},text=normal(context),effects={advantage_sources:[],proficiency_multiplier:null};if(confirmed(choices,'favored_enemy')&&text.includes(normal(choices.favored_enemy))&&['Survival','Arcana','History','Investigation','Nature','Religion'].includes(skill))effects.advantage_sources.push(`Favored Enemy: ${choices.favored_enemy}`);if(confirmed(choices,'favored_terrain')&&text.includes(normal(choices.favored_terrain))&&['Animal Handling','Insight','Medicine','Perception','Survival','Arcana','History','Investigation','Nature','Religion'].includes(skill))effects.proficiency_multiplier=2;return effects;}
export function isConfirmedChoice(character,id,value=null){const choices=character?.class_choices||{};return confirmed(choices,id)&&(value==null||normal(choices[id])===normal(value));}