import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { appendRecoverableItem, buildRecoverableItem } from '../../shared/story/recoveryTransaction.ts';
import { commitNarratedStoryInventoryRecovery, narrationMayPublishRecovery, validateNarratedRecovery } from '../../shared/story/narratedStoryInventoryCommit.ts';
import { discoverNarratedProjectileRecovery, reconcileLegacyNarratedProjectileRecovery } from '../../shared/repairs/narratedProjectileRecovery.ts';
import { hashValue, PROTECTED_DND_IDS, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

export default async function testNarratedStoryInventoryCommitRegression(req) {
  const base44 = createClientFromRequest(req); const db = base44.asServiceRole; const fixtures=[]; const cleanup=[]; const results=[];
  try {
    await req.json().catch(() => ({})); const protectedBefore = await hashValue(await readProtectedDndState(db)); const tag=`StoryInventoryQA_${Date.now()}`;
    const make=async(label, inventory=[{name:'Arrows',quantity:11,category:'Ammunition',stackable:true,unit:'arrow',stack_semantics:'individual'}])=>{const character=await db.entities.Character.create({name:`${tag}_${label}`,race:'Human',class:'Ranger',level:5,hp_max:44,hp_current:44,inventory,long_rest_abilities:{},is_active:false});const session=await db.entities.GameSession.create({character_id:character.id,title:`${tag}_${label}`,story_log:[],world_state:{},is_active:false});fixtures.push(['GameSession',session.id],['Character',character.id]);return {character,session};};
    const success={success:true,skill:'Perception',dc:12,raw_d20:17,final_total:20}; const failure={...success,success:false,raw_d20:1,final_total:4};
    const ordinary=['You recover your footing and regain focus.','You recover composure and strength, then find a safer route through the marsh.','You retrieve your bearings and recover ground.','You find information about the hidden path.','You tighten your grip on the already-carried documents.']; results.push({name:'movement state and abstract discovery idioms are not acquisitions',pass:ordinary.every((narrative)=>validateNarratedRecovery({narrative,recovery:{}}).status==='not_applicable')}); results.push({name:'concrete item claim without structure fails closed',pass:validateNarratedRecovery({narrative:'You recover exactly 7 arrows from the mud.',recovery:null}).status==='missing_exact_structured_recovery'}); results.push({name:'mismatched item quantity fails closed',pass:validateNarratedRecovery({narrative:'You recover exactly 7 arrows from the mud.',recovery:{type:'arrows',quantity:6}}).status==='mismatched_exact_structured_recovery'});
    const environmental=await make('environmental'); const payload={base44,sessionId:environmental.session.id,characterId:environmental.character.id,requestId:`${tag}:arrows`,check:success,recovery:{type:'arrows',quantity:7}}; const committed=await commitNarratedStoryInventoryRecovery(payload); const after=await db.entities.Character.get(environmental.character.id); const replay=await commitNarratedStoryInventoryRecovery(payload); results.push({name:'Perception success commits seven canonical arrows before narration and replay is zero-write',pass:committed.body.applied&&after.inventory.filter((item)=>item.name==='Arrows').length===1&&after.inventory.find((item)=>item.name==='Arrows').quantity===18&&replay.body.already_processed&&replay.body.writes===0&&narrationMayPublishRecovery({narrative:'You found 7 arrows.',committed:committed.body.applied})});
    const failed=await make('failed'); const failedBefore=await hashValue(await db.entities.Character.get(failed.character.id)); const failedCommit=await commitNarratedStoryInventoryRecovery({...payload,sessionId:failed.session.id,characterId:failed.character.id,requestId:`${tag}:failed`,check:failure}); results.push({name:'failed Perception writes zero and cannot narrate arrows found',pass:failedCommit.body.writes===0&&failedBefore===await hashValue(await db.entities.Character.get(failed.character.id))&&!narrationMayPublishRecovery({narrative:'You found 7 arrows.',committed:false})});
    const vague=await make('vague'); const vagueCommit=await commitNarratedStoryInventoryRecovery({...payload,sessionId:vague.session.id,characterId:vague.character.id,requestId:`${tag}:vague`,recovery:null}); results.push({name:'vague or ambiguous reward text has zero writes',pass:vagueCommit.body.writes===0&&!narrationMayPublishRecovery({narrative:'You find some arrows among the debris.',committed:false})===false});
    const mismatch=await commitNarratedStoryInventoryRecovery({...payload,sessionId:environmental.session.id,characterId:failed.character.id,requestId:`${tag}:mismatch`}); results.push({name:'wrong Character and Session is 403',pass:mismatch.status===403&&mismatch.body.writes===0});
    const duplicate=await make('duplicate',[{name:'Arrows',quantity:11},{name:'Arrows',quantity:2}]); const duplicateCommit=await commitNarratedStoryInventoryRecovery({...payload,sessionId:duplicate.session.id,characterId:duplicate.character.id,requestId:`${tag}:duplicate`}); results.push({name:'ambiguous existing stacks fail closed without duplicates',pass:duplicateCommit.status===409&&duplicateCommit.body.writes===0});
    const ledger=await make('ledger'); const combat=await db.entities.CombatLog.create({session_id:ledger.session.id,character_id:ledger.character.id,is_active:false,result:'victory',combatants:[{id:ledger.character.id,type:'player'}],log_entries:[]}); fixtures.push(['CombatLog',combat.id]); const entry=buildRecoverableItem({originRequestId:`${tag}:spent`,characterId:ledger.character.id,sessionId:ledger.session.id,combatId:combat.id,canonicalName:'Arrows',quantity:3,sourceAction:'shot'}); await db.entities.Character.update(ledger.character.id,{long_rest_abilities:appendRecoverableItem(ledger.character.long_rest_abilities,entry)}); const capped=await commitNarratedStoryInventoryRecovery({...payload,sessionId:ledger.session.id,characterId:ledger.character.id,requestId:`${tag}:capped`,recovery:{type:'recover_owned_items',combat_id:combat.id,items:[{canonical_item:'Arrows',quantity:7,origin_request_id:entry.origin_request_id}]}}); results.push({name:'spent-projectile recovery is capped by eligible ledger quantity',pass:capped.body.writes===0&&capped.body.applied===false});
    const legacy=await make('legacy'); await db.entities.GameSession.update(legacy.session.id,{story_log:[{timestamp:'2026-08-13T00:00:00.000Z',player_choice:'look around the area for any arrows',text:'Your Perception check was a success. You found 7 arrows among the roots.',skill_check:{skill:'Perception',success:true,final_total:18}}]}); const discovered=await discoverNarratedProjectileRecovery({db,characterId:legacy.character.id,sessionId:legacy.session.id}); const dry=await reconcileLegacyNarratedProjectileRecovery({db,characterId:legacy.character.id,sessionId:legacy.session.id,incidentKey:discovered.body.discovery?.incident_key,expectedHashes:discovered.body.protected_hashes,mode:'dry_run'}); const applied=await reconcileLegacyNarratedProjectileRecovery({db,characterId:legacy.character.id,sessionId:legacy.session.id,incidentKey:discovered.body.discovery?.incident_key,expectedHashes:discovered.body.protected_hashes,mode:'apply'}); const legacyAfter=await db.entities.Character.get(legacy.character.id); const replayLegacy=await reconcileLegacyNarratedProjectileRecovery({db,characterId:legacy.character.id,sessionId:legacy.session.id,incidentKey:discovered.body.discovery?.incident_key,expectedHashes:discovered.body.protected_hashes,mode:'apply'}); results.push({name:'exact legacy story discovery derives deterministic incident key and dry-run eleven to eighteen',pass:discovered.status===200&&!!discovered.body.discovery.incident_key&&dry.status===200&&dry.body.writes===0&&discovered.body.discovery.expected_post_repair_quantity===18}); results.push({name:'guarded legacy apply merges seven once and replay writes zero',pass:applied.status===200&&legacyAfter.inventory.filter((item)=>item.name==='Arrows').length===1&&legacyAfter.inventory.find((item)=>item.name==='Arrows').quantity===18&&replayLegacy.body.writes===0});
    const ambiguous=await make('ambiguous'); await db.entities.GameSession.update(ambiguous.session.id,{story_log:[{player_choice:'look around for arrows',text:'Perception success: found 7 arrows.',skill_check:{success:true}},{player_choice:'look around for arrows',text:'Perception success: found 7 arrows.',skill_check:{success:true}}]}); const ambiguity=await discoverNarratedProjectileRecovery({db,characterId:ambiguous.character.id,sessionId:ambiguous.session.id}); results.push({name:'ambiguous legacy candidates fail closed with zero writes',pass:ambiguity.status===409&&ambiguity.body.writes===0});
    results.push({name:'protected live records remain unchanged',pass:protectedBefore===await hashValue(await readProtectedDndState(db))});
  } catch(error) { results.push({name:'test execution',pass:false,detail:error.message}); }
  finally { for (const [entity,id] of fixtures.reverse()) { let deleted=false,verified_absent=false; try { await db.entities[entity].delete(id); deleted=true; } catch {} try { verified_absent=!(await db.entities[entity].get(id)); } catch { verified_absent=true; } cleanup.push({entity,id,deleted,verified_absent}); } }
  const cleanupPassed=cleanup.every((entry)=>entry.deleted&&entry.verified_absent); const passed=results.filter((entry)=>entry.pass).length; const allPass=passed===results.length&&cleanupPassed; return Response.json({deployment_id:'narrated-story-inventory-commit-v2',passed,failed:results.length-passed,total:results.length,all_pass:allPass,results,cleanup,cleanup_verified:cleanupPassed,protected_ids:PROTECTED_DND_IDS},{status:allPass?200:500});
}