import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { canonicalSkill, classifyLegacyChoiceAction, normalizeChoiceActionContract, CHOICE_ACTION_CONTRACT_VERSION } from '../../shared/story/choiceActionContract.js';
import { executeStoryWeaponAttack, STORY_WEAPON_ATTACK_VERSION } from '../../shared/story/storyWeaponAttack.ts';
import { hashValue, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

export default async function(req) {
  const fixtures=[]; const tests=[]; const test=(name,pass)=>tests.push({name,pass:!!pass});
  try {
    const base44=createClientFromRequest(req),user=await base44.auth.me(); if(!user||user.role!=='admin')return Response.json({error:'Admin access required.'},{status:403}); await req.json().catch(()=>({}));
    const protectedBefore=await hashValue(await readProtectedDndState(base44.asServiceRole));
    const exact='Take a precision shot to incapacitate the guard before he reaches cover.';
    for(const phrase of [exact,'Shoot the guard','Fire an arrow at the guard','Loose an arrow at the guard','Attack with longbow','Snipe the guard']) test(`legacy classifier routes: ${phrase}`,classifyLegacyChoiceAction(phrase)?.action_type==='weapon_attack');
    const malformed=normalizeChoiceActionContract({text:exact,skill_check:'Precision',dc:14}); test('weapon phrase dominates invalid skill metadata',malformed.action_type==='weapon_attack'&&malformed.skill_check===null&&malformed.weapon_attack.intent==='incapacitate_requested');
    test('real canonical skill remains skill check',normalizeChoiceActionContract({text:'Study the tracks',skill_check:'Survival',dc:12}).action_type==='skill_check'&&canonicalSkill('Survival')==='Survival');
    test('ambiguous nonmechanical legacy text fails closed to utility',normalizeChoiceActionContract({text:'Consider the situation',skill_check:'Precision'}).action_type==='utility');
    const makeFixture=async(label,{arrows=18,conditions=[],targetHp=30,targetAc=12}={})=>{const token=`Precision_${label}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;const character=await base44.entities.Character.create({name:token,race:'Human',class:'Ranger',level:6,dexterity:18,strength:10,proficiency_bonus:3,armor_class:16,hp_max:52,hp_current:52,spell_slots:{level_2:1},inventory:[{name:'Arrows',quantity:arrows},{name:'Unidentified Staff'}],equipped:{weapon:{name:'Longbow',type:'ranged',damage_dice:'1d8',damage_type:'piercing',properties:['Ammunition (150/600)','Heavy','Two-Handed']}},conditions,active_modifiers:[{name:'Pass without Trace',source:'Pass without Trace',effect:'skill_bonus',skill:'Stealth',bonus:10,concentration:true}],gold:20,xp:500,is_active:false});const session=await base44.asServiceRole.entities.GameSession.create({character_id:character.id,title:token,in_combat:false,combat_state:{},time_of_day:'Morning',world_state:{clock_hour:4,elapsed_hours:28,active_concentration:{spell_name:'Pass Without Trace'}},story_log:[],is_active:false});fixtures.push(['Character',character.id],['GameSession',session.id]);return{character,session,enemies:[{name:'Guard',hp:targetHp,ac:targetAc,attack_bonus:3,damage_dice:'1d6',damage_bonus:1,dexterity:10,cr:1,xp:100}]};};
    const pwt=await makeFixture('pwt'); const requestId=`shot:${pwt.session.id}:one`; const first=await executeStoryWeaponAttack({base44,user,sessionId:pwt.session.id,requestId,contract:{...malformed,text:exact},enemies:pwt.enemies,rollD20Fn:()=>10}); const pwtChar=await base44.asServiceRole.entities.Character.get(pwt.character.id); const pwtSession=await base44.asServiceRole.entities.GameSession.get(pwt.session.id); const replay=await executeStoryWeaponAttack({base44,user,sessionId:pwt.session.id,requestId,contract:{...malformed,text:exact},enemies:pwt.enemies,rollD20Fn:()=>20});
    test('exact phrase resolves authoritative attack and consumes one arrow',first.status===200&&first.body.success&&pwtChar.inventory[0].quantity===17&&first.body.ammunition?.consumed===1);
    test('PWT alone grants no attack advantage and concentration remains',first.body.advantage===false&&first.body.advantage_sources.length===0&&pwtChar.active_modifiers.some((m)=>m.concentration&&/pass without trace/i.test(m.source)));
    test('ranged incapacitate intent is recorded but never guaranteed',first.body.nonlethal_intent===true&&first.body.nonlethal_guaranteed===false&&/cannot guarantee a nonlethal knockout/i.test(first.body.narrative));
    test('surviving target leaves authoritative combat active',first.body.target_hp>0&&first.body.combat_active&&pwtSession.in_combat);
    test('replay returns receipt with zero writes and no second arrow',replay.body.already_processed===true&&replay.body.writes===0&&(await base44.asServiceRole.entities.Character.get(pwt.character.id)).inventory[0].quantity===17);
    const hidden=await makeFixture('hidden',{conditions:[{name:'stealthed',break_on_attack:true}],targetHp:2,targetAc:8}); const hiddenResult=await executeStoryWeaponAttack({base44,user,sessionId:hidden.session.id,requestId:`shot:${hidden.session.id}`,contract:{...malformed,text:exact},enemies:hidden.enemies,rollD20Fn:()=>20}); const hiddenChar=await base44.asServiceRole.entities.Character.get(hidden.character.id); test('exact structured concealment grants named advantage and breaks only hidden state',hiddenResult.body.advantage===true&&hiddenResult.body.advantage_sources.includes('Attacking from Stealthed/concealed')&&!hiddenChar.conditions.some((c)=>String(c.name||c).toLowerCase()==='stealthed')&&hiddenChar.active_modifiers.some((m)=>m.concentration));
    test('defeated sole target completes combat for narrative handoff',hiddenResult.body.target_hp===0&&hiddenResult.body.combat_active===false);
    const empty=await makeFixture('empty',{arrows:0}); const beforeEmpty=await hashValue(await base44.asServiceRole.entities.Character.get(empty.character.id)); const emptyResult=await executeStoryWeaponAttack({base44,user,sessionId:empty.session.id,requestId:`shot:${empty.session.id}`,contract:{...malformed,text:exact},enemies:empty.enemies,rollD20Fn:()=>20}); const afterEmpty=await hashValue(await base44.asServiceRole.entities.Character.get(empty.character.id)); const emptySession=await base44.asServiceRole.entities.GameSession.get(empty.session.id); test('pre-roll ammunition failure performs zero writes and starts no combat',emptyResult.status>=400&&emptyResult.body.writes===0&&beforeEmpty===afterEmpty&&!emptySession.in_combat);
    const wrong=await executeStoryWeaponAttack({base44,user,sessionId:'missing-session',requestId:'wrong',contract:malformed,enemies:[]}); test('mismatched or missing session rejects authoritatively',wrong.status===403);
    test('versions are explicit',malformed.contract_version===CHOICE_ACTION_CONTRACT_VERSION&&first.body.version===STORY_WEAPON_ATTACK_VERSION);
    const protectedAfter=await hashValue(await readProtectedDndState(base44.asServiceRole)); test('protected live records remain unchanged',protectedBefore===protectedAfter);
    const passed=tests.filter((entry)=>entry.pass).length;return Response.json({function_version:'precision-shot-choice-routing-regression-v1.0.0',contract_version:CHOICE_ACTION_CONTRACT_VERSION,attack_version:STORY_WEAPON_ATTACK_VERSION,passed,failed:tests.length-passed,total:tests.length,all_pass:passed===tests.length,tests,protected_live_state:{unchanged:protectedBefore===protectedAfter}},{status:passed===tests.length?200:500});
  } catch(error){return Response.json({error:error.message||'Precision-shot regression failed.',tests},{status:500});}
  finally{const base44=createClientFromRequest(req);for(const[entity,id]of fixtures.reverse()){try{await base44.asServiceRole.entities[entity].delete(id);}catch{}}}
}