import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { executeThrownWeaponAction, recoverThrownWeapon } from '../../shared/story/thrownWeaponAction.ts';
import { hashValue as hash, PROTECTED_DND_IDS as LIVE_IDS, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const readProtected = (base44) => readProtectedDndState(base44.asServiceRole);
const dagger = { name: 'Dagger', type: 'Weapon', category: 'Weapon', properties: ['finesse', 'light', 'thrown (range 20/60)'], damage_dice: '1d4', damage_type: 'piercing', source: 'Equipment Database', equipment_id: 'fixture-equipment-dagger', quantity: 1 };
const legacy = { name: 'Dagger', category: 'Weapon', properties: ['Finesse', 'Light', 'Thrown'], item_id: 'fixture-legacy-dagger', quantity: 1 };
export default async function testThrownWeaponRegression(req) {
  const fixtures = []; const cleanup = []; const results = [];
  try {
    const base44 = createClientFromRequest(req); await req.json().catch(() => ({}));
    const protectedBefore = await hash(await readProtected(base44));
    const make = async (label, inventory = [dagger, legacy, { name: 'Arrows', quantity: 0 }, { name: 'Rope', quantity: 1 }]) => {
      const character = await base44.asServiceRole.entities.Character.create({ name: `ThrownQA_${label}_${Date.now()}`, race: 'Human', class: 'Ranger', level: 5, hp_max: 30, hp_current: 30, inventory, equipped: { weapon: dagger }, long_rest_abilities: {}, is_active: false });
      const session = await base44.asServiceRole.entities.GameSession.create({ character_id: character.id, title: label, story_log: [], world_state: {}, is_active: false });
      fixtures.push({ character: character.id, session: session.id }); return { character, session };
    };
    const invoke = (fixture, id, weapon_attack, sessionId = fixture.session.id) => executeThrownWeaponAction({ base44, ownerId: fixture.character.created_by_id, payload: { session_id: sessionId, character_id: fixture.character.id, action_text: 'throw my Dagger at the wolf', request_id: id, weapon_attack } });
    const valid = await make('live-shape'); const before = await base44.asServiceRole.entities.Character.get(valid.character.id); const untouchedHash = await hash({ equipped: before.equipped, rope: before.inventory[3] });
    const hit = await invoke(valid, 'hit', { item_id: dagger.equipment_id, target: 'Necrotic Wolf', outcome: { committed: true, hit: true, kill: true } }); const afterHit = await base44.asServiceRole.entities.Character.get(valid.character.id);
    results.push({ name: 'exact live two-Dagger shape explicit item identity hit kill consumes only selected Dagger', pass: hit.status === 200 && hit.body.receipt?.kill && !(afterHit.inventory || []).some((item) => item.equipment_id === dagger.equipment_id) && (afterHit.inventory || []).some((item) => item.item_id === legacy.item_id) });
    const replay = await invoke(valid, 'hit', { item_id: dagger.equipment_id, target: 'Necrotic Wolf', outcome: { committed: true, hit: true, kill: true } });
    results.push({ name: 'attack replay consumes zero', pass: replay.body?.already_processed && replay.body?.writes === 0 });
    results.push({ name: 'unrelated inventory and equipped remain unchanged', pass: await hash({ equipped: afterHit.equipped, rope: afterHit.inventory.find((item) => item.name === 'Rope') }) === untouchedHash });
    const missFixture = await make('miss', [dagger, { name: 'Rope', quantity: 1 }]); const miss = await invoke(missFixture, 'miss', { item_id: dagger.equipment_id, target: 'Wolf', outcome: { committed: true, hit: false, kill: false } }); const missAfter = await base44.asServiceRole.entities.Character.get(missFixture.character.id);
    results.push({ name: 'committed miss consumes exactly one', pass: miss.status === 200 && !(missAfter.inventory || []).some((item) => item.equipment_id === dagger.equipment_id) });
    const ambiguous = await make('ambiguous'); const ambiguousBefore = await base44.asServiceRole.entities.Character.get(ambiguous.character.id); const ambiguousResult = await invoke(ambiguous, 'ambiguous', { target: 'Wolf', outcome: { committed: true, hit: true } }); const ambiguousAfter = await base44.asServiceRole.entities.Character.get(ambiguous.character.id);
    results.push({ name: 'ambiguous same-name selection fails closed', pass: ambiguousResult.status === 409 && await hash(ambiguousBefore.inventory) === await hash(ambiguousAfter.inventory) });
    const zero = await make('zero', [{ ...dagger, quantity: 0 }]); const zeroResult = await invoke(zero, 'zero', { item_id: dagger.equipment_id, target: 'Wolf', outcome: { committed: true, hit: false } });
    results.push({ name: 'quantity zero rejects', pass: zeroResult.status === 409 && zeroResult.body.writes === 0 });
    const failedRecovery = await recoverThrownWeapon({ base44, ownerId: valid.character.created_by_id, payload: { session_id: valid.session.id, character_id: valid.character.id, request_id: 'recover-fail', attack_request_id: 'hit', item_id: dagger.equipment_id, check: { success: false }, item: dagger } });
    results.push({ name: 'failed thrown recovery adds zero and arrows remain zero', pass: failedRecovery.body.recovered === 0 && failedRecovery.body.writes === 0 && (await base44.asServiceRole.entities.Character.get(valid.character.id)).inventory.find((item) => item.name === 'Arrows')?.quantity === 0 });
    const recovery = await recoverThrownWeapon({ base44, ownerId: valid.character.created_by_id, payload: { session_id: valid.session.id, character_id: valid.character.id, request_id: 'recover-success', attack_request_id: 'hit', item_id: dagger.equipment_id, check: { success: true }, item: dagger } }); const recovered = await base44.asServiceRole.entities.Character.get(valid.character.id);
    const recoveryReplay = await recoverThrownWeapon({ base44, ownerId: valid.character.created_by_id, payload: { session_id: valid.session.id, character_id: valid.character.id, request_id: 'recover-success', attack_request_id: 'hit', item_id: dagger.equipment_id, check: { success: true }, item: dagger } });
    results.push({ name: 'successful recovery adds exactly one matching item and replay adds zero', pass: recovery.body.recovered === 1 && recovered.inventory.filter((item) => item.equipment_id === dagger.equipment_id).reduce((sum, item) => sum + Number(item.quantity || 0), 0) === 1 && recoveryReplay.body.recovered === 0 && recoveryReplay.body.writes === 0 });
    const mismatch = await make('mismatch'); const mismatchBefore = await base44.asServiceRole.entities.Character.get(mismatch.character.id); const mismatchResult = await invoke(mismatch, 'mismatch', { item_id: dagger.equipment_id, target: 'Wolf', outcome: { committed: true, hit: true } }, valid.session.id); const mismatchAfter = await base44.asServiceRole.entities.Character.get(mismatch.character.id);
    const protectedAfter = await hash(await readProtected(base44));
    results.push({ name: 'Character Session mismatch returns 403 with zero writes and protected live records remain unchanged', pass: mismatchResult.status === 403 && mismatchResult.body.writes === 0 && await hash(mismatchBefore.inventory) === await hash(mismatchAfter.inventory) && protectedBefore === protectedAfter });
  } catch (error) { results.push({ name: 'test execution', pass: false, detail: error.message }); }
  finally { const base44 = createClientFromRequest(req); for (const fixture of fixtures.reverse()) for (const [entity, id] of [['GameSession', fixture.session], ['Character', fixture.character]]) { let deleted=false, verified_absent=false; try { await base44.asServiceRole.entities[entity].delete(id); deleted=true; } catch {} try { verified_absent=!(await base44.asServiceRole.entities[entity].get(id)); } catch { verified_absent=true; } cleanup.push({ entity,id,deleted,verified_absent }); } }
  const passed=results.filter((result)=>result.pass).length; const cleanupPassed=cleanup.every((entry)=>entry.deleted&&entry.verified_absent); return Response.json({ deployment_id:'thrown-dagger-pwt-playtest-repair-v1',passed,failed:results.length-passed,total:results.length,all_pass:passed===results.length&&cleanupPassed,results,cleanup,cleanup_passed:cleanupPassed,cleanup_verified:cleanupPassed,live_state:{protected_ids:LIVE_IDS,read_or_mutated:false}},{status:passed===results.length&&cleanupPassed?200:500});
}