import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { buildInfiltrationSessionUpdate, choiceSetSimilarity, guardInfiltrationBeat, planInfiltrationAdvancement, storyBeatSimilarity } from '../../shared/story/infiltrationSuccessAdvancement.ts';
import { commitStoryTransition } from '../../shared/story/storyTransition.ts';
import { hashValue,readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const choices=(label)=>[1,2,3,4].map((n)=>({text:`${label} changed option ${n}`,action_type:n===1?'movement':'skill_check',skill_check:n===1?null:'Perception',dc:n===1?null:10+n,risk_level:'medium'}));
export default async function(req){
  const base44=createClientFromRequest(req),fixtures=[],tests=[],cleanup=[],record=(name,pass)=>tests.push({name,pass:!!pass});
  try{
    const user=await base44.auth.me();if(!user||user.role!=='admin')return Response.json({error:'Admin required'},{status:403});await req.json().catch(()=>({}));const db=base44.asServiceRole,protectedBefore=await hashValue(await readProtectedDndState(db));
    try{
      const tag=`InfiltrationAdvance_${Date.now()}`,character=await base44.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:5,hp_max:40,hp_current:40,inventory:[{name:'Arrows',quantity:16}],is_active:false});fixtures.push(['Character',character.id]);
      const staticText='You remain still and patient, preserving your concealed vantage without betraying your position. The threat continues toward the bait, unaware of you, and no further action is taken.';
      const prior={request_id:'prior',text:staticText,choices:choices('prior')},firstId=`${tag}:first`,firstReceipt={id:firstId,request_id:firstId,skill:'Stealth',raw_d20:19,modifier_total:7,final_total:26,dc:12,success:true,unified_story_skill_resolution:true};
      let session=await db.entities.GameSession.create({character_id:character.id,title:tag,current_location:'apothecary loading bay',time_of_day:'Midnight',story_log:[prior],world_state:{clock_hour:4,elapsed_hours:0,__skill_check_receipts:[firstReceipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',session.id]);
      const firstPlan=planInfiltrationAdvancement({session,actionText:'Wait for the guard rotation and sneak through the cellar hatch.',check:firstReceipt,requestId:firstId});record('successful receipt plans structured scene advancement',firstPlan?.success&&firstPlan.after.stage===1&&firstPlan.after.progress===25&&firstPlan.after.discovered===false&&firstPlan.after.player_position==='inside_objective');record('waiting success advances clock fifteen minutes',firstPlan.clock?.clock.before_hour===4&&firstPlan.clock?.clock.after_hour===4.25&&firstPlan.clock?.clock.elapsed_hours===.25);
      let regenerations=0;const guarded=await guardInfiltrationBeat({candidate:{narrative:staticText,choices:prior.choices},previousEntry:prior,plan:firstPlan,regenerate:async()=>{regenerations++;return {narrative:'The guard commits to the far corner as you slip through the cellar hatch into the apothecary.',choices:choices('first'),combat_trigger:false};}});record('duplicate beat triggers one regeneration',guarded.guard.triggered&&guarded.guard.regenerated&&regenerations===1&&!guarded.guard.fallback_used);record('regenerated narration and choices are distinct',storyBeatSimilarity(prior.text,guarded.result.narrative)<.72&&choiceSetSimilarity(prior.choices,guarded.result.choices)<.82);
      const update=buildInfiltrationSessionUpdate({session,plan:firstPlan}),entry={request_id:firstId,text:guarded.result.narrative,choices:guarded.result.choices,skill_check:firstReceipt,scene_advancement:guarded.result.scene_advancement},commit=commitStoryTransition(session.story_log,entry,firstId);await db.entities.GameSession.update(session.id,{...update,story_log:commit.story_log});session=await db.entities.GameSession.get(session.id);record('scene state clock and story pair commit together',session.world_state.infiltration.stage===1&&session.world_state.clock_hour===4.25&&session.story_log.at(-1).request_id===firstId);
      const secondId=`${tag}:second`,secondReceipt={...firstReceipt,id:secondId,request_id:secondId,raw_d20:18,final_total:25};await db.entities.GameSession.update(session.id,{world_state:{...session.world_state,__skill_check_receipts:[firstReceipt,secondReceipt]}});session=await db.entities.GameSession.get(session.id);const secondPlan=planInfiltrationAdvancement({session,actionText:'Wait for the guard rotation and sneak through the cellar hatch.',check:secondReceipt,requestId:secondId}),secondGuard=await guardInfiltrationBeat({candidate:{narrative:staticText,choices:prior.choices},previousEntry:session.story_log.at(-1),plan:secondPlan,regenerate:async()=>null});record('repeated same intent escalates stage and bounded fallback',secondPlan.repeated_intent&&secondPlan.after.stage===2&&secondPlan.after.threat_position!==firstPlan.after.threat_position&&secondGuard.guard.fallback_used&&!/no further action is taken/i.test(secondGuard.result.narrative));record('bounded fallback choices evolve',choiceSetSimilarity(session.story_log.at(-1).choices,secondGuard.result.choices)<.82&&secondGuard.result.choices.length===4);
      const failedId=`${tag}:failed`,failedReceipt={...firstReceipt,id:failedId,request_id:failedId,raw_d20:2,final_total:9,success:false};await db.entities.GameSession.update(session.id,{world_state:{...session.world_state,__skill_check_receipts:[firstReceipt,secondReceipt,failedReceipt]}});session=await db.entities.GameSession.get(session.id);const failedPlan=planInfiltrationAdvancement({session,actionText:'Wait and watch the guard.',check:failedReceipt,requestId:failedId}),failedGuard=await guardInfiltrationBeat({candidate:{narrative:session.story_log.at(-1).text,choices:session.story_log.at(-1).choices},previousEntry:session.story_log.at(-1),plan:failedPlan,regenerate:async()=>null});record('failure path is distinct bounded and does not advance state',failedPlan.success===false&&failedPlan.writes===0&&failedGuard.guard.fallback_used&&failedGuard.result.narrative.length<500&&JSON.stringify(failedPlan.after)===JSON.stringify(failedPlan.before));
      const uncommitted={...secondReceipt,id:'uncommitted',request_id:'uncommitted'};record('no scene mutation plan without committed receipt',planInfiltrationAdvancement({session,actionText:'Wait for the guard.',check:uncommitted,requestId:'uncommitted'})===null);
      const replayPlan=planInfiltrationAdvancement({session,actionText:'Wait for the guard rotation and sneak through the cellar hatch.',check:firstReceipt,requestId:firstId});record('same advancement request is replay zero-write',replayPlan.replayed&&replayPlan.writes===0&&buildInfiltrationSessionUpdate({session,plan:replayPlan})===null);const rapidA=planInfiltrationAdvancement({session,actionText:'Wait for the guard rotation and sneak through the cellar hatch.',check:firstReceipt,requestId:firstId}),rapidB=planInfiltrationAdvancement({session,actionText:'Wait for the guard rotation and sneak through the cellar hatch.',check:firstReceipt,requestId:firstId});record('rapid repeated request dedupes deterministically',rapidA.replayed&&rapidB.replayed&&rapidA.receipt.request_id===rapidB.receipt.request_id);
      const beforeProtected=await hashValue(await readProtectedDndState(db));record('fixture mechanics leave protected state untouched during suite',beforeProtected===protectedBefore);
    }catch(error){record(`execution: ${error.message}`,false);}finally{for(const [entity,id] of fixtures.reverse()){let absent=false;try{await base44.asServiceRole.entities[entity].delete(id);}catch{}try{absent=!(await base44.asServiceRole.entities[entity].get(id));}catch{absent=true;}cleanup.push({entity,id,absent});}}
    record('cleanup verified absent',cleanup.every((item)=>item.absent));record('protected live unchanged',protectedBefore===await hashValue(await readProtectedDndState(base44.asServiceRole)));const passed=tests.filter((test)=>test.pass).length,all=passed===tests.length;return Response.json({function_version:'test-infiltration-success-advancement-v1.0.0',passed,failed:tests.length-passed,total:tests.length,all_pass:all,tests,cleanup},{status:all?200:500});
  }catch(error){return Response.json({error:error.message||'Infiltration advancement regression failed.'},{status:500});}
}