import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { executePlayerAttackCore } from '../../shared/combat/playerAttackCore.ts';
import { handlePlayerAttack } from '../../shared/combat/playerAttack.ts';
import { appendRecoverableItem, buildRecoverableItem, executeRecoveryTransaction } from '../../shared/story/recoveryTransaction.ts';
import { prepareProjectileRecoveryProposal, readLatestCompletedCombat, recoveryAnnotation, resolveExplicitThrownWeapon } from '../../shared/story/projectileLifecycle.ts';
import { resolveUnifiedStorySkillCheck } from '../../shared/story/unifiedStorySkillResolution.ts';
import { hashValue as hash, PROTECTED_DND_IDS, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const dagger = { name:'Dagger', item_id:'qa-dagger', category:'Weapon', type:'melee', properties:['Finesse','Light','Thrown'], damage_dice:'1d4', damage_type:'piercing', quantity:2 };
const bow = { name:'Longbow', equipment_id:'qa-bow', category:'Weapon', type:'ranged', properties:['Ammunition (150/600)','Heavy','Two-Handed'], damage_dice:'1d8', damage_type:'piercing', quantity:1 };
const arrows = { name:'Arrows', category:'Ammunition', stackable:true, unit:'arrow', stack_semantics:'individual', quantity:2 };

export default async function testNarratedProjectileRecoveryRegression(req) {
  const base44=createClientFromRequest(req); const fixtures=[]; const cleanup=[]; const results=[];
  try {
    await req.json().catch(()=>({})); const protectedBefore=await hash(await readProtectedDndState(base44.asServiceRole));
    const make=async(label, inventory=[dagger], turn=0, location='Test Clearing')=>{
      const tag=`ProjectileQA_${label}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
      const character=await base44.asServiceRole.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:5,strength:14,dexterity:18,constitution:12,intelligence:14,wisdom:14,charisma:10,proficiency_bonus:3,hp_max:40,hp_current:40,armor_class:15,inventory,equipped:{weapon:inventory[0]},long_rest_abilities:{},conditions:[],is_active:false});
      const session=await base44.asServiceRole.entities.GameSession.create({character_id:character.id,title:tag,current_location:location,in_combat:true,combat_state:{},story_log:[],world_state:{},is_active:false});
      const player={id:character.id,name:tag,type:'player',hp_current:40,hp_max:40,ac:15,is_conscious:true,conditions:[]}; const target={id:`${tag}-target`,name:'Target',type:'enemy',hp_current:200,hp_max:200,ac:12,is_conscious:true,conditions:[]}; const enemy={id:`${tag}-enemy`,name:'Other',type:'enemy',hp_current:200,hp_max:200,ac:12,is_conscious:true,conditions:[]};
      const combat=await base44.asServiceRole.entities.CombatLog.create({session_id:session.id,character_id:character.id,character_name:tag,location,round:1,current_turn_index:turn,is_active:true,result:'ongoing',combatants:[player,target,enemy],initiative_order:[],log_entries:[],world_state:{actions_used_this_turn:0}});
      await base44.asServiceRole.entities.GameSession.update(session.id,{combat_state:{combat_id:combat.id}}); fixtures.push(['CombatLog',combat.id],['GameSession',session.id],['Character',character.id]); return {character,session,combat,target};
    };
    const attack=(f,id,weapon,actionText,roll=15,target=f.target.id,session=f.session.id)=>executePlayerAttackCore({base44,sessionId:session,combatId:f.combat.id,characterId:f.character.id,ownerId:f.character.created_by_id,requestId:id,handler:handlePlayerAttack,rollD20Fn:()=>roll,payload:{target_id:target,weapon,spell:null,modifiers:{action_text:actionText}}});

    const thrown=await make('hit-miss',[dagger]); const hit=await attack(thrown,'dagger-hit',dagger,'throw my dagger at Target',15); const miss=await attack(thrown,'dagger-miss',dagger,'throw my dagger at Target',1); const thrownAfter=await base44.asServiceRole.entities.Character.get(thrown.character.id); const thrownCombat=await base44.asServiceRole.entities.CombatLog.get(thrown.combat.id);
    results.push({name:'free-text throw my dagger hit and miss each decrement one and record canonical identity',pass:hit.status===200&&miss.status===200&&thrownAfter.inventory.find(i=>i.item_id==='qa-dagger')?.quantity===0&&thrownCombat.log_entries.filter(e=>e.projectile?.item_id==='qa-dagger').length===2&&thrownCombat.log_entries.filter(e=>e.action==='player_attack'&&e.attack_mode==='thrown').length===2});
    const replay=await attack(thrown,'dagger-hit',dagger,'throw my dagger at Target',15); results.push({name:'attack replay writes zero',pass:replay.body.idempotent_replay===true&&(await base44.asServiceRole.entities.Character.get(thrown.character.id)).inventory.find(i=>i.item_id==='qa-dagger')?.quantity===0});

    const generic=await make('generic',[dagger]); const genericResult=await attack(generic,'generic',dagger,'attack Target',15); const genericAfter=await base44.asServiceRole.entities.Character.get(generic.character.id); results.push({name:'generic attack uses selected UI weapon without fabricating thrown consumption',pass:genericResult.status===200&&genericAfter.inventory[0].quantity===2&&!genericResult.body.log_entry?.projectile&&genericResult.body.log_entry?.weapon?.name==='Dagger'});
    const zero=resolveExplicitThrownWeapon({actionText:'throw my dagger at Target',inventory:[{...dagger,quantity:0}],selectedWeapon:dagger}); const ambiguous=resolveExplicitThrownWeapon({actionText:'throw my dagger at Target',inventory:[dagger,{...dagger,item_id:'qa-dagger-2'}],selectedWeapon:{name:'Dagger'}}); results.push({name:'quantity zero and ambiguous identity fail closed',pass:zero.handled&&!zero.ok&&ambiguous.handled&&!ambiguous.ok});
    const invalid=await make('invalid',[dagger]); const beforeInvalid=await hash(await Promise.all([base44.asServiceRole.entities.Character.get(invalid.character.id),base44.asServiceRole.entities.CombatLog.get(invalid.combat.id)])); const badTarget=await attack(invalid,'bad-target',dagger,'throw my dagger at Missing',15,'missing'); const badTurnFixture=await make('turn',[dagger],1); const beforeTurn=await hash(await Promise.all([base44.asServiceRole.entities.Character.get(badTurnFixture.character.id),base44.asServiceRole.entities.CombatLog.get(badTurnFixture.combat.id)])); const badTurn=await attack(badTurnFixture,'bad-turn',dagger,'throw my dagger at Target'); const mismatch=await attack(invalid,'mismatch',dagger,'throw my dagger at Target',15,invalid.target.id,badTurnFixture.session.id); const afterInvalid=await hash(await Promise.all([base44.asServiceRole.entities.Character.get(invalid.character.id),base44.asServiceRole.entities.CombatLog.get(invalid.combat.id)])); const afterTurn=await hash(await Promise.all([base44.asServiceRole.entities.Character.get(badTurnFixture.character.id),base44.asServiceRole.entities.CombatLog.get(badTurnFixture.combat.id)])); results.push({name:'wrong target turn and session mismatch reject with zero writes',pass:badTarget.status===404&&badTurn.status===409&&mismatch.status===403&&beforeInvalid===afterInvalid&&beforeTurn===afterTurn});

    const mixed=await make('mixed',[bow,dagger,arrows]); await attack(mixed,'arrow-shot',bow,'shoot Target',15); await attack(mixed,'dagger-shot',bow,'throw my dagger at Target',15); await base44.asServiceRole.entities.CombatLog.update(mixed.combat.id,{is_active:false,result:'victory'}); await base44.asServiceRole.entities.GameSession.update(mixed.session.id,{in_combat:false,combat_state:{}}); const mixedChar=await base44.asServiceRole.entities.Character.get(mixed.character.id); const spent=mixedChar.long_rest_abilities?.__spent_item_ledger||[]; results.push({name:'arrows and dagger each append combat-scoped immutable spent ledger entries',pass:spent.filter(e=>e.combat_id===mixed.combat.id).some(e=>e.canonical_item==='Arrows')&&spent.filter(e=>e.combat_id===mixed.combat.id).some(e=>e.canonical_item==='Dagger')&&spent.every(e=>e.action_request_id&&e.consumed_at&&e.quantity===1&&e.recoverability_state==='recoverable')});
    const freshSession=await base44.asServiceRole.entities.GameSession.get(mixed.session.id); const proposal=await prepareProjectileRecoveryProposal({base44,session:freshSession,character:mixedChar,actionText:'search to get my arrows and dagger back'}); const committed=await executeRecoveryTransaction({base44,ownerId:mixed.character.created_by_id,sessionId:mixed.session.id,characterId:mixed.character.id,combatId:mixed.combat.id,requestId:'mixed-recovery',outcome:{check:{success:true},recovery:proposal.recovery}}); const recovered=await base44.asServiceRole.entities.Character.get(mixed.character.id); const committedReplay=await executeRecoveryTransaction({base44,ownerId:mixed.character.created_by_id,sessionId:mixed.session.id,characterId:mixed.character.id,combatId:mixed.combat.id,requestId:'mixed-recovery',outcome:{check:{success:true},recovery:proposal.recovery}});
    results.push({name:'deterministic accessible mixed recovery uses no fake DC and atomically restores one canonical arrow and dagger stack',pass:proposal.requires_check===false&&proposal.dc===null&&proposal.recovery.rule.type==='automatic_recovery'&&committed.body.applied&&recovered.inventory.filter(i=>i.name==='Arrows').length===1&&recovered.inventory.find(i=>i.name==='Arrows')?.quantity===2&&recovered.inventory.find(i=>i.item_id==='qa-dagger')?.quantity===2});
    results.push({name:'recovery replay writes zero',pass:committedReplay.body.already_processed&&committedReplay.body.writes===0});

    const uncertain=await make('uncertain',[dagger]); await attack(uncertain,'uncertain-shot',dagger,'throw my dagger at Target',15); await base44.asServiceRole.entities.CombatLog.update(uncertain.combat.id,{is_active:false,result:'victory'}); await base44.asServiceRole.entities.GameSession.update(uncertain.session.id,{in_combat:false,combat_state:{},current_location:'Different Place'}); const uncertainSession=await base44.asServiceRole.entities.GameSession.get(uncertain.session.id); const uncertainChar=await base44.asServiceRole.entities.Character.get(uncertain.character.id); const uncertainProposal=await prepareProjectileRecoveryProposal({base44,session:uncertainSession,character:uncertainChar,actionText:'search for my dagger'}); const failed=await executeRecoveryTransaction({base44,sessionId:uncertain.session.id,characterId:uncertain.character.id,combatId:uncertain.combat.id,requestId:'uncertain-fail',outcome:{check:{success:false},recovery:uncertainProposal.recovery}}); const skill=await resolveUnifiedStorySkillCheck({db:base44.asServiceRole,user:null,payload:{session_id:uncertain.session.id,character_id:uncertain.character.id,request_id:'uncertain-skill',skill:'Investigation',dc:12,raw_d20:20,all_rolls:[20]}}); const succeeded=await executeRecoveryTransaction({base44,sessionId:uncertain.session.id,characterId:uncertain.character.id,combatId:uncertain.combat.id,requestId:'uncertain-success',outcome:{check:skill.body.receipt,recovery:uncertainProposal.recovery}});
    results.push({name:'uncertain recovery consumes one unified skill DC result; failure writes zero and success writes exact item',pass:uncertainProposal.requires_check&&uncertainProposal.dc===12&&failed.body.writes===0&&skill.body.success&&succeeded.body.applied&&succeeded.body.recovered_items[0].quantity===1});
    results.push({name:'recovery narration cannot claim success before inventory commit',pass:/no items recovered/i.test(recoveryAnnotation({recovery:uncertainProposal.recovery,resolution:{success:false,final_total:8},applied:false}))&&/committed to inventory/i.test(recoveryAnnotation({recovery:uncertainProposal.recovery,resolution:skill.body.receipt,applied:true,recoveredItems:succeeded.body.recovered_items}))});

    const anomaly=await make('anomaly',[dagger]); await base44.asServiceRole.entities.CombatLog.update(anomaly.combat.id,{is_active:false,result:'victory'}); await base44.asServiceRole.entities.GameSession.update(anomaly.session.id,{in_combat:false,combat_state:{}}); const anomalyEntry={...buildRecoverableItem({originRequestId:'legacy-dagger',characterId:anomaly.character.id,sessionId:anomaly.session.id,combatId:anomaly.combat.id,location:'Test Clearing',canonicalName:'Dagger',quantity:1,sourceAction:'legacy_generic_attack',itemSnapshot:dagger}),inventory_decrement_proven:false}; const anomalyChar=await base44.asServiceRole.entities.Character.get(anomaly.character.id); await base44.asServiceRole.entities.Character.update(anomaly.character.id,{long_rest_abilities:appendRecoverableItem(anomalyChar.long_rest_abilities,anomalyEntry)}); const anomalyRecovery=await executeRecoveryTransaction({base44,sessionId:anomaly.session.id,characterId:anomaly.character.id,combatId:anomaly.combat.id,requestId:'anomaly-recovery',outcome:{check:{success:true},recovery:{type:'recover_owned_items',items:[{canonical_item:'Dagger',quantity:1,origin_request_id:'legacy-dagger'}]}}}); const anomalyAfter=await base44.asServiceRole.entities.Character.get(anomaly.character.id); results.push({name:'preexisting missed decrement anomaly records reconciliation without duplicating dagger',pass:anomalyRecovery.body.recovered_items[0].anomaly_reconciled&&anomalyAfter.inventory[0].quantity===2});
    const unrelated=await make('unrelated',[dagger]); await base44.asServiceRole.entities.CombatLog.update(unrelated.combat.id,{is_active:false,result:'victory'}); const unrelatedResult=await executeRecoveryTransaction({base44,sessionId:anomaly.session.id,characterId:anomaly.character.id,combatId:unrelated.combat.id,requestId:'wrong-combat',outcome:{check:{success:true},recovery:{type:'recover_owned_items',items:[{canonical_item:'Dagger',quantity:1,origin_request_id:'legacy-dagger'}]}}}); results.push({name:'later unrelated combat items cannot be recovered',pass:unrelatedResult.status===409&&unrelatedResult.body.writes===0});
    const latest=await readLatestCompletedCombat(base44,mixed.session.id); results.push({name:'victory recovery handoff reads authoritative completed CombatLog',pass:latest?.id===mixed.combat.id&&latest.result==='victory'});
    const protectedAfter=await hash(await readProtectedDndState(base44.asServiceRole)); results.push({name:'all protected IDs remain unchanged',pass:protectedBefore===protectedAfter});
  } catch(error){results.push({name:'test execution',pass:false,detail:error.message});}
  finally{for(const [entity,id] of fixtures.reverse()){let deleted=false,verified_absent=false;try{await base44.asServiceRole.entities[entity].delete(id);deleted=true;}catch{}try{verified_absent=!(await base44.asServiceRole.entities[entity].get(id));}catch{verified_absent=true;}cleanup.push({entity,id,deleted,verified_absent});}}
  const passed=results.filter(r=>r.pass).length; const cleanupPassed=cleanup.every(r=>r.deleted&&r.verified_absent); return Response.json({deployment_id:'narrated-projectile-recovery-v1',passed,failed:results.length-passed,total:results.length,all_pass:passed===results.length&&cleanupPassed,results,cleanup,cleanup_passed:cleanupPassed,cleanup_verified:cleanupPassed,protected_ids:PROTECTED_DND_IDS},{status:passed===results.length&&cleanupPassed?200:500});
}