// ─── Portal Seed Data ─────────────────────────────────────────────────────────

export const COMPLICATIONS_TABLE = [
  { roll_min: 1,  roll_max: 15, id: 'wild_magic',      label: 'Wild Magic Surge',      icon: '🔮', color: '#c084fc', desc: 'A random magical effect erupts from your body as the unstable portal dumps raw arcane energy into the weave.', effect: 'wild_magic' },
  { roll_min: 16, roll_max: 30, id: 'bandit_ambush',   label: 'Bandit Ambush',          icon: '🗡️', color: '#fca5a5', desc: 'Rogues patrol this known arrival point. You emerge into an ambush!', effect: 'combat', enemies: ['Bandit x2'] },
  { roll_min: 31, roll_max: 45, id: 'stolen_gold',     label: 'Pickpocketed',           icon: '💰', color: '#fb923c', desc: 'Nimble fingers relieve you of some coin during the disorienting transit.', effect: 'lose_gold', dice: '2d20' },
  { roll_min: 46, roll_max: 58, id: 'wrong_location',  label: 'Wrong Destination',      icon: '🗺️', color: '#60a5fa', desc: 'The portal hiccuped. You arrive somewhere unintended — a nearby town you didn\'t plan for.', effect: 'wrong_dest' },
  { roll_min: 59, roll_max: 68, id: 'portal_fatigue',  label: 'Portal Fatigue',         icon: '😓', color: '#94a3b8', desc: 'Spatial transit tears at your constitution. You gain one level of exhaustion.', effect: 'exhaustion' },
  { roll_min: 69, roll_max: 76, id: 'psychic_damage',  label: 'Portal Feedback',        icon: '⚡', color: '#a78bfa', desc: 'Psychic backlash rips through your mind as the portal collapses behind you.', effect: 'damage', dice: '1d6', damage_type: 'psychic' },
  { roll_min: 77, roll_max: 85, id: 'delayed',         label: 'Time Dilation',          icon: '⏳', color: '#fde68a', desc: 'You arrive 1d4 hours later than expected, confused and disoriented.', effect: 'delay' },
  { roll_min: 86, roll_max: 93, id: 'cosmetic',        label: 'Wild Magic Cosmetic',    icon: '✨', color: '#86efac', desc: 'A harmless cosmetic effect — your hair turns green, you smell of sulfur, or you speak in rhyme for 1 hour.', effect: 'cosmetic' },
  { roll_min: 94, roll_max: 97, id: 'ally_separated',  label: 'Party Separated',        icon: '🔀', color: '#f472b6', desc: 'You arrive separately from any companions. They appear 1d10 minutes later nearby.', effect: 'separated' },
  { roll_min: 98, roll_max: 100,id: 'portal_collapse', label: 'Portal Collapse!',       icon: '💥', color: '#dc2626', desc: 'The portal explodes. You take 2d6 force damage and the portal goes permanently offline.', effect: 'collapse', dice: '2d6', damage_type: 'force' },
];

export const WILD_MAGIC_EFFECTS = [
  'You polymorphed into a potted plant for 1 minute.',
  'Fireworks erupt from your hands — 1d6 fire damage to you.',
  'You become invisible until you attack or cast a spell.',
  'You regain 2d10 hit points as wild healing magic floods through you.',
  'Three butterflies materialize and follow you for 24 hours.',
  'You are surrounded by faint, ethereal music only you can hear.',
  'Your skin turns blue for 1d8 hours.',
  'You teleport 20 feet in a random direction.',
  'A spectral cow appears next to you for 1 minute.',
  'You grow a magnificent beard that falls off after 1 hour.',
];

export const SANCTIONED_PORTALS_SEED = [
  {
    name: 'Waterdeep Central Nexus',
    city: 'Waterdeep',
    region: 'Sword Coast North',
    description: 'The grandest portal hub in the North, maintained by the Watchful Order of Magists. Gilded archways rise 30 feet, inscribed with protective runes.',
    destination_hubs: ["Baldur's Gate Southern Gate Hub", "Neverwinter Spellweave Station", "Luskan Arcane Exchange", "Daggerford Wayside Portal"],
    cost_gp: 75,
    guild_required: false,
    guild_discount_cost: 38,
    vip_only: false,
    flavor_text: 'The Guild seal pulses with warm golden light. A robed attendant bows. "Your destination, honored traveler?"',
    map_x: 35,
    map_y: 28,
    is_active: true,
  },
  {
    name: "Baldur's Gate Southern Gate Hub",
    city: "Baldur's Gate",
    region: 'Western Heartlands',
    description: "Operated by the Underchanters' Society under Guild license. Situated near the Basilisk Gate, busy with merchants and dignitaries.",
    destination_hubs: ['Waterdeep Central Nexus', "Neverwinter Spellweave Station", "Amn Trade Portal", "Daggerford Wayside Portal"],
    cost_gp: 90,
    guild_required: false,
    guild_discount_cost: 45,
    vip_only: false,
    flavor_text: 'A stern half-elf clerk stamps your travel parchment. "Declare all magical items, weapons drawn, and livestock before transit."',
    map_x: 32,
    map_y: 55,
    is_active: true,
  },
  {
    name: 'Neverwinter Spellweave Station',
    city: 'Neverwinter',
    region: 'Sword Coast North',
    description: "Rebuilt after the Spellplague. Lord Neverember's personal investment — gleaming white marble with sapphire inlays, a symbol of the city's resurgence.",
    destination_hubs: ['Waterdeep Central Nexus', "Baldur's Gate Southern Gate Hub", "Luskan Arcane Exchange", "Silverymoon Moongate"],
    cost_gp: 80,
    guild_required: false,
    guild_discount_cost: 40,
    vip_only: false,
    flavor_text: '"Welcome to Neverwinter, gem of the North. Your journey continues safely under Neverember\'s protection." The attendant smiles warmly.',
    map_x: 28,
    map_y: 20,
    is_active: true,
  },
  {
    name: 'Luskan Arcane Exchange',
    city: 'Luskan',
    region: 'Sword Coast North',
    description: 'Run by the Arcane Brotherhood under a Guild special exemption. Functional but grim — skull motifs carved into every arch, ravens on the rafters.',
    destination_hubs: ['Waterdeep Central Nexus', 'Neverwinter Spellweave Station'],
    cost_gp: 60,
    guild_required: true,
    guild_discount_cost: 30,
    vip_only: false,
    flavor_text: 'A tattooed Brotherhood mage eyes you coldly. "Guild card. Now. No card, no transit — unless you want to *donate* a memory."',
    map_x: 22,
    map_y: 12,
    is_active: true,
  },
  {
    name: 'Daggerford Wayside Portal',
    city: 'Daggerford',
    region: 'Delimbiyr Vale',
    description: 'A modest portal station maintained by a single Guild-licensed wizard, Alura Carver. Popular with travelers between Waterdeep and the south.',
    destination_hubs: ['Waterdeep Central Nexus', "Baldur's Gate Southern Gate Hub"],
    cost_gp: 50,
    guild_required: false,
    guild_discount_cost: 25,
    vip_only: false,
    flavor_text: '"Oh! A traveler! Lovely. I\'ve got tea on. Would you like tea before you go? No? Alright then, let me just—" She fumbles with her keys. Charming.',
    map_x: 33,
    map_y: 40,
    is_active: true,
  },
  {
    name: 'Silverymoon Moongate',
    city: 'Silverymoon',
    region: 'Luruar',
    description: 'The most beautiful portal in the North — a shimmering crescent of pure moonstone built by High Mage Alustriel. Admission by invitation or Guild membership.',
    destination_hubs: ['Neverwinter Spellweave Station', 'Waterdeep Central Nexus'],
    cost_gp: 120,
    guild_required: true,
    guild_discount_cost: 60,
    vip_only: false,
    flavor_text: '"Only those of lawful standing may pass the Moongate. Your soul is weighed, traveler." A silver glow scans you head to toe.',
    map_x: 55,
    map_y: 18,
    is_active: true,
  },
];

export const SKETCHY_PORTALS_SEED = [
  // Waterdeep
  {
    name: "Gorzod's Back-Alley Gate",
    city: 'Waterdeep',
    location_desc: "Dock Ward alley, behind the Splashing Nixie tavern",
    operator_name: 'Gorzod the Unhinged',
    operator_personality: 'Manic, unpredictable, brilliant but dangerously unstable wild mage',
    operator_greeting: '"20 gold or I feed you to the gelatinous cube! She hasn\'t eaten today and she\'s VERY hungry! Also I may have miscalibrated the portal slightly. Slightly."',
    description: 'A shimmering purple tear in reality wedged between two dumpsters. Smells of cabbage and ozone. The operator argues constantly with his familiar.',
    destinations: ['Luskan Docks Fragment', "Amn Smuggler's Circle", "Baldur's Gate Undercity Rift"],
    cost_gp: 20,
    safety_pct: 60,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'The portal crackles violet and green. Something on the other side is screaming — but Gorzod assures you that\'s normal.',
    map_x: 35,
    map_y: 29,
    is_active: true,
  },
  {
    name: "Mira's Exile Gate",
    city: 'Waterdeep',
    location_desc: "Castle Ward basement, beneath the Yawning Portal Inn",
    operator_name: 'Mira the Exile',
    operator_personality: 'Quiet, precise, former Zhentarim spellweaver with a price on her head',
    operator_greeting: '"Quietly now. Kingdom guards patrol the alley above. 30 gold, no questions, no names. The portal holds — I tested it this morning. Mostly."',
    description: 'A precise hexagonal portal etched with Netherese-style sigils. Remarkably stable for an illegal operation. Mira keeps meticulous notes.',
    destinations: ['Neverwinter Shadow Quarter', "Baldur's Gate Undercity Rift", 'Daggerford Mill Breach'],
    cost_gp: 30,
    safety_pct: 75,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'Mira traces a final rune, whispers an incantation in Netherese, and the gate hums to life — crisp, professional, and entirely illegal.',
    map_x: 35,
    map_y: 30,
    is_active: true,
  },
  // Baldur's Gate
  {
    name: "Undercity Rift",
    city: "Baldur's Gate",
    location_desc: "Undercity sewers, below the Elfsong Tavern",
    operator_name: 'Zareth Shadowfen',
    operator_personality: 'Drow smuggler, calm and businesslike, dangerous when crossed',
    operator_greeting: '"Surface coin. No barter. No sob stories. My portal, my rules. 15 gold goes where 15 gold goes — could be Waterdeep, could be somewhere... interesting."',
    description: 'A drow-made portal of dark crystal and shadow-silk threads. Destinations shift based on lunar cycles. Zareth rarely explains the complications.',
    destinations: ["Gorzod's Back-Alley Gate", 'Luskan Docks Fragment', "Mira's Exile Gate"],
    cost_gp: 15,
    safety_pct: 55,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'The drow crystal hums with shadow-light. Zareth watches you step through with an expression that could be amusement or contempt.',
    map_x: 32,
    map_y: 56,
    is_active: true,
  },
  {
    name: "Bhallar's Ruined Tower Gate",
    city: "Baldur's Gate",
    location_desc: "Outside city walls, collapsed wizard tower, Outer City",
    operator_name: 'Bhallar Greystone',
    operator_personality: 'Elderly, deaf, perpetually confused gnome wizard who may have created this portal centuries ago and forgotten',
    operator_greeting: '"EH? PORTAL? YES PORTAL! Five silver! No wait — five gold! OR IS IT FIVE PLATINUM? WHAT YEAR IS IT? Are you a cheese merchant? You look like a cheese merchant."',
    description: 'An ancient portal embedded in the ruins of a pre-Spellplague tower. Bhallar stumbled upon it 40 years ago and has operated it ever since without fully understanding it.',
    destinations: ['Amn Smuggler\'s Circle', 'Daggerford Mill Breach', 'Neverwinter Shadow Quarter'],
    cost_gp: 8,
    safety_pct: 40,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'Bhallar yanks a dangling crystal and the portal roars to life, flashing through seventeen colors. "THERE! PROBABLY FINE!" he bellows cheerfully.',
    map_x: 31,
    map_y: 57,
    is_active: true,
  },
  // Neverwinter
  {
    name: 'Neverwinter Shadow Quarter Gate',
    city: 'Neverwinter',
    location_desc: "Blacklake District, under a fishmonger's stall",
    operator_name: 'The Velvet Hood',
    operator_personality: 'Unknown identity, speaks through magical mask, extremely professional',
    operator_greeting: '"25 gold. Your identity is forgotten the moment you step through. My portals are clean. My discretion is absolute. Do we have an accord?"',
    description: 'The most professional illegal portal in the North. The Velvet Hood has never had a fatality — impressive given the clientele.',
    destinations: ["Mira's Exile Gate", "Gorzod's Back-Alley Gate", 'Silverymoon Hidden Grove'],
    cost_gp: 25,
    safety_pct: 80,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'The portal shimmers like black velvet. No sound, no smell, no trace. The Velvet Hood nods once.',
    map_x: 28,
    map_y: 21,
    is_active: true,
  },
  {
    name: 'Luskan Docks Fragment',
    city: 'Luskan',
    location_desc: "Ship graveyard, rotting dock 7, under a collapsed hull",
    operator_name: 'One-Eye Vaskar',
    operator_personality: 'Sea-weathered half-orc pirate who discovered this portal in a wreck and charges for use',
    operator_greeting: '"Twelve gold. Don\'t touch anything. Don\'t BREATHE on anything. That hull\'s held this portal for thirty years and I will NOT have you breathing on it."',
    description: 'A salt-crusted portal wedged inside a ship\'s ballast room. Smells overwhelmingly of brine and tar. Destination varies with tide cycles, Vaskar claims.',
    destinations: ["Gorzod's Back-Alley Gate", "Bhallar's Ruined Tower Gate", 'Waterdeep Docks Shadow'],
    cost_gp: 12,
    safety_pct: 50,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'The portal throbs like a heartbeat — slow, nautical, salt-stained. Vaskar watches with his one good eye.',
    map_x: 22,
    map_y: 13,
    is_active: true,
  },
  // Extra locations
  {
    name: "Amn Smuggler's Circle",
    city: 'Amn',
    location_desc: "Jungle clearing south of Athkatla, Gnoll territory",
    operator_name: 'The Three Sisters',
    operator_personality: 'Trio of tiefling merchants who rotate portal duties. Cheerful, terrifyingly organized crime.',
    operator_greeting: '"Welcome, welcome! Twenty-five gold — split three ways of course. Our portal is *usually* accurate. Roughly. Statistically."',
    description: 'A beautifully maintained portal in a jungle clearing, surrounded by tiefling mercenary guards and a surprisingly good food stall.',
    destinations: ["Baldur's Gate Undercity Rift", "Bhallar's Ruined Tower Gate", 'Waterdeep Docks Shadow'],
    cost_gp: 25,
    safety_pct: 65,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 10,
    flavor_text: 'Exotic incense mingles with jungle air. A tiefling hands you a clay token. "For the arrivals log. We like records."',
    map_x: 42,
    map_y: 72,
    is_active: true,
  },
  {
    name: 'Daggerford Mill Breach',
    city: 'Daggerford',
    location_desc: "Beneath the old mill, waterwheel chamber",
    operator_name: 'Pell Wheatsworth',
    operator_personality: 'Halfling miller who has no idea how this portal got in his basement but charges 10 gold regardless',
    operator_greeting: '"Aye, ten gold. She opens every night when the wheel turns. I don\'t know how, I don\'t know why, I just... charge. Mill\'s been in the family 400 years, *probably* haunted."',
    description: 'A naturally occurring wild portal that manifests in the waterwheel chamber every evening. Pell just started charging after the third uninvited visitor dropped in.',
    destinations: ["Mira's Exile Gate", "Bhallar's Ruined Tower Gate"],
    cost_gp: 10,
    safety_pct: 45,
    complications: COMPLICATIONS_TABLE,
    reputation_required: 0,
    flavor_text: 'The waterwheel churns and the portal blooms from the spray — chaotic, beautiful, smelling of flour and wild magic.',
    map_x: 33,
    map_y: 41,
    is_active: true,
  },
];

export const WORLD_LOCATIONS = [
  { name: 'Waterdeep',      region: 'Sword Coast North',    x: 35, y: 28, desc: 'The City of Splendors, greatest metropolis of the Sword Coast.' },
  { name: "Baldur's Gate",  region: 'Western Heartlands',   x: 32, y: 55, desc: 'The jewel of the Sword Coast, a city of wealth and shadows.' },
  { name: 'Neverwinter',    region: 'Sword Coast North',    x: 28, y: 20, desc: 'The Jewel of the North, rebuilt after the Spellplague.' },
  { name: 'Luskan',         region: 'Sword Coast North',    x: 22, y: 12, desc: 'The City of Sails, home to pirates and the Arcane Brotherhood.' },
  { name: 'Daggerford',     region: 'Delimbiyr Vale',       x: 33, y: 40, desc: 'A modest market town on the Trade Way.' },
  { name: 'Silverymoon',    region: 'Luruar',               x: 55, y: 18, desc: 'The Gem of the North, city of art and magic.' },
  { name: 'Amn',            region: 'Amn',                  x: 42, y: 72, desc: 'A mercantile nation of wealth and intrigue.' },
];