// D&D 5e PHB + Common Feats Data
export const FEATS = [
  {
    name: "Alert",
    prerequisite: null,
    category: "General",
    description: "Always on the lookout for danger, you gain the following benefits: +5 bonus to initiative, you can't be surprised while you are conscious, and other creatures don't gain advantage on attack rolls against you as a result of being unseen by you.",
    benefits: ["+5 Initiative", "Can't be surprised", "No hidden attacker advantage"],
    tags: ["initiative", "defense"],
  },
  {
    name: "Athlete",
    prerequisite: null,
    category: "General",
    description: "You have undergone extensive physical training to gain the following benefits: +1 STR or DEX, when you are prone, standing up uses only 5 feet of movement, climbing doesn't halve your speed, running long jump or high jump only requires 5 feet of movement beforehand.",
    benefits: ["+1 STR or DEX", "Stand from prone with 5 ft", "Climb at full speed"],
    tags: ["strength", "dexterity", "mobility"],
    asi_choices: ["strength", "dexterity"],
  },
  {
    name: "Actor",
    prerequisite: null,
    category: "Social",
    description: "+1 CHA. Skilled at mimicry and misdirection, you can mimic the speech of another person or sounds made by other creatures. You gain advantage on Deception and Performance checks when trying to pass yourself off as a different person, and you can mimic another person's speech if you've heard them speak for at least 1 minute.",
    benefits: ["+1 CHA", "Advantage on Deception/Performance (disguise)", "Mimic voices"],
    tags: ["charisma", "social", "deception"],
    asi_bonus: { charisma: 1 },
  },
  {
    name: "Charger",
    prerequisite: null,
    category: "Combat",
    description: "When you use your action to Dash, you can use a bonus action to make one melee weapon attack or to shove a creature. If you move at least 10 feet in a straight line immediately before taking this bonus action, you either gain a +5 bonus to the attack's damage roll (if you chose the melee attack) or push the target up to 10 feet away from you (if you chose to shove).",
    benefits: ["Bonus attack or shove after Dash", "+5 damage on charge attack", "Push target 10 ft"],
    tags: ["combat", "melee", "mobility"],
  },
  {
    name: "Crossbow Expert",
    prerequisite: null,
    category: "Combat",
    description: "Ignore loading property of crossbows you are proficient with. Being within 5 feet of a hostile creature doesn't impose disadvantage on your ranged attack rolls. When you use the Attack action and attack with a one-handed weapon, you can use a bonus action to attack with a loaded hand crossbow you are holding.",
    benefits: ["Ignore crossbow loading", "No melee range penalty", "Bonus hand crossbow attack"],
    tags: ["combat", "ranged", "crossbow"],
  },
  {
    name: "Defensive Duelist",
    prerequisite: "DEX 13+",
    category: "Combat",
    description: "When you are wielding a finesse weapon with which you are proficient and another creature hits you with a melee attack, you can use your reaction to add your proficiency bonus to your AC for that attack, potentially causing the attack to miss you.",
    benefits: ["Reaction: +proficiency bonus to AC vs one melee hit"],
    tags: ["combat", "melee", "defense", "reaction"],
    stat_req: { dexterity: 13 },
  },
  {
    name: "Dual Wielder",
    prerequisite: null,
    category: "Combat",
    description: "+1 AC while wielding a melee weapon in each hand. You can use two-weapon fighting even when the one-handed melee weapons aren't light. You can draw or stow two one-handed weapons when you would normally draw or stow only one.",
    benefits: ["+1 AC dual wielding", "Can dual wield non-light weapons", "Draw two weapons at once"],
    tags: ["combat", "melee", "two-weapon"],
  },
  {
    name: "Dungeon Delver",
    prerequisite: null,
    category: "Exploration",
    description: "Alert to the hidden traps and secret doors found in many dungeons: Advantage on Perception and Investigation checks to detect secret doors, advantage on saves vs traps, resistance to damage dealt by traps, can search for traps while traveling at a normal pace.",
    benefits: ["Adv. on trap/secret door detection", "Adv. on saves vs traps", "Trap damage resistance"],
    tags: ["exploration", "traps"],
  },
  {
    name: "Durable",
    prerequisite: null,
    category: "Survival",
    description: "+1 CON. When you roll a Hit Die to regain hit points, the minimum number of HP you regain from the roll equals twice your Constitution modifier (minimum of 2).",
    benefits: ["+1 CON", "Minimum 2× CON mod HP on hit dice"],
    tags: ["constitution", "healing", "survival"],
    asi_bonus: { constitution: 1 },
  },
  {
    name: "Elemental Adept",
    prerequisite: "Spellcasting or Pact Magic",
    category: "Magic",
    description: "Choose a damage type: acid, cold, fire, lightning, or thunder. Spells you cast ignore resistance to that damage type. When you roll damage for a spell of the chosen type, you can treat any 1 on a damage die as a 2. Can be taken multiple times, choosing a new type each time.",
    benefits: ["Ignore resistance to chosen element", "Min 2 on damage dice"],
    tags: ["magic", "damage", "spellcasting"],
    caster_only: true,
  },
  {
    name: "Grappler",
    prerequisite: "STR 13+",
    category: "Combat",
    description: "+1 STR. Advantage on attack rolls against a creature you are grappling. You can pin a grappled creature by making another grapple check (both restrained while pinned).",
    benefits: ["+1 STR", "Adv. attacks vs grappled target", "Can restrain grappled creature"],
    tags: ["combat", "melee", "strength", "grapple"],
    stat_req: { strength: 13 },
    asi_bonus: { strength: 1 },
  },
  {
    name: "Great Weapon Master",
    prerequisite: null,
    category: "Combat",
    description: "On a critical hit or killing a creature with a melee weapon, you can make one melee weapon attack as a bonus action. Before making a melee attack with a heavy weapon you are proficient with, you can take a -5 penalty to the attack roll. If the attack hits, you add +10 to the damage roll.",
    benefits: ["Bonus attack on crit or kill", "-5 hit / +10 damage option"],
    tags: ["combat", "melee", "heavy weapon", "damage"],
  },
  {
    name: "Healer",
    prerequisite: null,
    category: "Support",
    description: "When you stabilize a dying creature with a healer's kit, that creature regains 1 HP. As an action, you can spend a use of a healer's kit to tend to a creature, restoring 1d6+4 HP + the creature's maximum number of Hit Dice. A creature can only benefit from this feat once per short rest.",
    benefits: ["Stabilized creatures regain 1 HP", "1d6+4+HD healing with kit (1/SR)"],
    tags: ["healing", "support"],
  },
  {
    name: "Heavily Armored",
    prerequisite: "Medium Armor proficiency",
    category: "Armor",
    description: "+1 STR. Gain proficiency with heavy armor.",
    benefits: ["+1 STR", "Heavy armor proficiency"],
    tags: ["armor", "strength"],
    asi_bonus: { strength: 1 },
  },
  {
    name: "Heavy Armor Master",
    prerequisite: "Heavy armor proficiency",
    category: "Armor",
    description: "+1 STR. While wearing heavy armor, bludgeoning, piercing, and slashing damage from non-magical attacks is reduced by 3.",
    benefits: ["+1 STR", "-3 nonmagical physical damage in heavy armor"],
    tags: ["armor", "defense", "strength"],
    asi_bonus: { strength: 1 },
  },
  {
    name: "Inspiring Leader",
    prerequisite: "CHA 13+",
    category: "Support",
    description: "You can spend 10 minutes inspiring your companions, giving up to 6 friendly creatures (including yourself) temporary HP equal to your level + your Charisma modifier.",
    benefits: ["Grant level+CHA temp HP to 6 creatures (after rest)"],
    tags: ["charisma", "support", "temp hp"],
    stat_req: { charisma: 13 },
  },
  {
    name: "Keen Mind",
    prerequisite: null,
    category: "Utility",
    description: "+1 INT. You always know which way is north. You always know the number of hours left before the next sunrise or sunset. You can accurately recall anything you have seen or heard within the past month.",
    benefits: ["+1 INT", "Perfect navigation sense", "Perfect month-long recall"],
    tags: ["intelligence", "utility"],
    asi_bonus: { intelligence: 1 },
  },
  {
    name: "Lightly Armored",
    prerequisite: null,
    category: "Armor",
    description: "+1 STR or DEX. Gain proficiency with light armor.",
    benefits: ["+1 STR or DEX", "Light armor proficiency"],
    tags: ["armor"],
    asi_choices: ["strength", "dexterity"],
  },
  {
    name: "Linguist",
    prerequisite: null,
    category: "Utility",
    description: "+1 INT. You learn three languages of your choice. You can imbue hidden messages in your writing; a DC 15 INT check is needed to decipher the coded message.",
    benefits: ["+1 INT", "Learn 3 languages", "Create coded messages"],
    tags: ["intelligence", "languages", "utility"],
    asi_bonus: { intelligence: 1 },
  },
  {
    name: "Lucky",
    prerequisite: null,
    category: "General",
    description: "You have 3 luck points. Whenever you make an attack roll, ability check, or saving throw, you can spend one luck point to roll an additional d20 and choose which to use. You can also spend a luck point when an attack roll is made against you to impose disadvantage on that roll. Luck points refresh on a long rest.",
    benefits: ["3 luck points/LR", "Reroll any d20 and choose result", "Force enemy attack disadvantage"],
    tags: ["luck", "reroll", "defense"],
  },
  {
    name: "Mage Slayer",
    prerequisite: null,
    category: "Combat",
    description: "When a creature within 5 feet of you casts a spell, you can use your reaction to make a melee weapon attack against that creature. When you damage a creature that is concentrating on a spell, it has disadvantage on the Constitution saving throw to maintain concentration. You have advantage on saving throws against spells cast by creatures within 5 feet of you.",
    benefits: ["Reaction attack vs nearby caster", "Disadvantage on concentration saves you cause", "Adv. saves vs adjacent spells"],
    tags: ["combat", "anti-magic", "reaction"],
  },
  {
    name: "Magic Initiate",
    prerequisite: null,
    category: "Magic",
    description: "Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. Learn 2 cantrips and 1 first-level spell from that class's list. You can cast the 1st-level spell once per long rest without expending a spell slot. INT, WIS, or CHA is your spellcasting ability for these spells.",
    benefits: ["2 cantrips from chosen class", "1st-level spell 1/LR"],
    tags: ["magic", "utility", "multiclass"],
  },
  {
    name: "Martial Adept",
    prerequisite: null,
    category: "Combat",
    description: "You learn two maneuvers from the Battle Master archetype. Gain a superiority die (d6). The die is expended when you use it, and regained on a short or long rest. If you already have superiority dice, gain one more die of the same type.",
    benefits: ["2 Battle Master maneuvers", "+1 superiority die (d6)"],
    tags: ["combat", "maneuvers", "fighter"],
  },
  {
    name: "Medium Armor Master",
    prerequisite: "Medium armor proficiency",
    category: "Armor",
    description: "Wearing medium armor doesn't impose disadvantage on Stealth checks. Maximum DEX bonus to AC while wearing medium armor increases to +3.",
    benefits: ["No stealth penalty in medium armor", "+3 max DEX to AC in medium armor"],
    tags: ["armor", "dexterity", "stealth"],
  },
  {
    name: "Mobile",
    prerequisite: null,
    category: "Combat",
    description: "Speed increases by 10 feet. When you use the Dash action, difficult terrain doesn't cost extra movement for the rest of the turn. When you make a melee attack against a creature, you don't provoke opportunity attacks from that creature for the rest of the turn, whether you hit or not.",
    benefits: ["+10 ft speed", "Ignore difficult terrain on Dash", "No OA from attacked targets"],
    tags: ["mobility", "speed", "combat"],
  },
  {
    name: "Moderately Armored",
    prerequisite: "Light armor proficiency",
    category: "Armor",
    description: "+1 STR or DEX. Gain proficiency with medium armor and shields.",
    benefits: ["+1 STR or DEX", "Medium armor and shield proficiency"],
    tags: ["armor"],
    asi_choices: ["strength", "dexterity"],
  },
  {
    name: "Mounted Combatant",
    prerequisite: null,
    category: "Combat",
    description: "Advantage on melee attack rolls against unmounted creatures smaller than your mount. Force an attack targeting your mount to target you instead (reaction). If your mount is subjected to a DEX save for half damage, it takes no damage on a success and half on a failure.",
    benefits: ["Adv. attacks vs smaller unmounted creatures", "Redirect attacks to yourself", "Mount's DEX save improved"],
    tags: ["combat", "mounted", "cavalry"],
  },
  {
    name: "Observant",
    prerequisite: null,
    category: "Utility",
    description: "+1 INT or WIS. If you can see a creature's mouth while it is speaking a language you understand, you can interpret what it's saying by reading its lips. You have a +5 bonus to your passive Perception and passive Investigation scores.",
    benefits: ["+1 INT or WIS", "Lip reading", "+5 passive Perception & Investigation"],
    tags: ["perception", "intelligence", "wisdom", "utility"],
    asi_choices: ["intelligence", "wisdom"],
  },
  {
    name: "Polearm Master",
    prerequisite: null,
    category: "Combat",
    description: "When you take the Attack action with a glaive, halberd, pike, or quarterstaff, you can use a bonus action to make a melee attack with the opposite end of the weapon (1d4 bludgeoning). While wielding a glaive, halberd, pike, or quarterstaff, other creatures provoke opportunity attacks when they enter your reach.",
    benefits: ["Bonus butt-end attack (1d4)", "OA when enemies enter reach"],
    tags: ["combat", "polearm", "reach", "melee"],
  },
  {
    name: "Resilient",
    prerequisite: null,
    category: "General",
    description: "Choose one ability score. +1 to that ability score. Gain proficiency in saving throws using the chosen ability score.",
    benefits: ["+1 to chosen ability", "Saving throw proficiency in chosen ability"],
    tags: ["saving throw", "defense"],
    asi_choices: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
  },
  {
    name: "Ritual Caster",
    prerequisite: "INT or WIS 13+",
    category: "Magic",
    description: "You have learned a number of spells that you can cast as rituals. Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. Acquire a ritual book holding two 1st-level spells with the ritual tag from that class. If you find ritual spells of 1st or 2nd level, you can add them to your book. Intelligence or Wisdom is your spellcasting ability.",
    benefits: ["Ritual book with 2 ritual spells", "Can learn more ritual spells"],
    tags: ["magic", "ritual", "utility"],
    stat_req: { intelligence: 13, wisdom: 13, type: 'or' },
  },
  {
    name: "Savage Attacker",
    prerequisite: null,
    category: "Combat",
    description: "Once per turn when you roll damage for a melee weapon attack, you can reroll the weapon's damage dice and use either total.",
    benefits: ["Reroll melee weapon damage once per turn"],
    tags: ["combat", "melee", "damage"],
  },
  {
    name: "Sentinel",
    prerequisite: null,
    category: "Combat",
    description: "When you hit a creature with an OA, the creature's speed becomes 0 for the rest of the turn. Creatures within your reach provoke OA even if they took the Disengage action. When a creature makes an attack against a target other than you (and that target doesn't have this feat), you can use your reaction to make a melee weapon attack against the attacker.",
    benefits: ["OA reduces speed to 0", "Disengage doesn't prevent your OA", "React to protect allies"],
    tags: ["combat", "melee", "control", "reaction"],
  },
  {
    name: "Sharpshooter",
    prerequisite: null,
    category: "Combat",
    description: "Attacking at long range doesn't impose disadvantage. Ranged weapon attacks ignore half cover and three-quarters cover. Before making a ranged attack with a ranged weapon you are proficient with, you can take a -5 penalty to the roll. If the attack hits, you add +10 to the attack's damage.",
    benefits: ["No long range penalty", "Ignore half/3/4 cover", "-5 hit / +10 damage option"],
    tags: ["combat", "ranged", "damage"],
  },
  {
    name: "Shield Master",
    prerequisite: null,
    category: "Combat",
    description: "If you take the Attack action on your turn, you can use a bonus action to try to shove a creature within 5 feet. If you aren't incapacitated, you can add your shield's AC bonus to DEX saves against spells or other harmful effects that target only you. If you succeed on a DEX save for half damage, you take no damage instead.",
    benefits: ["Bonus shove after Attack", "+Shield to DEX saves", "Evasion-like vs DEX saves"],
    tags: ["combat", "defense", "shield"],
  },
  {
    name: "Skilled",
    prerequisite: null,
    category: "General",
    description: "Gain proficiency in any combination of three skills or tools of your choice.",
    benefits: ["3 skill or tool proficiencies"],
    tags: ["skills", "utility"],
  },
  {
    name: "Skulker",
    prerequisite: "DEX 13+",
    category: "Stealth",
    description: "You can try to hide when you are lightly obscured from the creature from which you are hiding. When you are hidden from a creature and miss it with a ranged weapon attack, making the attack doesn't reveal your position. Dim light doesn't impose disadvantage on your Perception checks relying on sight.",
    benefits: ["Hide in light obscurement", "Missed ranged attacks don't reveal you", "No dim light Perception penalty"],
    tags: ["stealth", "ranged", "dexterity"],
    stat_req: { dexterity: 13 },
  },
  {
    name: "Spell Sniper",
    prerequisite: "Spellcasting or Pact Magic",
    category: "Magic",
    description: "When you cast a spell that requires an attack roll, the spell's range doubles. Ranged spell attacks ignore half cover and three-quarters cover. Learn one cantrip that requires an attack roll from any class's spell list. INT, WIS, or CHA is your spellcasting ability.",
    benefits: ["Double range on attack spells", "Ignore cover with spell attacks", "1 attack cantrip"],
    tags: ["magic", "ranged", "damage"],
    caster_only: true,
  },
  {
    name: "Tavern Brawler",
    prerequisite: null,
    category: "Combat",
    description: "+1 STR or CON. Proficient with improvised weapons. Unarmed strike uses d4 for damage. When you hit with an unarmed strike or improvised weapon, you can use a bonus action to attempt a grapple.",
    benefits: ["+1 STR or CON", "Improvised weapon proficiency", "d4 unarmed damage", "Bonus grapple on hit"],
    tags: ["combat", "melee", "unarmed"],
    asi_choices: ["strength", "constitution"],
  },
  {
    name: "Tough",
    prerequisite: null,
    category: "Survival",
    description: "Your HP maximum increases by an amount equal to twice your current level when you gain this feat. Whenever you gain a level thereafter, your HP maximum increases by an additional 2.",
    benefits: ["+2 HP per level (retroactive and ongoing)"],
    tags: ["hp", "survival", "defense"],
  },
  {
    name: "War Caster",
    prerequisite: "Spellcasting or Pact Magic",
    category: "Magic",
    description: "Advantage on Constitution saving throws to maintain concentration. You can perform the somatic components of spells even when you have weapons or a shield in one or both hands. When a hostile creature's movement provokes an OA from you, you can use your reaction to cast a spell at the creature, rather than making an OA.",
    benefits: ["Adv. on concentration saves", "Cast with weapons in hand", "Cast spell as OA"],
    tags: ["magic", "concentration", "reaction"],
    caster_only: true,
  },
  {
    name: "Weapon Master",
    prerequisite: null,
    category: "Combat",
    description: "+1 STR or DEX. Gain proficiency with four weapons of your choice.",
    benefits: ["+1 STR or DEX", "4 weapon proficiencies"],
    tags: ["combat", "weapons"],
    asi_choices: ["strength", "dexterity"],
  },
  // Xanathar's Guide feats
  {
    name: "Bountiful Luck",
    prerequisite: "Halfling",
    category: "Racial",
    description: "When an ally you can see within 30 feet of you rolls a 1 on a d20, you can use your reaction to let the ally reroll. The ally must use the new roll.",
    benefits: ["Reaction: let nearby ally reroll a 1"],
    tags: ["luck", "support", "racial"],
    race_req: ["Halfling"],
  },
  {
    name: "Dragon Fear",
    prerequisite: "Dragonborn",
    category: "Racial",
    description: "+1 STR, CON, or CHA. Instead of exhaling destructive energy, you can frighten creatures. Each creature within 30 feet must succeed on a Wisdom saving throw (DC 8 + proficiency + CHA modifier) or be frightened for 1 minute.",
    benefits: ["+1 STR, CON, or CHA", "Breath weapon becomes fear aura"],
    tags: ["racial", "dragonborn", "fear"],
    race_req: ["Dragonborn"],
    asi_choices: ["strength", "constitution", "charisma"],
  },
  {
    name: "Dragon Hide",
    prerequisite: "Dragonborn",
    category: "Racial",
    description: "+1 STR, CON, or CHA. You manifest scales and claws resembling those of your draconic ancestor. Your scales are natural armor (AC 13 + DEX). Your unarmed strikes deal 1d4 slashing damage.",
    benefits: ["+1 STR, CON, or CHA", "Natural AC 13+DEX", "1d4 claw attacks"],
    tags: ["racial", "dragonborn", "armor"],
    race_req: ["Dragonborn"],
    asi_choices: ["strength", "constitution", "charisma"],
  },
  {
    name: "Drow High Magic",
    prerequisite: "Elf (drow)",
    category: "Racial",
    description: "Learn the Detect Magic spell and can cast it at will. Learn Levitate and Dispel Magic, each castable once per long rest without a spell slot. CHA is spellcasting ability for all three.",
    benefits: ["Detect Magic at will", "Levitate 1/LR", "Dispel Magic 1/LR"],
    tags: ["racial", "elf", "magic"],
    race_req: ["Elf"],
  },
  {
    name: "Elven Accuracy",
    prerequisite: "Elf or Half-Elf",
    category: "Racial",
    description: "+1 DEX, INT, WIS, or CHA. When you have advantage on an attack roll using DEX, INT, WIS, or CHA, you can reroll one of the dice once.",
    benefits: ["+1 DEX/INT/WIS/CHA", "Triple advantage reroll on qualifying attacks"],
    tags: ["racial", "elf", "accuracy"],
    race_req: ["Elf", "Half-Elf"],
    asi_choices: ["dexterity", "intelligence", "wisdom", "charisma"],
  },
  {
    name: "Fade Away",
    prerequisite: "Gnome",
    category: "Racial",
    description: "+1 DEX or INT. When you take damage, you can use your reaction to become invisible until the start of your next turn (or until you attack, deal damage, or force a saving throw). 1/Short or Long Rest.",
    benefits: ["+1 DEX or INT", "Reaction: become invisible when damaged (1/SR)"],
    tags: ["racial", "gnome", "stealth"],
    race_req: ["Gnome"],
    asi_choices: ["dexterity", "intelligence"],
  },
  {
    name: "Fey Teleportation",
    prerequisite: "Elf (high elf)",
    category: "Racial",
    description: "+1 INT or CHA. Learn Sylvan. Once per short rest, cast Misty Step without expending a spell slot. INT or CHA is spellcasting ability.",
    benefits: ["+1 INT or CHA", "Learn Sylvan", "Misty Step 1/SR"],
    tags: ["racial", "elf", "teleportation"],
    race_req: ["Elf"],
    asi_choices: ["intelligence", "charisma"],
  },
  {
    name: "Flames of Phlegethos",
    prerequisite: "Tiefling",
    category: "Racial",
    description: "+1 INT or CHA. When you roll fire damage for a spell, reroll any 1s and use the new roll. When you cast a fire damage spell, wreathing flames surround you until end of next turn, dealing 1d4 fire damage to creatures within 5 feet that hit you with a melee attack.",
    benefits: ["+1 INT or CHA", "Reroll 1s on fire damage", "Flame aura on fire spells"],
    tags: ["racial", "tiefling", "fire", "magic"],
    race_req: ["Tiefling"],
    asi_choices: ["intelligence", "charisma"],
  },
  {
    name: "Infernal Constitution",
    prerequisite: "Tiefling",
    category: "Racial",
    description: "+1 CON. Resistance to cold and poison damage. Advantage on saving throws against being poisoned.",
    benefits: ["+1 CON", "Cold and poison resistance", "Adv. vs poison saves"],
    tags: ["racial", "tiefling", "defense"],
    race_req: ["Tiefling"],
    asi_bonus: { constitution: 1 },
  },
  {
    name: "Orcish Fury",
    prerequisite: "Half-Orc",
    category: "Racial",
    description: "+1 STR or CON. Once per short rest, add one weapon damage die to a weapon attack. When you use Relentless Endurance, you can use your reaction to make one weapon attack.",
    benefits: ["+1 STR or CON", "Extra damage die 1/SR", "Counterattack after Relentless Endurance"],
    tags: ["racial", "half-orc", "combat"],
    race_req: ["Half-Orc"],
    asi_choices: ["strength", "constitution"],
  },
  {
    name: "Prodigy",
    prerequisite: "Half-Elf, Half-Orc, or Human",
    category: "Racial",
    description: "Gain one skill proficiency, one tool proficiency, and one language. Gain expertise in one skill proficiency you already have.",
    benefits: ["1 skill proficiency", "1 tool proficiency", "1 language", "Expertise in 1 skill"],
    tags: ["racial", "skills", "utility"],
    race_req: ["Human", "Half-Elf", "Half-Orc"],
  },
  {
    name: "Second Chance",
    prerequisite: "Halfling",
    category: "Racial",
    description: "+1 DEX, CON, or CHA. When a creature hits you with an attack, you can use your reaction to force that creature to reroll. Once used, you must finish a short or long rest to use it again.",
    benefits: ["+1 DEX/CON/CHA", "Reaction: force attack reroll (1/SR)"],
    tags: ["racial", "halfling", "defense"],
    race_req: ["Halfling"],
    asi_choices: ["dexterity", "constitution", "charisma"],
  },
  {
    name: "Squat Nimbleness",
    prerequisite: "Dwarf or small race",
    category: "Racial",
    description: "+1 STR or DEX. Speed increases by 5 feet. Proficiency in Acrobatics or Athletics (your choice). Advantage on checks to escape a grapple.",
    benefits: ["+1 STR or DEX", "+5 speed", "Acrobatics or Athletics proficiency"],
    tags: ["racial", "dwarf", "mobility"],
    race_req: ["Dwarf", "Halfling", "Gnome"],
    asi_choices: ["strength", "dexterity"],
  },
  {
    name: "Wood Elf Magic",
    prerequisite: "Elf (wood elf)",
    category: "Racial",
    description: "Learn the Druidcraft cantrip. Learn Longstrider and Pass without Trace, each castable once per long rest without a spell slot. WIS is spellcasting ability.",
    benefits: ["Druidcraft cantrip", "Longstrider 1/LR", "Pass Without Trace 1/LR"],
    tags: ["racial", "elf", "magic"],
    race_req: ["Elf"],
  },
];

export const FEAT_CATEGORIES = ["General", "Combat", "Magic", "Armor", "Support", "Utility", "Exploration", "Survival", "Social", "Stealth", "Racial"];

export const CATEGORY_COLORS = {
  General: "text-slate-300 bg-slate-700/40 border-slate-600/40",
  Combat: "text-red-300 bg-red-900/20 border-red-700/30",
  Magic: "text-purple-300 bg-purple-900/20 border-purple-700/30",
  Armor: "text-blue-300 bg-blue-900/20 border-blue-700/30",
  Support: "text-green-300 bg-green-900/20 border-green-700/30",
  Utility: "text-amber-300 bg-amber-900/20 border-amber-700/30",
  Exploration: "text-teal-300 bg-teal-900/20 border-teal-700/30",
  Survival: "text-orange-300 bg-orange-900/20 border-orange-700/30",
  Social: "text-pink-300 bg-pink-900/20 border-pink-700/30",
  Stealth: "text-indigo-300 bg-indigo-900/20 border-indigo-700/30",
  Racial: "text-yellow-300 bg-yellow-900/20 border-yellow-700/30",
};

// Check if character meets prerequisite for a feat
export function meetsPrerequisite(feat, character) {
  if (!feat.stat_req) return true;
  if (feat.stat_req.type === 'or') {
    return Object.entries(feat.stat_req)
      .filter(([k]) => k !== 'type')
      .some(([stat, min]) => (character[stat] || 10) >= min);
  }
  return Object.entries(feat.stat_req)
    .filter(([k]) => k !== 'type')
    .every(([stat, min]) => (character[stat] || 10) >= min);
}

// Check if character's race meets racial requirement
export function meetsRaceReq(feat, character) {
  if (!feat.race_req) return true;
  return feat.race_req.includes(character.race);
}

// Check if character can take a feat (caster-only)
export function meetsCasterReq(feat, character) {
  const CASTERS = ['Wizard','Sorcerer','Warlock','Bard','Cleric','Druid','Paladin','Ranger'];
  if (!feat.caster_only) return true;
  return CASTERS.includes(character.class);
}

export function canTakeFeat(feat, character) {
  return meetsPrerequisite(feat, character) && meetsRaceReq(feat, character) && meetsCasterReq(feat, character);
}