// ═══════════════════════════════════════════════════════════════════════════════
// Pathfinder 2nd Edition (Remaster) — Core Game Data
// Covers: Ancestries, Classes, Skills, Feats, Spell Traditions, Backgrounds
// ═══════════════════════════════════════════════════════════════════════════════

// ─── PF2E Ancestries (equivalent of D&D Races) ──────────────────────────────
export const PF2E_ANCESTRIES = {
  Human: {
    hp: 8, size: 'Medium', speed: 25,
    stat_boosts: ['Two free boosts'],
    languages: ['Common', 'one additional'],
    traits: ['Adaptable', 'Ambitious'],
    description: 'Ambitious, versatile, and numerous. Humans receive two free ability boosts and an extra general feat at 1st level.',
    heritages: [
      { name: 'Skilled Heritage', traits: ['Trained in one additional skill, becomes expert at 5th level'] },
      { name: 'Versatile Heritage', traits: ['Gain a general feat of your choice'] },
      { name: 'Wintertouched', traits: ['Cold resistance equal to half your level'] },
      { name: 'Half-Elf', traits: ['Low-light vision', 'Access to elf and half-elf ancestry feats'] },
      { name: 'Half-Orc', traits: ['Low-light vision', 'Access to orc and half-orc ancestry feats'] },
    ],
  },
  Elf: {
    hp: 6, size: 'Medium', speed: 30,
    stat_boosts: ['Dexterity', 'Intelligence', 'Free'],
    stat_flaws: ['Constitution'],
    languages: ['Common', 'Elven'],
    traits: ['Low-Light Vision'],
    description: 'Elves are long-lived and deeply connected to nature and magic. They are lithe, quick, and perceptive.',
    heritages: [
      { name: 'Arctic Elf', traits: ['Cold resistance equal to half your level'] },
      { name: 'Cavern Elf', traits: ['Darkvision instead of low-light vision'] },
      { name: 'Seer Elf', traits: ['Detect Magic as an innate cantrip'] },
      { name: 'Whisper Elf', traits: ['Seek action gains a +2 circumstance bonus'] },
      { name: 'Woodland Elf', traits: ['Climb Speed 10, or ignore difficult terrain from undergrowth'] },
    ],
  },
  Dwarf: {
    hp: 10, size: 'Medium', speed: 20,
    stat_boosts: ['Constitution', 'Wisdom', 'Free'],
    stat_flaws: ['Charisma'],
    languages: ['Common', 'Dwarven'],
    traits: ['Darkvision', 'Clan Dagger'],
    description: 'Stout and resilient, dwarves are master craftsmen and fierce warriors. Their hardy nature gives them the highest ancestry HP.',
    heritages: [
      { name: 'Ancient-Blooded Dwarf', traits: ['Reaction: +1 circumstance bonus to saves vs magic'] },
      { name: 'Death Warden Dwarf', traits: ['Saving throw bonus vs necromancy, resist negative damage'] },
      { name: 'Forge Dwarf', traits: ['Fire resistance equal to half your level'] },
      { name: 'Rock Dwarf', traits: ['+2 vs Shove/Trip, +2 to Reflex vs being knocked prone'] },
      { name: 'Strong-Blooded Dwarf', traits: ['Poison resistance, +2 to saves vs poison'] },
    ],
  },
  Gnome: {
    hp: 8, size: 'Small', speed: 25,
    stat_boosts: ['Constitution', 'Charisma', 'Free'],
    stat_flaws: ['Strength'],
    languages: ['Common', 'Gnomish', 'Sylvan'],
    traits: ['Low-Light Vision'],
    description: 'Fey-touched and endlessly curious, gnomes bring wild creativity and boundless energy to everything they do.',
    heritages: [
      { name: 'Chameleon Gnome', traits: ['Change hair/eye color; gain a camouflage bonus to Stealth'] },
      { name: 'Fey-Touched Gnome', traits: ['Gain a primal cantrip'] },
      { name: 'Sensate Gnome', traits: ['Gain an occult cantrip (Detect Magic or similar)'] },
      { name: 'Umbral Gnome', traits: ['Darkvision instead of low-light vision'] },
      { name: 'Wellspring Gnome', traits: ['Gain a cantrip from any tradition'] },
    ],
  },
  Halfling: {
    hp: 6, size: 'Small', speed: 25,
    stat_boosts: ['Dexterity', 'Wisdom', 'Free'],
    stat_flaws: ['Strength'],
    languages: ['Common', 'Halfling'],
    traits: ['Keen Eyes (lower penalty to seek concealed creatures)'],
    description: 'Halflings are optimistic, cheerful wanderers with an uncanny ability to avoid danger through pure luck.',
    heritages: [
      { name: 'Gutsy Halfling', traits: ['+1 circumstance bonus to saves vs emotion effects, treat crit failures as failures'] },
      { name: 'Hillock Halfling', traits: ['Regain +level extra HP when resting, +Treat Wounds bonus'] },
      { name: 'Nomadic Halfling', traits: ['Extra language per level, Assurance (Survival)'] },
      { name: 'Twilight Halfling', traits: ['Low-light vision'] },
      { name: 'Wildwood Halfling', traits: ['Ignore difficult terrain from plants, treat undergrowth as cover'] },
    ],
  },
  Goblin: {
    hp: 6, size: 'Small', speed: 25,
    stat_boosts: ['Dexterity', 'Charisma', 'Free'],
    stat_flaws: ['Wisdom'],
    languages: ['Common', 'Goblin'],
    traits: ['Darkvision'],
    description: 'Chaotic and inventive, goblins love fire, singing, and finding creative (if dangerous) solutions to problems.',
    heritages: [
      { name: 'Charhide Goblin', traits: ['Fire resistance equal to half your level, +2 to save vs catching fire'] },
      { name: 'Irongut Goblin', traits: ['Eat spoiled food safely, +2 to saves vs diseases/poison from food'] },
      { name: 'Razortooth Goblin', traits: ['Jaws unarmed attack: 1d6 piercing'] },
      { name: 'Snow Goblin', traits: ['Cold resistance, ignore difficult terrain from ice/snow'] },
      { name: 'Unbreakable Goblin', traits: ['+4 HP from ancestry instead of 6, reduce fall damage by half'] },
    ],
  },
  Leshy: {
    hp: 8, size: 'Small', speed: 25,
    stat_boosts: ['Constitution', 'Wisdom', 'Free'],
    stat_flaws: ['Intelligence'],
    languages: ['Common', 'Sylvan'],
    traits: ['Low-Light Vision', 'Plant Nourishment (photosynthesis instead of eating)'],
    description: 'Sentient plant creatures animated by nature spirits. Each leshy has a unique botanical appearance.',
    heritages: [
      { name: 'Fungus Leshy', traits: ['Darkvision, can survive in low-light or dark environments'] },
      { name: 'Gourd Leshy', traits: ['Store items inside your body cavity'] },
      { name: 'Leaf Leshy', traits: ['Gentle Landing (fall safely from any height)'] },
      { name: 'Vine Leshy', traits: ['Reach trait on unarmed attacks'] },
    ],
  },
  Orc: {
    hp: 10, size: 'Medium', speed: 25,
    stat_boosts: ['Strength', 'Free'],
    languages: ['Common', 'Orcish'],
    traits: ['Darkvision'],
    description: 'Powerful and proud, orcs are fierce warriors with a deeply communal culture built on strength and honor.',
    heritages: [
      { name: 'Badlands Orc', traits: ['Environmental heat resistance, reduced water needs'] },
      { name: 'Deep Orc', traits: ['Darkvision extended range, climb speed 10'] },
      { name: 'Hold-Scarred Orc', traits: ['Fast healing 1 during encounters'] },
      { name: 'Rainfall Orc', traits: ['Ignore difficult terrain from rain/mud, swim speed 10'] },
    ],
  },
  Kobold: {
    hp: 6, size: 'Small', speed: 25,
    stat_boosts: ['Dexterity', 'Charisma', 'Free'],
    stat_flaws: ['Constitution'],
    languages: ['Common', 'Draconic'],
    traits: ['Darkvision', 'Draconic Exemplar (choose a dragon type)'],
    description: 'Small draconic humanoids who claim kinship with true dragons. Clever trapmakers and surprisingly fierce defenders.',
    heritages: [
      { name: 'Caveclimber Kobold', traits: ['Climb speed 10'] },
      { name: 'Dragonscaled Kobold', traits: ['Resistance to your exemplar dragon damage type'] },
      { name: 'Strongjaw Kobold', traits: ['Jaws unarmed attack: 1d6 piercing'] },
      { name: 'Venomtail Kobold', traits: ['Tail attack with poison damage'] },
    ],
  },
  Catfolk: {
    hp: 8, size: 'Medium', speed: 25,
    stat_boosts: ['Dexterity', 'Charisma', 'Free'],
    stat_flaws: ['Wisdom'],
    languages: ['Common', 'Amurrun'],
    traits: ['Low-Light Vision', 'Land on Your Feet (reduce fall damage)'],
    description: 'Curious, agile, and fiercely independent feline humanoids driven by wanderlust and a love of stories.',
    heritages: [
      { name: 'Clawed Catfolk', traits: ['Claw unarmed attack: 1d6 slashing'] },
      { name: 'Hunting Catfolk', traits: ['Move speed increases to 30'] },
      { name: 'Jungle Catfolk', traits: ['Climb speed 10'] },
      { name: 'Nine Lives Catfolk', traits: ['Once per day, avoid a killing blow'] },
    ],
  },
  Tengu: {
    hp: 6, size: 'Medium', speed: 25,
    stat_boosts: ['Dexterity', 'Free'],
    languages: ['Common', 'Tengu'],
    traits: ['Low-Light Vision', 'Sharp Beak (1d6 piercing unarmed)'],
    description: 'Avian humanoids with sharp minds and sharper beaks. Known as collectors of stories, shiny objects, and secrets.',
    heritages: [
      { name: 'Dogtooth Tengu', traits: ['Beak attack gets versatile slashing'] },
      { name: 'Skyborn Tengu', traits: ['Feather Fall innate ability'] },
      { name: 'Stormtossed Tengu', traits: ['Electricity resistance equal to half level'] },
      { name: 'Taloned Tengu', traits: ['Talon unarmed attack: 1d4 slashing, agile'] },
    ],
  },
};

// ─── PF2E Classes ────────────────────────────────────────────────────────────
export const PF2E_CLASSES = {
  Fighter: {
    hp: 10, key_ability: ['Strength', 'Dexterity'],
    perception: 'Expert', fortitude: 'Expert', reflex: 'Expert', will: 'Trained',
    skills: 3,
    armor: ['Light', 'Medium', 'Heavy', 'Shields'],
    weapons: ['Simple', 'Martial', 'Advanced (in weapon group)'],
    description: 'Masters of weaponry who excel at martial combat. Fighters gain proficiency faster than any class.',
    features: {
      1: ['Attack of Opportunity', 'Shield Block (reaction)', 'Fighter Feat'],
      2: ['Fighter Feat', 'Skill Feat'],
      3: ['Bravery (expert Will vs fear)', 'General Feat'],
      5: ['Fighter Weapon Mastery', 'Ancestry Feat'],
      9: ['Combat Flexibility', 'Juggernaut'],
      13: ['Weapon Legend'],
      19: ['Versatile Legend'],
    },
    subclasses: [],
  },
  Rogue: {
    hp: 8, key_ability: ['Dexterity'],
    perception: 'Expert', fortitude: 'Trained', reflex: 'Expert', will: 'Expert',
    skills: 7,
    armor: ['Light'],
    weapons: ['Simple', 'Rapier', 'Sap', 'Shortbow', 'Shortsword'],
    description: 'Skilled specialists who exploit weaknesses. Choose a Racket to define your style.',
    features: {
      1: ['Sneak Attack 1d6', "Rogue's Racket", 'Surprise Attack', 'Rogue Feat'],
      2: ['Rogue Feat', 'Skill Feat'],
      3: ['Deny Advantage'],
      5: ['Sneak Attack 2d6', 'Weapon Tricks'],
      7: ['Evasion', 'Vigilant Senses'],
      9: ['Debilitating Strikes', 'Great Fortitude'],
      13: ['Improved Evasion', 'Incredible Senses', 'Sneak Attack 4d6'],
    },
    subclasses: [
      { name: 'Thief', desc: 'Use Dexterity for damage with finesse weapons. Agile and quick.' },
      { name: 'Ruffian', desc: 'Use medium armor, deal Sneak Attack with d8 weapons. Tough and brutal.' },
      { name: 'Scoundrel', desc: 'Feint to flat-foot enemies. Charismatic tricksters.' },
      { name: 'Eldritch Trickster', desc: 'Gain spellcasting through a multiclass dedication. Magic meets stealth.' },
    ],
  },
  Wizard: {
    hp: 6, key_ability: ['Intelligence'],
    perception: 'Trained', fortitude: 'Trained', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Unarmored'],
    weapons: ['Club', 'Crossbow', 'Dagger', 'Heavy Crossbow', 'Staff'],
    description: 'Scholarly arcane spellcasters who study magic through rigorous research and spell preparation.',
    features: {
      1: ['Arcane Spellcasting', 'Arcane School', 'Arcane Bond', 'Wizard Feat'],
      2: ['Wizard Feat', 'Skill Feat'],
      5: ['Lightning Reflexes'],
      7: ['Expert Spellcaster'],
      9: ['Magical Fortitude'],
      11: ['Alertness'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster'],
    },
    subclasses: [
      { name: 'School of Ars Grammatica', desc: 'Focus on the fundamental grammar of magic itself.' },
      { name: 'School of Battle Magic', desc: 'Specialize in combat-oriented evocation and destruction.' },
      { name: 'School of Civic Wizardry', desc: 'Enchantment and social magic for governance and diplomacy.' },
      { name: 'School of Mentalism', desc: 'Divination and mind-affecting magic.' },
      { name: 'School of Protean Form', desc: 'Transmutation and shapeshifting magic.' },
      { name: 'School of the Boundary', desc: 'Abjuration and protective magic.' },
    ],
  },
  Cleric: {
    hp: 8, key_ability: ['Wisdom'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Unarmored', 'Light', 'Medium (warpriest)'],
    weapons: ["Deity's favored weapon", 'Simple'],
    description: 'Divine spellcasters who channel the power of their deity. Choose Cloistered Cleric or Warpriest.',
    features: {
      1: ['Divine Spellcasting', 'Divine Font (Heal/Harm)', 'Doctrine', 'Cleric Feat'],
      2: ['Cleric Feat', 'Skill Feat'],
      3: ['Second Doctrine'],
      5: ['Alertness'],
      9: ['Resolve'],
      11: ['Lightning Reflexes'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster'],
    },
    subclasses: [
      { name: 'Cloistered Cleric', desc: 'Focus on spellcasting. Expert in divine spell DCs.' },
      { name: 'Warpriest', desc: 'Martial cleric with medium armor and shield proficiency.' },
    ],
  },
  Ranger: {
    hp: 10, key_ability: ['Strength', 'Dexterity'],
    perception: 'Expert', fortitude: 'Expert', reflex: 'Expert', will: 'Trained',
    skills: 4,
    armor: ['Light', 'Medium'],
    weapons: ['Simple', 'Martial'],
    description: 'Expert hunters and trackers who specialize in fighting specific prey. Masters of the wilds.',
    features: {
      1: ["Hunt Prey", "Hunter's Edge", 'Ranger Feat'],
      2: ['Ranger Feat', 'Skill Feat'],
      3: ['Iron Will'],
      5: ['Trackless Step', 'Weapon Expertise'],
      7: ['Evasion'],
      9: ["Nature's Edge"],
      11: ['Wild Stride'],
      15: ['Improved Evasion'],
      19: ['Masterful Hunter'],
    },
    subclasses: [
      { name: 'Flurry', desc: 'Reduced penalty for multiple attacks against hunted prey.' },
      { name: 'Outwit', desc: 'Bonus to Deception, Intimidation, Stealth vs hunted prey.' },
      { name: 'Precision', desc: 'Extra damage on first hit each round against hunted prey.' },
    ],
  },
  Champion: {
    hp: 10, key_ability: ['Strength', 'Dexterity'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Light', 'Medium', 'Heavy', 'Shields'],
    weapons: ['Simple', 'Martial'],
    description: 'Holy warriors devoted to a deity. Choose a cause that defines your champion reaction.',
    features: {
      1: ['Champion Cause', "Deity and Cause", "Champion's Reaction", 'Champion Feat'],
      2: ['Champion Feat', 'Skill Feat'],
      3: ['Divine Ally (Blade, Shield, or Steed)'],
      5: ['Weapon Expertise'],
      7: ['Armor Expertise'],
      9: ['Champion Expertise', 'Divine Smite'],
      11: ['Shield Paragon'],
      15: ['Armor Mastery'],
    },
    subclasses: [
      { name: 'Paladin (LG)', desc: 'Retributive Strike — reduce damage an ally takes and Strike the enemy.' },
      { name: 'Redeemer (NG)', desc: "Glimpse of Redemption — enforce enemy's choice: take penalty or grant resistance." },
      { name: 'Liberator (CG)', desc: 'Liberating Step — free ally from restraints and grant a Step.' },
      { name: 'Tyrant (LE)', desc: 'Iron Command — enemy must kneel or take damage.' },
      { name: 'Desecrator (NE)', desc: 'Selfish Shield — gain resistance when an ally is hit.' },
      { name: 'Antipaladin (CE)', desc: 'Destructive Vengeance — deal persistent evil damage when hit.' },
    ],
  },
  Barbarian: {
    hp: 12, key_ability: ['Strength'],
    perception: 'Expert', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 3,
    armor: ['Light', 'Medium'],
    weapons: ['Simple', 'Martial'],
    description: 'Fierce warriors who channel primal fury. Choose an Instinct that shapes your rage.',
    features: {
      1: ['Rage (+2 damage, temp HP, restrictions)', 'Instinct', 'Barbarian Feat'],
      3: ['Deny Advantage'],
      5: ['Brutality'],
      7: ['Juggernaut (Fortitude master)'],
      9: ['Raging Resistance'],
      11: ['Mighty Rage (free action rage)'],
      13: ['Greater Juggernaut'],
      15: ['Indomitable Will'],
      17: ['Heightened Senses'],
    },
    subclasses: [
      { name: 'Animal Instinct', desc: 'Gain a unique unarmed attack from a bestial form.' },
      { name: 'Dragon Instinct', desc: 'Breath weapon and draconic rage damage.' },
      { name: 'Fury Instinct', desc: 'Pure rage — extra damage, no restrictions on armor.' },
      { name: 'Giant Instinct', desc: 'Wield oversized weapons for massive damage.' },
      { name: 'Spirit Instinct', desc: 'Channel positive/negative energy while raging.' },
      { name: 'Superstition Instinct', desc: 'Bonus vs magic, penalty to benefit from magic.' },
    ],
  },
  Bard: {
    hp: 8, key_ability: ['Charisma'],
    perception: 'Expert', fortitude: 'Trained', reflex: 'Trained', will: 'Expert',
    skills: 4,
    armor: ['Light'],
    weapons: ['Simple', 'Longsword', 'Rapier', 'Sap', 'Shortbow', 'Shortsword', 'Whip'],
    description: 'Occult spellcasters who blend art and magic. Muses shape their creative expression.',
    features: {
      1: ['Occult Spellcasting', 'Composition Cantrips (Inspire Courage)', 'Muse', 'Bard Feat'],
      2: ['Bard Feat', 'Skill Feat'],
      3: ['Lightning Reflexes', 'Signature Spells'],
      7: ['Expert Spellcaster'],
      9: ['Great Fortitude', 'Resolve'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster'],
    },
    subclasses: [
      { name: 'Enigma', desc: 'Focus on knowledge and lore. Gain Bardic Lore and True Strike.' },
      { name: 'Maestro', desc: 'Focus on compositions and performance. Lingering Composition.' },
      { name: 'Polymath', desc: 'Versatile and adaptable. Swap spells daily.' },
      { name: 'Warrior', desc: 'Combat-oriented bard with martial training.' },
    ],
  },
  Druid: {
    hp: 8, key_ability: ['Wisdom'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Light', 'Medium (non-metal)', 'Shields (non-metal)'],
    weapons: ['Simple'],
    description: 'Primal spellcasters who draw power from the natural world. Druidic Orders shape their connection.',
    features: {
      1: ['Primal Spellcasting', 'Druidic Order', 'Druidic Language', 'Wild Empathy', 'Druid Feat'],
      2: ['Druid Feat', 'Skill Feat'],
      3: ['Alertness', 'Great Fortitude'],
      5: ['Lightning Reflexes'],
      7: ['Expert Spellcaster'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster'],
    },
    subclasses: [
      { name: 'Animal Order', desc: 'Gain an animal companion and Order Explorer feats.' },
      { name: 'Leaf Order', desc: 'Focus on plants and healing. Gain Goodberry.' },
      { name: 'Storm Order', desc: 'Destructive elemental power. Gain Tempest Surge.' },
      { name: 'Wild Order', desc: 'Shapeshifting focus. Gain Wild Shape form spells.' },
    ],
  },
  Monk: {
    hp: 10, key_ability: ['Strength', 'Dexterity'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Expert', will: 'Expert',
    skills: 4,
    armor: ['Unarmored (expert)'],
    weapons: ['Simple', 'Unarmed'],
    description: 'Masters of unarmed combat who channel ki for extraordinary martial techniques.',
    features: {
      1: ['Flurry of Blows', 'Powerful Fist (1d6 unarmed)', 'Monk Feat'],
      3: ['Incredible Movement (+10 speed)', 'Mystic Strikes'],
      5: ['Alertness', 'Expert Strikes'],
      7: ['Path to Perfection (master one save)'],
      9: ['Metal Strikes'],
      11: ['Second Path to Perfection'],
      13: ['Graceful Mastery'],
      15: ['Third Path to Perfection'],
      17: ['Adamantine Strikes'],
    },
    subclasses: [],
  },
  Sorcerer: {
    hp: 6, key_ability: ['Charisma'],
    perception: 'Trained', fortitude: 'Trained', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Unarmored'],
    weapons: ['Simple'],
    description: 'Spontaneous spellcasters whose innate bloodline grants them magical power.',
    features: {
      1: ['Bloodline (determines spell tradition)', 'Bloodline Spells', 'Sorcerer Feat'],
      2: ['Sorcerer Feat', 'Skill Feat'],
      3: ['Signature Spells'],
      5: ['Magical Fortitude'],
      7: ['Expert Spellcaster'],
      9: ['Lightning Reflexes'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster', 'Bloodline Paragon'],
    },
    subclasses: [
      { name: 'Aberrant', desc: 'Occult tradition. Tentacles and alien power.' },
      { name: 'Angelic', desc: 'Divine tradition. Celestial healing and light.' },
      { name: 'Demonic', desc: 'Divine tradition. Destructive chaos and fire.' },
      { name: 'Draconic', desc: 'Arcane tradition. Dragon breath and scales.' },
      { name: 'Fey', desc: 'Primal tradition. Illusions and nature magic.' },
      { name: 'Imperial', desc: 'Arcane tradition. Command and mental domination.' },
      { name: 'Undead', desc: 'Divine tradition. Necromancy and life drain.' },
    ],
  },
  Alchemist: {
    hp: 8, key_ability: ['Intelligence'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Expert', will: 'Trained',
    skills: 3,
    armor: ['Light', 'Medium'],
    weapons: ['Simple', 'Alchemical Bombs'],
    description: 'Crafters of elixirs, bombs, and mutagens using scientific formulas rather than magic.',
    features: {
      1: ['Alchemy', 'Research Field', 'Formula Book', 'Alchemist Feat'],
      5: ['Field Discovery'],
      7: ['Alchemical Weapon Expertise'],
      9: ['Alertness', 'Double Brew'],
      11: ['Juggernaut'],
      13: ['Greater Field Discovery'],
    },
    subclasses: [
      { name: 'Bomber', desc: 'Specialize in alchemical bombs. Extra splash damage.' },
      { name: 'Chirurgeon', desc: 'Focus on healing elixirs. Use Crafting for Treat Wounds.' },
      { name: 'Mutagenist', desc: 'Create mutagens that enhance your body.' },
      { name: 'Toxicologist', desc: 'Master of poisons. Apply poisons efficiently.' },
    ],
  },
  Witch: {
    hp: 6, key_ability: ['Intelligence'],
    perception: 'Trained', fortitude: 'Trained', reflex: 'Trained', will: 'Expert',
    skills: 3,
    armor: ['Unarmored'],
    weapons: ['Simple'],
    description: 'Spellcasters who gain power through a pact with a mysterious patron. A familiar serves as their spellbook.',
    features: {
      1: ['Patron and Familiar', 'Hexes (Hex Cantrips)', 'Witch Feat', 'Spellcasting'],
      2: ['Witch Feat', 'Skill Feat'],
      7: ['Expert Spellcaster'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster'],
    },
    subclasses: [
      { name: 'Fervor (Divine)', desc: 'Patron grants divine tradition spells.' },
      { name: 'Fate (Occult)', desc: 'Patron grants occult tradition spells.' },
      { name: 'Night (Occult)', desc: 'Patron grants darkness and shadow magic.' },
      { name: 'Wild (Primal)', desc: 'Patron grants primal tradition spells.' },
      { name: 'Resentment (Occult)', desc: 'Patron grants grudge-based hex magic.' },
    ],
  },
  Oracle: {
    hp: 8, key_ability: ['Charisma'],
    perception: 'Trained', fortitude: 'Trained', reflex: 'Trained', will: 'Expert',
    skills: 3,
    armor: ['Unarmored'],
    weapons: ['Simple'],
    description: 'Divine spellcasters cursed with powerful mysteries. Greater power comes at the cost of deepening their curse.',
    features: {
      1: ['Divine Spellcasting', 'Mystery and Curse', 'Revelation Spells', 'Oracle Feat'],
      7: ['Expert Spellcaster'],
      11: ['Major Curse (greater power, greater penalty)'],
      15: ['Master Spellcaster'],
      19: ['Legendary Spellcaster', 'Extreme Curse'],
    },
    subclasses: [
      { name: 'Ancestors', desc: 'Spirits of the dead guide you. Curse: confusion from conflicting advice.' },
      { name: 'Battle', desc: 'War and combat. Curse: increasing recklessness.' },
      { name: 'Bones', desc: 'Death and undeath. Curse: appearance becomes deathlike.' },
      { name: 'Cosmos', desc: 'Stars and space. Curse: burning starlight and gravity shifts.' },
      { name: 'Flames', desc: 'Fire and destruction. Curse: surrounded by searing heat.' },
      { name: 'Life', desc: 'Healing and vitality. Curse: healing yourself becomes harder.' },
      { name: 'Tempest', desc: 'Storms and lightning. Curse: uncontrollable winds.' },
    ],
  },
  Swashbuckler: {
    hp: 10, key_ability: ['Dexterity'],
    perception: 'Expert', fortitude: 'Trained', reflex: 'Expert', will: 'Expert',
    skills: 5,
    armor: ['Light'],
    weapons: ['Simple', 'Martial'],
    description: 'Daring combatants who gain Panache through style and flair, then spend it on devastating finishing moves.',
    features: {
      1: ['Panache', "Swashbuckler's Style", 'Confident Finisher', 'Swashbuckler Feat'],
      3: ['Vivacious Speed (+10)', 'Stylish Tricks'],
      5: ['Weapon Expertise'],
      7: ['Evasion'],
      9: ['Continuous Flair', 'Weapon Specialization'],
      11: ['Vigilant Senses'],
      15: ['Improved Evasion'],
    },
    subclasses: [
      { name: 'Battledancer', desc: 'Gain Panache through Performance.' },
      { name: 'Braggart', desc: 'Gain Panache through Intimidation (Demoralize).' },
      { name: 'Fencer', desc: 'Gain Panache through Feint.' },
      { name: 'Gymnast', desc: 'Gain Panache through Athletics (Trip, Grapple).' },
      { name: 'Wit', desc: 'Gain Panache through Diplomacy (Bon Mot).' },
    ],
  },
  Investigator: {
    hp: 8, key_ability: ['Intelligence'],
    perception: 'Expert', fortitude: 'Trained', reflex: 'Expert', will: 'Expert',
    skills: 6,
    armor: ['Light'],
    weapons: ['Simple', 'Martial (light)'],
    description: 'Brilliant detectives who use keen minds and Pursue a Lead to solve mysteries and outfight enemies.',
    features: {
      1: ['On the Case', 'Devise a Stratagem', 'Methodology', 'Investigator Feat'],
      3: ['Keen Recollection', 'Skillful Lessons'],
      5: ['Weapon Expertise', 'Vigilant Senses'],
      7: ['Studious Expertise'],
      9: ['Great Fortitude', 'Resolve'],
    },
    subclasses: [
      { name: 'Alchemical Sciences', desc: 'Use alchemy to create investigative tools.' },
      { name: 'Empiricism', desc: 'Trust only your senses. Bonus to Recall Knowledge.' },
      { name: 'Forensic Medicine', desc: 'Focus on Medicine. Use Medicine for Pursue a Lead clues.' },
      { name: 'Interrogation', desc: 'Focus on social investigation. Bonus to Intimidation.' },
    ],
  },
  Magus: {
    hp: 8, key_ability: ['Strength', 'Dexterity'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 2,
    armor: ['Light', 'Medium'],
    weapons: ['Simple', 'Martial'],
    description: 'Hybrid casters who combine arcane spellcasting with martial prowess through Spellstrike.',
    features: {
      1: ['Arcane Spellcasting', 'Spellstrike', 'Hybrid Study', 'Magus Feat'],
      3: ['Arcane Cascade (stance)'],
      5: ['Striking Spell'],
      7: ['Expert Spellcaster', 'Studious Spells'],
      9: ['Alertness', 'Expert Strikes'],
      15: ['Master Spellcaster'],
    },
    subclasses: [
      { name: 'Inexorable Iron', desc: 'Two-handed weapon focus. Strength-based Spellstrike.' },
      { name: 'Laughing Shadow', desc: 'Mobile melee fighter. Extra movement on Spellstrike.' },
      { name: 'Sparkling Targe', desc: 'Shield and defense focus. Shielded Spellstrike.' },
      { name: 'Starlit Span', desc: 'Ranged Spellstrike with bows and crossbows.' },
      { name: 'Twisting Tree', desc: 'Staff-based combat. Versatile weapon enhancement.' },
    ],
  },
  Thaumaturge: {
    hp: 8, key_ability: ['Charisma'],
    perception: 'Expert', fortitude: 'Expert', reflex: 'Trained', will: 'Expert',
    skills: 3,
    armor: ['Light', 'Medium'],
    weapons: ['Simple', 'Martial'],
    description: 'Exploit supernatural weaknesses using esoteric implements and lore. Part scholar, part warrior.',
    features: {
      1: ['Exploit Vulnerability', 'First Implement and Esoterica', 'Thaumaturge Feat'],
      3: ['Lightning Reflexes'],
      5: ['Second Implement', 'Thaumaturgic Expertise'],
      9: ['Resolve', 'Vigilant Senses'],
      11: ['Medium Armor Expertise'],
      15: ['Third Implement', 'Greater Resolve'],
    },
    subclasses: [
      { name: 'Amulet', desc: 'Protective implement. Grant resistance to allies.' },
      { name: 'Bell', desc: 'Sonic implement. Stupefied enemies with ringing.' },
      { name: 'Chalice', desc: 'Healing implement. Drink to regain HP.' },
      { name: 'Lantern', desc: 'Light implement. Reveal hidden and invisible creatures.' },
      { name: 'Mirror', desc: 'Illusion implement. Create misleading reflections.' },
      { name: 'Regalia', desc: 'Command implement. Intimidate and command foes.' },
      { name: 'Tome', desc: 'Knowledge implement. Recall Knowledge as a free action.' },
      { name: 'Wand', desc: 'Blasting implement. Shoot force damage.' },
      { name: 'Weapon', desc: 'Martial implement. Enhanced weapon strikes.' },
    ],
  },
  Kineticist: {
    hp: 8, key_ability: ['Constitution'],
    perception: 'Trained', fortitude: 'Expert', reflex: 'Expert', will: 'Trained',
    skills: 3,
    armor: ['Light'],
    weapons: ['Simple'],
    description: 'Channel raw elemental power from the Elemental Planes. Gather elements to fuel devastating blasts.',
    features: {
      1: ['Kinetic Gate (choose element)', 'Kinetic Aura', 'Elemental Blast', 'Kineticist Feat'],
      3: ['Will Expertise'],
      5: ['Gate Junction', 'Weapon Expertise'],
      7: ['Kinetic Durability', 'Second Gate (second element)'],
      9: ['Perception Expertise'],
      11: ['Kinetic Expertise'],
      15: ['Gate Mastery', 'Third Gate'],
    },
    subclasses: [
      { name: 'Air', desc: 'Wind and lightning. Flight and ranged blasts.' },
      { name: 'Earth', desc: 'Stone and metal. Armor and crushing force.' },
      { name: 'Fire', desc: 'Flame and heat. Maximum damage output.' },
      { name: 'Metal', desc: 'Ore and alloy. Versatile physical blasts.' },
      { name: 'Water', desc: 'Waves and ice. Healing and cold damage.' },
      { name: 'Wood', desc: 'Plants and growth. Healing and terrain control.' },
    ],
  },
};

// ─── PF2E Skills ─────────────────────────────────────────────────────────────
export const PF2E_SKILLS = {
  Acrobatics: 'dexterity',
  Arcana: 'intelligence',
  Athletics: 'strength',
  Crafting: 'intelligence',
  Deception: 'charisma',
  Diplomacy: 'charisma',
  Intimidation: 'charisma',
  Medicine: 'wisdom',
  Nature: 'wisdom',
  Occultism: 'intelligence',
  Performance: 'charisma',
  Religion: 'wisdom',
  Society: 'intelligence',
  Stealth: 'dexterity',
  Survival: 'wisdom',
  Thievery: 'dexterity',
};

// Lore skills are custom — players add their own (e.g. "Warfare Lore", "Underworld Lore")
export const PF2E_LORE_SKILLS = [
  'Warfare Lore', 'Underworld Lore', 'Sailing Lore', 'Academia Lore',
  'Accounting Lore', 'Architecture Lore', 'Art Lore', 'Circus Lore',
  'Engineering Lore', 'Farming Lore', 'Fishing Lore', 'Fortune-Telling Lore',
  'Games Lore', 'Genealogy Lore', 'Gladiatorial Lore', 'Guild Lore',
  'Heraldry Lore', 'Herbalism Lore', 'Hunting Lore', 'Labor Lore',
  'Legal Lore', 'Library Lore', 'Mercantile Lore', 'Mining Lore',
  'Scouting Lore', 'Scribing Lore', 'Tanning Lore', 'Theater Lore',
];

// PF2E proficiency ranks and bonuses
export const PF2E_PROFICIENCY_RANKS = {
  untrained: 0,
  trained: 2,
  expert: 4,
  master: 6,
  legendary: 8,
};

// ─── PF2E Core Feats (sample of iconic feats per category) ──────────────────
export const PF2E_GENERAL_FEATS = [
  { name: 'Toughness', level: 1, description: 'Increase HP by your level. Reduce your dying value by 1 (you die at dying 5 instead of dying 4).' },
  { name: 'Fleet', level: 1, description: 'Increase your Speed by 5 feet.' },
  { name: 'Incredible Initiative', level: 1, description: '+2 circumstance bonus to initiative rolls.' },
  { name: 'Shield Block', level: 1, description: 'Reaction: Reduce damage by shield Hardness, shield takes remaining damage.' },
  { name: 'Armor Proficiency', level: 1, description: 'Gain trained proficiency in light armor (or medium, if already trained in light).' },
  { name: 'Canny Acumen', level: 1, description: 'Become expert in Perception, Fortitude, Reflex, or Will.' },
  { name: 'Diehard', level: 1, description: "You die at dying 5 instead of dying 4." },
  { name: 'Fast Recovery', level: 1, description: 'Regain double HP from rest, reduce drained/sickened faster.' },
  { name: 'Feather Step', level: 1, description: 'Step into difficult terrain.' },
  { name: 'Ancestral Paragon', level: 3, description: 'Gain a 1st-level ancestry feat.' },
  { name: 'Untrained Improvisation', level: 3, description: 'Add your level to untrained skill checks (half level below 7th).' },
  { name: 'Expeditious Search', level: 7, description: 'Search at full speed instead of half speed.' },
  { name: 'Incredible Investiture', level: 11, description: 'Invest up to 12 items instead of the standard 10.' },
];

export const PF2E_SKILL_FEATS = [
  { name: 'Assurance', level: 1, skill: 'Any', description: 'Forgo rolling: result is 10 + proficiency (no modifiers).' },
  { name: 'Dubious Knowledge', level: 1, skill: 'Recall Knowledge', description: 'On a failed Recall Knowledge, learn one true and one false info (you choose which).' },
  { name: 'Bargain Hunter', level: 1, skill: 'Diplomacy', description: 'Earn income using Diplomacy during downtime. Find better prices.' },
  { name: 'Battle Medicine', level: 1, skill: 'Medicine', description: 'Use Medicine to Treat Wounds as a single action in combat (once per person per day).' },
  { name: 'Cat Fall', level: 1, skill: 'Acrobatics', description: 'Treat falls as 10 feet shorter (or more at higher proficiency).' },
  { name: 'Charming Liar', level: 1, skill: 'Deception', description: 'When you Lie, the target is also fascinated with you on a success.' },
  { name: 'Intimidating Glare', level: 1, skill: 'Intimidation', description: 'Demoralize without speaking (visual only, no language barrier).' },
  { name: 'Pickpocket', level: 1, skill: 'Thievery', description: 'Steal items from creatures in combat or who are observing you (–5 penalty).' },
  { name: 'Quick Jump', level: 1, skill: 'Athletics', description: 'High Jump and Long Jump as one action instead of two.' },
  { name: 'Steady Balance', level: 1, skill: 'Acrobatics', description: 'Treat successes on Balance as critical successes. Not flat-footed while Balancing.' },
  { name: 'Titan Wrestler', level: 1, skill: 'Athletics', description: 'Grapple creatures up to two sizes larger than you.' },
  { name: 'Bon Mot', level: 1, skill: 'Diplomacy', description: 'Witty quip imposes –2 to Perception and Will saves on target.' },
  { name: 'Continual Recovery', level: 2, skill: 'Medicine', description: 'Treat Wounds cooldown is 10 minutes instead of 1 hour.' },
  { name: 'Quick Repair', level: 2, skill: 'Crafting', description: 'Repair an item in 1 minute instead of 10 minutes.' },
  { name: 'Kip Up', level: 7, skill: 'Acrobatics', description: 'Stand up from prone as a free action.' },
  { name: 'Ward Medic', level: 2, skill: 'Medicine', description: 'Treat Wounds on up to 2 targets at once (4 at master).' },
];

// ─── PF2E Spell Traditions ───────────────────────────────────────────────────
export const PF2E_SPELL_TRADITIONS = {
  Arcane: {
    description: 'Magic of logic and study. Excels at force damage, transformation, and elemental manipulation.',
    key_ability: 'Intelligence',
    classes: ['Wizard', 'Magus', 'Sorcerer (Draconic/Imperial)'],
  },
  Divine: {
    description: 'Power granted by deities. Strong in healing, holy damage, and protective wards.',
    key_ability: 'Wisdom or Charisma',
    classes: ['Cleric', 'Champion', 'Oracle', 'Sorcerer (Angelic/Demonic/Undead)'],
  },
  Occult: {
    description: 'Magic of the mind and hidden truths. Specializes in mental effects, illusions, and curses.',
    key_ability: 'Charisma or Intelligence',
    classes: ['Bard', 'Witch (Fate/Night)', 'Sorcerer (Aberrant)'],
  },
  Primal: {
    description: 'Raw power of nature and the elements. Strong in elemental blasts, healing, and animal forms.',
    key_ability: 'Wisdom',
    classes: ['Druid', 'Sorcerer (Fey)', 'Witch (Wild)'],
  },
};

// ─── PF2E Sample Spells (cantrips + rank 1-3 highlights) ────────────────────
export const PF2E_SAMPLE_SPELLS = [
  // Cantrips
  { name: 'Electric Arc', rank: 0, traditions: ['Arcane', 'Primal'], description: 'Lightning arcs between 2 targets. Each takes 1d4+mod electricity damage (basic Reflex save).', actions: 2 },
  { name: 'Produce Flame', rank: 0, traditions: ['Arcane', 'Primal'], description: 'Hurl a flame at a target. Ranged spell attack for 1d4+mod fire damage.', actions: 2 },
  { name: 'Shield', rank: 0, traditions: ['Arcane', 'Divine', 'Occult'], description: 'Raise a magical shield granting +1 AC. Can Shield Block for 5 hardness.', actions: 1 },
  { name: 'Heal', rank: 0, traditions: ['Divine', 'Primal'], description: '(Rank 1+) Heal 1d8 per rank. 1 action: touch. 2 actions: 30ft range. 3 actions: 30ft emanation.', actions: '1-3' },
  { name: 'Telekinetic Projectile', rank: 0, traditions: ['Arcane', 'Occult'], description: 'Hurl an object. Ranged spell attack for 1d6+mod bludgeoning damage.', actions: 2 },
  { name: 'Guidance', rank: 0, traditions: ['Divine', 'Occult', 'Primal'], description: 'Target gains +1 status bonus to one attack, Perception, save, or skill check.', actions: 1 },
  { name: 'Detect Magic', rank: 0, traditions: ['Arcane', 'Divine', 'Occult', 'Primal'], description: 'Detect magical auras in a 30-foot emanation.', actions: 2 },
  { name: 'Light', rank: 0, traditions: ['Arcane', 'Divine', 'Occult', 'Primal'], description: 'Object glows with bright light in a 20-foot radius.', actions: 2 },
  // Rank 1
  { name: 'Magic Missile', rank: 1, traditions: ['Arcane', 'Occult'], description: 'Fire 1 missile per action (1-3 actions). Each deals 1d4+1 force damage, no attack roll.', actions: '1-3' },
  { name: 'Burning Hands', rank: 1, traditions: ['Arcane', 'Primal'], description: '15-foot cone deals 2d6 fire damage (basic Reflex save).', actions: 2 },
  { name: 'Fear', rank: 1, traditions: ['Arcane', 'Divine', 'Occult', 'Primal'], description: 'Target becomes frightened 1 (frightened 2 on crit fail, flee on crit fail).', actions: 2 },
  { name: 'Bless', rank: 1, traditions: ['Divine', 'Occult'], description: '5ft emanation grants +1 status bonus to attack rolls for allies.', actions: 2 },
  { name: 'Command', rank: 1, traditions: ['Arcane', 'Divine', 'Occult'], description: 'Target must follow a one-word command on its next turn.', actions: 2 },
  { name: 'Grease', rank: 1, traditions: ['Arcane', 'Primal'], description: 'Coat a surface or object. Creatures must Balance or fall prone.', actions: 2 },
  { name: 'Sanctuary', rank: 1, traditions: ['Divine', 'Occult'], description: 'Creatures must succeed at a Will save to target the warded creature.', actions: 2 },
  // Rank 2
  { name: 'Fireball', rank: 3, traditions: ['Arcane', 'Primal'], description: '20-foot burst deals 6d6 fire damage (basic Reflex save). Iconic blaster spell.', actions: 2 },
  { name: 'Haste', rank: 3, traditions: ['Arcane', 'Occult', 'Primal'], description: 'Target gains quickened 1 (extra Strike or Stride each turn).', actions: 2 },
  { name: 'Heroism', rank: 3, traditions: ['Divine', 'Occult'], description: 'Target gains +1 status bonus to attack rolls, Perception, saves, and skill checks.', actions: 2 },
  { name: 'Lightning Bolt', rank: 3, traditions: ['Arcane', 'Primal'], description: '120-foot line deals 4d12 electricity damage (basic Reflex save).', actions: 2 },
  { name: 'Invisibility', rank: 2, traditions: ['Arcane', 'Occult'], description: 'Target becomes invisible until it attacks or casts a spell.', actions: 2 },
  { name: 'Restoration', rank: 2, traditions: ['Divine', 'Occult', 'Primal'], description: 'Remove a condition: drained, enfeebled, clumsy, or stupefied (reduce by 2).', actions: 2 },
  { name: 'Dispel Magic', rank: 2, traditions: ['Arcane', 'Divine', 'Occult', 'Primal'], description: 'Attempt to counteract a spell effect on a target.', actions: 2 },
  { name: 'Resist Energy', rank: 2, traditions: ['Arcane', 'Divine', 'Occult', 'Primal'], description: 'Grant resistance 5 to a chosen energy type for 10 minutes.', actions: 2 },
];

// ─── PF2E Backgrounds (sample) ──────────────────────────────────────────────
export const PF2E_BACKGROUNDS = [
  { name: 'Acolyte', skills: ['Religion', 'Scribing Lore'], feat: 'Student of the Canon', boosts: ['Intelligence', 'Wisdom', 'Free'] },
  { name: 'Artisan', skills: ['Crafting', 'Guild Lore'], feat: 'Specialty Crafting', boosts: ['Strength', 'Intelligence', 'Free'] },
  { name: 'Barkeep', skills: ['Diplomacy', 'Alcohol Lore'], feat: 'Hobnobber', boosts: ['Constitution', 'Charisma', 'Free'] },
  { name: 'Criminal', skills: ['Stealth', 'Underworld Lore'], feat: 'Experienced Smuggler', boosts: ['Dexterity', 'Intelligence', 'Free'] },
  { name: 'Detective', skills: ['Society', 'Underworld Lore'], feat: 'Streetwise', boosts: ['Intelligence', 'Wisdom', 'Free'] },
  { name: 'Emissary', skills: ['Society', 'City Lore'], feat: 'Multilingual', boosts: ['Intelligence', 'Charisma', 'Free'] },
  { name: 'Entertainer', skills: ['Performance', 'Theater Lore'], feat: 'Fascinating Performance', boosts: ['Dexterity', 'Charisma', 'Free'] },
  { name: 'Farmhand', skills: ['Athletics', 'Farming Lore'], feat: 'Assurance (Athletics)', boosts: ['Constitution', 'Wisdom', 'Free'] },
  { name: 'Field Medic', skills: ['Medicine', 'Warfare Lore'], feat: 'Battle Medicine', boosts: ['Constitution', 'Wisdom', 'Free'] },
  { name: 'Fortune Teller', skills: ['Occultism', 'Fortune-Telling Lore'], feat: 'Oddity Identification', boosts: ['Intelligence', 'Charisma', 'Free'] },
  { name: 'Gladiator', skills: ['Performance', 'Gladiatorial Lore'], feat: 'Impressive Performance', boosts: ['Strength', 'Charisma', 'Free'] },
  { name: 'Guard', skills: ['Intimidation', 'Legal Lore'], feat: 'Quick Coercion', boosts: ['Strength', 'Charisma', 'Free'] },
  { name: 'Herbalist', skills: ['Nature', 'Herbalism Lore'], feat: 'Natural Medicine', boosts: ['Constitution', 'Wisdom', 'Free'] },
  { name: 'Hermit', skills: ['Nature or Occultism', 'Cave Lore'], feat: 'Dubious Knowledge', boosts: ['Constitution', 'Intelligence', 'Free'] },
  { name: 'Hunter', skills: ['Survival', 'Tanning Lore'], feat: 'Survey Wildlife', boosts: ['Dexterity', 'Wisdom', 'Free'] },
  { name: 'Laborer', skills: ['Athletics', 'Labor Lore'], feat: 'Hefty Hauler', boosts: ['Strength', 'Constitution', 'Free'] },
  { name: 'Martial Disciple', skills: ['Athletics or Acrobatics', 'Warfare Lore'], feat: 'Cat Fall or Quick Jump', boosts: ['Strength', 'Dexterity', 'Free'] },
  { name: 'Merchant', skills: ['Diplomacy', 'Mercantile Lore'], feat: 'Bargain Hunter', boosts: ['Intelligence', 'Charisma', 'Free'] },
  { name: 'Noble', skills: ['Society', 'Genealogy Lore'], feat: 'Courtly Graces', boosts: ['Intelligence', 'Charisma', 'Free'] },
  { name: 'Nomad', skills: ['Survival', 'Desert Lore or Swamp Lore'], feat: 'Assurance (Survival)', boosts: ['Constitution', 'Wisdom', 'Free'] },
  { name: 'Prisoner', skills: ['Stealth', 'Underworld Lore'], feat: 'Experienced Smuggler', boosts: ['Strength', 'Constitution', 'Free'] },
  { name: 'Sailor', skills: ['Athletics', 'Sailing Lore'], feat: 'Underwater Marauder', boosts: ['Strength', 'Dexterity', 'Free'] },
  { name: 'Scholar', skills: ['Arcana, Nature, Occultism, or Religion', 'Academia Lore'], feat: 'Assurance (skill)', boosts: ['Intelligence', 'Wisdom', 'Free'] },
  { name: 'Scout', skills: ['Survival', 'Scouting Lore'], feat: 'Forager', boosts: ['Dexterity', 'Wisdom', 'Free'] },
  { name: 'Street Urchin', skills: ['Thievery', 'City Lore'], feat: 'Pickpocket', boosts: ['Dexterity', 'Constitution', 'Free'] },
  { name: 'Tinker', skills: ['Crafting', 'Engineering Lore'], feat: 'Specialty Crafting', boosts: ['Dexterity', 'Intelligence', 'Free'] },
  { name: 'Warrior', skills: ['Intimidation', 'Warfare Lore'], feat: 'Intimidating Glare', boosts: ['Strength', 'Constitution', 'Free'] },
];

// ─── PF2E Rest Rules ─────────────────────────────────────────────────────────
export const PF2E_REST_RULES = {
  refocus: {
    name: 'Refocus (10 min)',
    duration: '10 minutes',
    description: 'Spend 10 minutes to regain 1 Focus Point (if you have a focus pool). Requires an activity related to your source of focus.',
    effects: ['Regain 1 Focus Point (if below max)'],
  },
  short_rest: {
    name: 'Short Rest (10 min)',
    duration: '10 minutes',
    description: 'A brief rest to treat wounds and refocus. Allies can use Medicine (Treat Wounds) on each other.',
    effects: [
      'Treat Wounds (Medicine check): 2d8 HP (trained), 2d8+10 (expert), 2d8+30 (master), 2d8+50 (legendary)',
      'Refocus: Regain 1 Focus Point',
      'Exploration activities continue',
    ],
  },
  long_rest: {
    name: 'Long Rest (8 hours)',
    duration: '8 hours (at least 6 hours sleeping)',
    description: 'A full night of rest to recover all resources. Must be uninterrupted.',
    effects: [
      'Regain ALL Hit Points',
      'Regain ALL spell slots',
      'Regain ALL Focus Points',
      'Reduce Drained condition by 1',
      'Reduce Doomed condition by 1',
      'Reduce other conditions as specified',
      'Daily preparations: Prepare spells, select daily abilities',
    ],
  },
};