import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { resolveGeneratedRecoveryCandidate } from '../../shared/story/generatedRecoveryResolution.ts';
import { guardAndCommitNarratedRecovery } from '../../shared/story/storyRecoveryGuard.ts';
import { acceptSequencedStoryPayload, canonicalStoryResponsePayload, commitStoryTransition, hashStoryValue, hydrateLatestStoryEntry, storyPayloadFromCommit } from '../../shared/story/storyTransition.ts';
import { NARRATED_RECOVERY_PARSER_VERSION } from '../../shared/story/narratedStoryInventoryCommit.ts';
import { hashValue, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const choices = (label) => [1,2,3,4].map((n) => ({ text: `${label} option ${n}`, skill_check: n % 2 ? 'Stealth' : 'Perception', dc: 10 + n, risk_level: n > 2 ? 'medium' : 'low' }));

export default async function testProductionStoryRecoveryRegression(req) {
  const base44=createClientFromRequest(req); const user=await base44.auth.me();
  if(!user||user.role!=='admin') return Response.json({error:'Admin access required'},{status:403});
  const db=base44.asServiceRole,results=[],fixtures=[],cleanup=[]; const record=(name,pass,detail)=>results.push({name,pass:!!pass,...(detail?{detail}:{})});
  const protectedBefore=await hashValue(await readProtectedDndState(db));
  try {
    await req.json().catch(()=>({})); const tag=`ProdStoryRecovery_${Date.now()}`;
    const character=await db.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:8,dexterity:18,wisdom:16,proficiency_bonus:3,hp_current:52,hp_max:52,inventory:[{name:'Arrows',quantity:18,category:'Ammunition'}],active_modifiers:[],conditions:[],is_active:false}); fixtures.push(['Character',character.id]);
    const requestId='story-choice:fixture:c88f2a64-1360-4ce9-b990-2a79ccc70a97'; const receipt={id:requestId,request_id:requestId,unified_story_skill_resolution:true,skill:'Stealth',dc:11,raw_d20:16,modifier_total:7,final_total:23,success:true,modifier_breakdown:{base_skill:7,effect_bonus:0,pwt_active:false}};
    let session=await db.entities.GameSession.create({character_id:character.id,title:tag,current_location:'Deep within the pathless wetlands of the Whispering Fens',story_log:[{request_id:'source',text:'Mist lies across the wetlands.',choices:choices('source')}],world_state:{__skill_check_receipts:[receipt]},in_combat:false,is_active:false}); fixtures.push(['GameSession',session.id]);
    const exactCandidate={narrative:'You advance cautiously through the pathless wetlands, using ground, cover, terrain, and reeds to avoid notice.',choices:choices('exact'),current_recovery:null,combat_trigger:false,enemies:[]};
    const exact=await resolveGeneratedRecoveryCandidate({candidate:exactCandidate,regenerate:async()=>{throw new Error('ordinary movement must not regenerate')},action:'Advance cautiously through Deep within the pathless wetlands of the Whispering Fens. while avoiding notice.',location:session.current_location,check:receipt});
    const inventoryBefore=await hashValue(character.inventory); const guarded=await guardAndCommitNarratedRecovery({base44,sessionId:session.id,characterId:character.id,requestId,check:receipt,narrative:exact.result.narrative,recovery:exact.result.current_recovery});
    const entry={timestamp:'2026-09-01T20:51:21.111Z',request_id:requestId,action:'choice',player_choice:'Advance cautiously through Deep within the pathless wetlands of the Whispering Fens. while avoiding notice.',text:exact.result.narrative,choices:exact.result.choices,skill_check:receipt}; entry.choice_evidence={response_payload_hash:await hashStoryValue(canonicalStoryResponsePayload({requestId,text:entry.text,choices:entry.choices,skillCheck:receipt}))}; const commit=commitStoryTransition(session.story_log,entry,requestId); await db.entities.GameSession.update(session.id,{story_log:commit.story_log}); session=await db.entities.GameSession.get(session.id); const latest=hydrateLatestStoryEntry(session);
    record('exact c88 production payload commits one narration and four choices',exact.classification==='non_acquisition'&&guarded.body.writes===0&&latest.request_id===requestId&&latest.choices.length===4&&latest.entry.skill_check.raw_d20===16&&latest.entry.skill_check.final_total===23);
    record('wetlands path ground cover terrain language is non acquisition',exact.classification==='non_acquisition');
    record('production movement preserves inventory bytes',inventoryBefore===await hashValue((await db.entities.Character.get(character.id)).inventory));
    for(let n=1;n<=3;n++){const id=`${requestId}:next:${n}`;const candidate={narrative:`Cautious movement ${n} carries you farther across the wet terrain without exchanging or adding possessions.`,choices:choices(`next${n}`),current_recovery:null};const resolved=await resolveGeneratedRecoveryCandidate({candidate,regenerate:async()=>candidate,action:'continue cautiously',location:session.current_location,check:receipt});const fresh=await db.entities.GameSession.get(session.id);const next=commitStoryTransition(fresh.story_log,{request_id:id,text:resolved.result.narrative,choices:resolved.result.choices,skill_check:{...receipt,id,request_id:id}},id);await db.entities.GameSession.update(session.id,{story_log:next.story_log});}
    session=await db.entities.GameSession.get(session.id); record('three consecutive successful non acquisition pairs have no orphan',session.story_log.slice(-3).every((e)=>e.text&&e.choices?.length===4)&&session.story_log.filter((e)=>e.request_id===requestId).length===1);
    const unsupported={narrative:'You recover exactly 7 arrows from the mud.',choices:choices('bad'),current_recovery:null}; let repairs=0; const fallback=await resolveGeneratedRecoveryCandidate({candidate:unsupported,regenerate:async()=>{repairs++;return unsupported},action:'advance cautiously',location:session.current_location,check:receipt}); record('unstructured exact acquisition gets one repair then zero acquisition fallback',repairs===1&&fallback.fallback_used&&fallback.classification==='non_acquisition'&&fallback.result.choices.length===4&&fallback.result.current_recovery===null);
    const structured={...unsupported,current_recovery:{type:'arrows',quantity:7}}; const matched=await resolveGeneratedRecoveryCandidate({candidate:structured,regenerate:async()=>structured,action:'recover arrows',location:session.current_location,check:receipt}); record('exact structured acquisition matches without regeneration',matched.classification==='matched_structured_recovery'&&matched.attempts===0);
    const vague=await resolveGeneratedRecoveryCandidate({candidate:{narrative:'There may be something useful beyond the reeds.',choices:choices('vague'),current_recovery:null},regenerate:async()=>null,action:'look ahead',location:session.current_location,check:receipt}); record('vague reward remains zero write eligible',vague.classification==='vague_ambiguous'&&vague.attempts===0);
    const response={...storyPayloadFromCommit({...commit,persistence_confirmed:true}),persistence_confirmed:true}; record('replay and late response remain guarded',commitStoryTransition(session.story_log,entry,requestId).replayed&&!acceptSequencedStoryPayload(response,1,2).accepted);
    record('PWT inactive receipt remains plus zero',receipt.modifier_breakdown.pwt_active===false&&receipt.modifier_breakdown.effect_bonus===0&&receipt.final_total===23);
    let wrongStatus=0; try{await guardAndCommitNarratedRecovery({base44,sessionId:'missing',characterId:character.id,requestId:'wrong',check:receipt,narrative:structured.narrative,recovery:structured.current_recovery});}catch(error){wrongStatus=error?.status||error?.response?.status||404;} record('wrong linkage rejects without writes',wrongStatus===403||wrongStatus===404);
  } catch(error){record('test execution',false,error.message);} finally {for(const [entity,id] of fixtures.reverse()){let absent=false;try{await db.entities[entity].delete(id);}catch{}try{absent=!(await db.entities[entity].get(id));}catch{absent=true;}cleanup.push({entity,id,absent});}}
  record('cleanup fixtures absent',cleanup.every((x)=>x.absent)); record('protected live unchanged',protectedBefore===await hashValue(await readProtectedDndState(db))); const passed=results.filter((x)=>x.pass).length,allPass=passed===results.length;
  return Response.json({function_version:'test-production-story-recovery-v1.0.0',parser_version:NARRATED_RECOVERY_PARSER_VERSION,passed,failed:results.length-passed,total:results.length,all_pass:allPass,results,cleanup},{status:allPass?200:500});
}