export const UNIQUE_SCENE_PICKUP_VERSION='unique-scene-pickup-v1.0.0';
const POSSESSION=/\b(pick(?:ed)?\s+up|take|took|collect(?:ed)?|put\s+(?:it|the\s+\w+)\s+in\s+(?:my|the)\s+pack|secure(?:d)?|stow(?:ed)?)\b/i;
const NEGATED=/\b(?:do\s+not|don't|cannot|can't|failed?\s+to|try|attempt|consider|should|could|may|might)\b/i;
const OBJECTS=[{key:'staff',pattern:/\bstaff\b/i,display:'Unidentified Staff',category:'Staff',description:'A heavy, gnarled darkwood staff wrapped in defiled Seventh Patrol iconography.'},{key:'wand',pattern:/\bwand\b/i,display:'Unidentified Wand',category:'Wand',description:'An unidentified wand recovered from the scene.'},{key:'amulet',pattern:/\bamulet\b/i,display:'Unidentified Amulet',category:'Amulet',description:'An unidentified amulet recovered from the scene.'},{key:'ring',pattern:/\bring\b/i,display:'Unidentified Ring',category:'Ring',description:'An unidentified ring recovered from the scene.'}];
const stableId=(requestId,key)=>`scene_item_${String(requestId).replace(/[^a-zA-Z0-9]+/g,'_').slice(-80)}_${key}`;
export function inferUniqueScenePickup({actionText,storyLog,requestId,sessionId,characterId,check}){
  const text=String(actionText||'').trim();if(!text||!POSSESSION.test(text)||NEGATED.test(text)||check?.success===false)return null;
  const mentioned=OBJECTS.filter((item)=>item.pattern.test(text));if(mentioned.length!==1)return null;const object=mentioned[0];
  const provenance=(storyLog||[]).slice(-12).map((entry,index)=>({entry,index:(storyLog||[]).length-Math.min(12,(storyLog||[]).length)+index})).filter(({entry})=>object.pattern.test(`${entry?.text||''} ${entry?.player_choice||''}`));
  const exact=provenance.filter(({entry})=>/\b(?:drops?|dropped|clatter(?:ed|s)?|held|holding|clutch(?:ed|ing)?|grip|ground|corpse|defeated|dead|remains)\b/i.test(String(entry?.text||'')));
  if(exact.length===0)return null;
  const source=exact[exact.length-1],instanceId=stableId(requestId,object.key),appearance=object.key==='staff'&&/gnarled piece of darkwood wrapped in the defiled iconography of the Seventh Patrol/i.test(String(source.entry.text||''))?object.description:`An unidentified ${object.key} secured from ${String(source.entry.text||'the authoritative scene').slice(0,180)}.`;
  return {classification:'exact_scene_provenance_unresolved_identity',provenance:{session_id:sessionId,character_id:characterId,acquisition_request_id:requestId,source_story_request_id:source.entry.request_id||null,source_story_index:source.index,scene_object:object.key,foe:/necromancer|cultist leader/i.test(String(source.entry.text||''))?'necromancer cultist leader':null},recovery:{type:'item',item:{item_id:instanceId,instance_id:instanceId,name:object.display,display_name:object.display,category:object.category,type:'Magic Item',quantity:1,stackable:false,is_magic:true,is_identified:false,identity_status:'unresolved',identification_status:'unidentified',unidentified_description:appearance,description:appearance,icon:'❔',acquisition_request_id:requestId,acquisition_source:'authoritative_scene_pickup',scene_provenance:{source_story_request_id:source.entry.request_id||null,source_story_index:source.index,session_id:sessionId,foe:/necromancer|cultist leader/i.test(String(source.entry.text||''))?'necromancer cultist leader':null}}}};
}