import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { auditPwtFutureVolleySetup } from '../../shared/repairs/pwtFutureVolleySetup.ts';
import { classifyStealthSetupIntent } from '../../shared/story/stealthSetupHandoff.ts';
import { hashValue, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

export default async function testPwtFutureVolleySetupRegression(req){
  const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user||user.role!=='admin')return Response.json({error:'Admin required'},{status:403});await req.json().catch(()=>({}));
  const db=base44.asServiceRole,fixtures=[],cleanup=[],results=[],record=(name,pass)=>results.push({name,pass:!!pass}),before=await hashValue(await readProtectedDndState(db));
  try{
    const tag=`PwtVolley_${Date.now()}`,rid=`story-action:${tag}:fotzng`,at='2026-09-01T21:28:15.465Z';
    let c=await db.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:8,dexterity:18,proficiency_bonus:3,skills:{Stealth:'proficient'},hp_max:52,hp_current:52,xp:14450,inventory:[{name:'Arrows',quantity:18}],spell_slots:{level_2:2},conditions:[],active_modifiers:[],is_active:false});fixtures.push(['Character',c.id]);
    const pwtCondition={id:'cond_pass_without_trace_1788298092495_wgu705',name:'pass without trace',source:'Pass without Trace',target_id:c.id,caster_id:c.id,concentration:true,applied_at:'2026-09-01T21:28:12.495Z',expires_at:'2026-09-01T22:28:12.495Z'};const pwtModifier={id:'typed_spell_pass_without_trace_1788298092495',source:'Pass without Trace',effect:'skill_bonus',skill:'Stealth',bonus:10,target_id:c.id,character_id:c.id,caster_id:c.id,concentration:true};await db.entities.Character.update(c.id,{conditions:[pwtCondition],active_modifiers:[pwtModifier]});c=await db.entities.Character.get(c.id);
    const receipt={id:rid,request_id:rid,unified_story_skill_resolution:true,skill:'Stealth',raw_d20:17,all_rolls:[17],dc:18,modifier_total:17,final_total:34,success:true,at,modifier_breakdown:{base_skill:7,effect_bonus:10,pwt_active:true}};const action='cast pass without trace to gain the stealth bonus. once that is done, i will launch a surprise volley of arrows at the leader.';
    let s=await db.entities.GameSession.create({character_id:c.id,title:tag,current_location:'Whispering Fens',story_log:[{request_id:'source',text:'Source',choices:[1,2,3,4].map((n)=>({text:`old ${n}`}))},{request_id:rid,player_choice:action,text:'Pass without Trace is active. Your Hide check succeeds.',choices:[],skill_check:receipt}],world_state:{active_concentration:{spell_name:'Pass without Trace',request_id:`${rid}:intent:0`,target_id:c.id,character_id:c.id,caster_id:c.id,concentration:true},__skill_check_receipts:[receipt]},in_combat:false,is_active:false});fixtures.push(['GameSession',s.id]);
    const scope={characterId:c.id,sessionId:s.id,requestId:rid},dry=await auditPwtFutureVolleySetup({db,mode:'dry_run',scope});record('exact combined intent classification establishes concealment',classifyStealthSetupIntent(action,receipt).establishes_concealment);record('dry run proposes four choices and one Stealthed with zero writes',dry.body.safe_to_repair&&dry.body.proposed_choice_count===4&&dry.body.writes===0&&!!dry.body.apply_token);
    const tampered=`${dry.body.apply_token.slice(0,-1)}${dry.body.apply_token.endsWith('a')?'b':'a'}`,bad=await auditPwtFutureVolleySetup({db,mode:'apply',scope,applyToken:tampered});record('tampered token rejects without writes',bad.status===409&&bad.body.writes===0);
    const applied=await auditPwtFutureVolleySetup({db,mode:'apply',scope,applyToken:dry.body.apply_token}),afterC=await db.entities.Character.get(c.id),afterS=await db.entities.GameSession.get(s.id);record('apply repairs choices and one structured Stealthed only',applied.body.writes===2&&afterS.story_log[1].choices.length===4&&afterC.conditions.filter((x)=>x.name==='stealthed').length===1);record('narration receipt PWT slot HP XP arrows preserved',afterS.story_log[1].text===s.story_log[1].text&&JSON.stringify(afterS.story_log[1].skill_check)===JSON.stringify(receipt)&&afterC.conditions.some((x)=>x.id===pwtCondition.id)&&afterC.active_modifiers.some((x)=>x.id===pwtModifier.id)&&afterC.spell_slots.level_2===2&&afterC.hp_current===52&&afterC.xp===14450&&afterC.inventory[0].quantity===18);
    const replay=await auditPwtFutureVolleySetup({db,mode:'apply',scope,applyToken:dry.body.apply_token});record('replay writes zero',replay.body.replayed&&replay.body.writes===0);record('no attack damage or combat created',(await db.entities.CombatLog.filter({session_id:s.id})).length===0&&afterC.hp_current===52&&afterC.inventory[0].quantity===18);
    const traversal=classifyStealthSetupIntent('Advance cautiously through the wetlands while avoiding notice.',receipt);record('mere traversal does not establish hidden state',!traversal.establishes_concealment);
    const wrong=await auditPwtFutureVolleySetup({db,mode:'dry_run',scope:{...scope,sessionId:'missing'}});record('wrong linkage rejects',wrong.status===403);
  }catch(error){record(`test execution: ${error.message}`,false);}finally{for(const [entity,id] of fixtures.reverse()){let absent=false;try{await db.entities[entity].delete(id);}catch{}try{absent=!(await db.entities[entity].get(id));}catch{absent=true;}cleanup.push({entity,id,absent});}}
  record('cleanup absent',cleanup.every((x)=>x.absent));record('protected live unchanged',before===await hashValue(await readProtectedDndState(db)));const passed=results.filter((x)=>x.pass).length,allPass=passed===results.length;return Response.json({function_version:'test-pwt-future-volley-setup-v1.0.0',passed,failed:results.length-passed,total:results.length,all_pass:allPass,results,cleanup},{status:allPass?200:500});
}