import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { applyCraigThrownDaggerRepair } from '../../shared/repairs/craigThrownDaggerPlaytestRepair.ts';

const dbDagger = { name: 'Dagger', type: 'Weapon', category: 'Weapon', properties: ['finesse', 'light', 'thrown (range 20/60)'], source: 'Equipment Database', equipment_id: '6a689bdb3b23c961f0ebeaa9', quantity: 1 };
const legacy = { name: 'Dagger', category: 'Weapon', properties: ['Finesse', 'Light', 'Thrown'], quantity: 1 };
const failedChoice = 'retrieve my arrows and dagger from the corpses [Skill Check: Medicine DC12 — FAILURE (rolled 11)]';

export default async function testApplyCraigThrownDaggerPlaytestRepair(req) {
  const fixtures=[]; const cleanup=[]; const results=[];
  try {
    const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401}); if(user.role!=='admin')return Response.json({error:'Admin access required'},{status:403}); await req.json().catch(()=>({}));
    const make=async(label,mutate=()=>{})=>{ const character=await base44.entities.Character.create({name:`DaggerRepairQA_${label}_${Date.now()}`,race:'Human',class:'Ranger',level:5,hp_max:30,hp_current:30,inventory:[{name:'Rope',quantity:1},dbDagger,{name:'Arrows',quantity:0},legacy],long_rest_abilities:{},is_active:false}); const story_log=[{player_choice:'older',text:'older'},{player_choice:'The combat has ended in victory and the player has finished searching the defeated enemies. Narrate the immediate aftermath, preserve current HP and depleted resources, and provide the next meaningful choices. Do not award duplicate combat XP, do not generate additional automatic loot, and do not immediately start another combat.',text:'The necrotic wolves you have just put down lie defeated.'},{player_choice:failedChoice,text:'You reach for your gear embedded in the mangled carcasses, but withdraw hollow-handed; the Dagger is damaged beyond simple field repair.'},{player_choice:'cast longstrider on myself',text:'control'},{player_choice:'cast pass without a trace on myself',text:'control'}]; const session=await base44.asServiceRole.entities.GameSession.create({character_id:character.id,title:label,in_combat:false,story_log,is_active:false}); fixtures.push({character:character.id,session:session.id}); await mutate({base44,character,session}); return {character,session}; };
    const valid=await make('valid'); const scope={character:valid.character.id,session:valid.session.id}; const first=await applyCraigThrownDaggerRepair({db:base44.asServiceRole,scope}); const replay=await applyCraigThrownDaggerRepair({db:base44.asServiceRole,scope}); const after=await base44.asServiceRole.entities.Character.get(valid.character.id);
    results.push({name:'production-shaped exact fixture removes only Equipment DB Dagger appends receipt and replays writes0',pass:first.status===200&&first.body.writes===1&&replay.body.already_processed&&replay.body.writes===0&&after.inventory.some(i=>i.name==='Dagger'&&!i.equipment_id)&&!after.inventory.some(i=>i.equipment_id===dbDagger.equipment_id)&&after.inventory.find(i=>i.name==='Arrows')?.quantity===0&&first.body.postconditions?.session_unchanged});
    for(const [label,mutate] of [['wording',async({base44,session})=>base44.asServiceRole.entities.GameSession.update(session.id,{story_log:[]})],['quantity',async({base44,character})=>base44.asServiceRole.entities.Character.update(character.id,{inventory:[{...dbDagger,quantity:2},{name:'Arrows',quantity:0},legacy]})],['arrows',async({base44,character})=>base44.asServiceRole.entities.Character.update(character.id,{inventory:[dbDagger,{name:'Arrows',quantity:1},legacy]})],['structured',async({base44,character})=>base44.asServiceRole.entities.Character.update(character.id,{long_rest_abilities:{__thrown_weapon_actions:[{token:'prior'}]}})]] ){ const fixture=await make(label,mutate); const result=await applyCraigThrownDaggerRepair({db:base44.asServiceRole,scope:{character:fixture.character.id,session:fixture.session.id}}); results.push({name:`near-miss ${label} fails closed writes0`,pass:result.status===409&&result.body.writes===0}); }
  } catch(error){results.push({name:'test execution',pass:false,detail:error.message});}
  finally{const base44=createClientFromRequest(req);for(const fixture of fixtures.reverse())for(const[entity,id]of[['GameSession',fixture.session],['Character',fixture.character]]){let deleted=false,verified_absent=false;try{await base44.asServiceRole.entities[entity].delete(id);deleted=true;}catch{}try{verified_absent=!(await base44.asServiceRole.entities[entity].get(id));}catch{verified_absent=true;}cleanup.push({entity,id,deleted,verified_absent});}}
  const passed=results.filter(r=>r.pass).length;const clean=cleanup.every(e=>e.deleted&&e.verified_absent);return Response.json({deployment_id:'thrown-dagger-pwt-playtest-repair-v1',passed,failed:results.length-passed,total:results.length,all_pass:passed===results.length&&clean,results,cleanup,cleanup_passed:clean,live_state:{protected_ids_read_or_mutated:false}},{status:passed===results.length&&clean?200:500});
}