import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { executeCraftingTransaction,planCraftingTransaction,CRAFTING_TRANSACTION_VERSION } from '../../shared/craftingTransaction.ts';
import { hashValue,readProtectedDndState } from '../../shared/tests/liveProtection.ts';

export default async function(req){
 const base44=createClientFromRequest(req),user=await base44.auth.me();if(!user||user.role!=='admin')return Response.json({error:'Admin required'},{status:403});await req.json().catch(()=>({}));const db=base44.asServiceRole,fixtures=[],tests=[],record=(name,pass)=>tests.push({name,pass:!!pass}),protectedBefore=await hashValue(await readProtectedDndState(db));
 try{const tag=`CraftQA_${Date.now()}`;let c=await db.entities.Character.create({name:tag,race:'Human',class:'Ranger',level:3,inventory:[{name:'Wood Shafts',quantity:10},{name:'Flint',quantity:10},{name:'Arrows',quantity:4}],long_rest_abilities:{},is_active:false});fixtures.push(['Character',c.id]);const s=await db.entities.GameSession.create({character_id:c.id,title:tag,story_log:[],world_state:{},is_active:false});fixtures.push(['GameSession',s.id]);
 const recipe={recipe_id:'ordinary-arrows',completed:true,time_minutes:60,tool:{name:"Woodcarver's Tools",provenance:'fixture-npc-workshop'},mechanically_identical:true,yield_quantity:3,output:{name:'Arrows',unit:'arrow',compatible_ammo_type:'Arrows',compatible_weapon:'Bow',rarity:'common'},ingredients:[{name:'Wood Shafts',quantity:3,source:'inventory'},{name:'Flint',quantity:3,source:'inventory'}],provenance:{type:'recipe',source:'fixture'}};
 const one=await executeCraftingTransaction({base44,characterId:c.id,sessionId:s.id,requestId:`${tag}:one`,recipe,check:{success:true}});c=await db.entities.Character.get(c.id);record('exact recipe yield commits once',one.body.applied&&one.body.writes===1);record('ingredients decrement atomically',c.inventory.find(i=>i.name==='Wood Shafts').quantity===7&&c.inventory.find(i=>i.name==='Flint').quantity===7);record('ordinary identical ammo merges canonical stack',c.inventory.filter(i=>i.name==='Arrows').length===1&&c.inventory.find(i=>i.name==='Arrows').quantity===7);record('receipt records output ingredients provenance request and hashes',one.body.receipt.version===CRAFTING_TRANSACTION_VERSION&&one.body.receipt.yield_quantity===3&&one.body.receipt.ingredients.length===2&&one.body.receipt.inventory_before_hash&&one.body.receipt.inventory_after_hash&&one.body.receipt.request_id);record('category rarity icon present',one.body.receipt.output.icon==='🏹⚪');const replay=await executeCraftingTransaction({base44,characterId:c.id,sessionId:s.id,requestId:`${tag}:one`,recipe,check:{success:true}});record('replay duplicate causes zero second mutation',replay.body.already_processed&&replay.body.writes===0&&(await db.entities.Character.get(c.id)).inventory.find(i=>i.name==='Arrows').quantity===7);record('narration interruption resumes receipt',replay.body.receipt.request_id===`${tag}:one`);
 const before=await hashValue(await db.entities.Character.get(c.id));const absent=await executeCraftingTransaction({base44,characterId:c.id,sessionId:s.id,requestId:`${tag}:absent`,recipe:{...recipe,ingredients:[{name:'Moon Metal',quantity:1,source:'inventory'}]},check:{success:true}});record('absent ingredients zero writes',absent.body.writes===0&&before===await hashValue(await db.entities.Character.get(c.id)));const checkOnly=planCraftingTransaction({character:c,session:s,requestId:'check',recipe,check:{success:false}});record('passed check requirement prevents check-only award',!checkOnly.ok&&checkOnly.reason==='successful_check_required');
 const special={...recipe,recipe_id:'ironwood-flint',mechanically_identical:false,yield_quantity:2,output:{name:'Ironwood Flint Arrows',unit:'arrow',compatible_ammo_type:'Arrows',compatible_weapon:'Bow',rarity:'common',crafting_identity:'ironwood-flint-v1'},ingredients:[{name:'Wood Shafts',quantity:2,source:'inventory'},{name:'Flint',quantity:2,source:'inventory'}]};const specialResult=await executeCraftingTransaction({base44,characterId:c.id,sessionId:s.id,requestId:`${tag}:special`,recipe:special,check:{success:true}});c=await db.entities.Character.get(c.id);record('distinct special ammo does not merge ordinary arrows',specialResult.body.applied&&c.inventory.find(i=>i.name==='Arrows').quantity===7&&c.inventory.find(i=>i.name==='Ironwood Flint Arrows').quantity===2);
 const cantrip=planCraftingTransaction({character:c,session:s,requestId:'cantrip',recipe:{...recipe,invocation_type:'druidcraft_cantrip'},check:{success:true}});record('Druidcraft cantrip ammunition attempt fails rules validation',!cantrip.ok&&/druidcraft_cantrip/.test(cantrip.reason));const wrong=await executeCraftingTransaction({base44,characterId:c.id,sessionId:'ffffffffffffffffffffffff',requestId:'wrong',recipe,check:{success:true}}).catch(()=>({status:404,body:{writes:0}}));record('mismatched session character rejects',wrong.status>=400);
 }catch(error){record(`execution: ${error.message}`,false);}finally{for(const [entity,id] of fixtures.reverse())try{await db.entities[entity].delete(id);}catch{}}
 record('cleanup and protected IDs unchanged',protectedBefore===await hashValue(await readProtectedDndState(db)));const passed=tests.filter(t=>t.pass).length,all=passed===tests.length;return Response.json({function_version:'authoritative-crafting-regression-v1.0.0',transaction_version:CRAFTING_TRANSACTION_VERSION,passed,failed:tests.length-passed,total:tests.length,all_pass:all,tests},{status:all?200:500});
}