import { characterBelongsToUser } from '../combat/authGuard.ts';

export const MAGIC_ITEM_IDENTIFICATION_VERSION='inventory-instance-identification-v1.0.0';
const RARITY_DC={common:10,uncommon:12,rare:15,'very rare':18,very_rare:18,legendary:20,artifact:23};
const FEES={common:10,uncommon:25,rare:100,'very rare':500,very_rare:500,legendary:2500,artifact:5000};
const instanceKey=(item)=>String(item?.instance_id||item?.item_id||item?.id||'');
const prof=(character)=>[2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6][Math.max(1,Math.min(20,Number(character.level)||1))-1];
function visibleSnapshot(item,canonical){return {...item,name:canonical.identified_name||canonical.name,display_name:canonical.identified_name||canonical.name,category:canonical.category||item.category,rarity:canonical.rarity,description:canonical.description,requires_attunement:!!canonical.requires_attunement,charges:canonical.charges,magic_properties:canonical.magic_properties||canonical.modifiers?.magic_properties||[],is_magic:true,is_identified:true,identity_status:'resolved',identification_status:'identified',identified_at:new Date().toISOString()};}
async function load({db,user,characterId,instanceId}){const character=await db.entities.Character.get(characterId);if(!character||!characterBelongsToUser(character,user))return {error:'Character ownership mismatch.',status:403};const matches=(character.inventory||[]).map((item,index)=>({item,index})).filter(({item})=>instanceKey(item)===instanceId);if(matches.length!==1)return {error:'Exact inventory item instance was not found.',status:matches.length?409:404};const {item,index}=matches[0];if(!item.is_magic)return {error:'That inventory instance is not magical.',status:409};return {character,item,index};}
async function canonical(db,item){if(!item.magic_item_id)return null;return db.entities.MagicItem.get(item.magic_item_id).catch(()=>null);}
function priorReceipt(character,token){return (character.long_rest_abilities?.__magic_identification_receipts||[]).find((r)=>r.token===token);}
export async function identifyInventoryInstanceBySkill({db,user,characterId,instanceId,skillType,requestId,testRoll}){
  const loaded=await load({db,user,characterId,instanceId});if(loaded.error)return {status:loaded.status,body:{success:false,error:loaded.error,writes:0}};const {character,item,index}=loaded;
  if(item.is_identified)return {status:200,body:{success:true,already_processed:true,item,writes:0}};const known=await canonical(db,item);if(!known)return {status:409,body:{success:false,identity_unresolved:true,message:'This item has no established hidden identity yet. Its appearance remains safely recorded for later resolution.',writes:0}};
  const token=String(requestId||`identify:${characterId}:${instanceId}:${skillType}`).slice(0,160),prior=priorReceipt(character,token);if(prior)return {status:200,body:{...prior.response,already_processed:true,writes:0}};
  const stat=['Arcana','Investigation'].includes(skillType)?'intelligence':null;if(!stat)return {status:400,body:{success:false,error:'Use Arcana or Investigation.',writes:0}};const score=Number(character[stat])||10,base=Math.floor((score-10)/2),skill=character.skills?.[skillType],modifier=base+(skill==='expert'||character.skills?.[`${skillType}_expertise`]?prof(character)*2:skill?prof(character):0),roll=Number(testRoll)||Math.floor(Math.random()*20)+1,dc=RARITY_DC[String(known.rarity||'').toLowerCase()]||15,total=roll+modifier,success=roll===20||(roll!==1&&total>=dc);let nextItem=item,writes=0;
  if(success){nextItem=visibleSnapshot(item,known);const inventory=(character.inventory||[]).map((entry,i)=>i===index?nextItem:entry),abilities={...(character.long_rest_abilities||{})},response={success:true,diceRoll:roll,skillModifier:modifier,totalRoll:total,dc,skillType,item:nextItem,itemName:nextItem.name,identifiedName:nextItem.name,message:`You successfully identified the ${nextItem.name}!`};abilities.__magic_identification_receipts=[...(abilities.__magic_identification_receipts||[]).slice(-49),{token,instance_id:instanceId,method:'skill',response,at:new Date().toISOString()}];await db.entities.Character.update(characterId,{inventory,long_rest_abilities:abilities});writes=1;return {status:200,body:{...response,writes}};}
  return {status:200,body:{success:false,diceRoll:roll,skillModifier:modifier,totalRoll:total,dc,skillType,itemName:item.name,message:"You fail to discern the item's true nature.",writes}};
}
export async function identifyInventoryInstanceByVendor({db,user,characterId,instanceId,vendorId,requestId}){
  const loaded=await load({db,user,characterId,instanceId});if(loaded.error)return {status:loaded.status,body:{success:false,error:loaded.error,writes:0}};const {character,item,index}=loaded;if(item.is_identified)return {status:200,body:{success:true,already_processed:true,item,newGold:character.gold,writes:0}};const known=await canonical(db,item);if(!known)return {status:409,body:{success:false,identity_unresolved:true,message:'The vendor cannot identify this item until its hidden identity is authoritatively resolved.',writes:0}};const vendor=await db.entities.Vendor.get(vendorId).catch(()=>null);if(!vendor)return {status:404,body:{success:false,error:'Vendor not found.',writes:0}};const token=String(requestId||`vendor-identify:${characterId}:${instanceId}:${vendorId}`).slice(0,160),prior=priorReceipt(character,token);if(prior)return {status:200,body:{...prior.response,already_processed:true,writes:0}};const fee=FEES[String(known.rarity||'').toLowerCase()]||50;if(Number(character.gold||0)<fee)return {status:409,body:{success:false,requiredGold:fee,characterGold:character.gold||0,message:`You need ${fee}gp to identify this item.`,writes:0}};const nextItem=visibleSnapshot(item,known),newGold=Number(character.gold)-fee,inventory=(character.inventory||[]).map((entry,i)=>i===index?nextItem:entry),abilities={...(character.long_rest_abilities||{})},response={success:true,fee,newGold,item:nextItem,itemName:nextItem.name,identifiedName:nextItem.name,message:`The vendor identified your ${nextItem.name} for ${fee}gp.`};abilities.__magic_identification_receipts=[...(abilities.__magic_identification_receipts||[]).slice(-49),{token,instance_id:instanceId,method:'vendor',vendor_id:vendorId,response,at:new Date().toISOString()}];await db.entities.Character.update(characterId,{inventory,gold:newGold,long_rest_abilities:abilities});await db.entities.Vendor.update(vendorId,{gold_reserve:Number(vendor.gold_reserve||200)+fee});return {status:200,body:{...response,writes:2}};
}