import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { DOMAIN_NAMES } from '../../shared/contentAudit/config.ts';
import { auditRecords, buildDryRunProposals, hashAuditValue, paginateCatalog } from '../../shared/contentAudit/engine.ts';
import { protectedSnapshot, protectedUnchanged, resultSummary } from '../../shared/tests/deepCombatGate.ts';

export default async function testContentCompletenessFullGate(req) {
  const results = []; const cleanup = { records: [], created: 0, cleanup_absent: true };
  try {
    await req.json().catch(() => ({})); const base44 = createClientFromRequest(req); const db = base44.asServiceRole; const beforeProtected = await protectedSnapshot(db); const before = {}; const rows = {};
    for (const domain of DOMAIN_NAMES) { const page = await paginateCatalog(base44, domain, 173); rows[domain] = page.records; before[domain] = await hashAuditValue(page.records.map((r) => ({ id:r.id, updated_date:r.updated_date || null }))); const audit = auditRecords(domain, page.records); const dry = await buildDryRunProposals(domain, page.records); results.push({ name: `${domain}: exhaustive pagination has terminal empty page`, pass: page.pagination.completed && page.pagination.terminal_empty_page && page.pagination.rows_fetched === page.records.length }); results.push({ name: `${domain}: display fallback and mechanics gaps are separately classified`, pass: Number.isFinite(audit.display.fallback_count) && Number.isFinite(audit.structured_semantics.required_gap_count) && Number.isFinite(audit.structured_semantics.engine_structuring_backlog) }); results.push({ name: `${domain}: source/version variants and dry-run proposals remain non-mutating`, pass: Number.isFinite(audit.classification.reference_variant_count) && Number.isFinite(dry.total_proposals) && typeof dry.proposal_hash === 'string' }); results.push({ name: `${domain}: source and version distributions are preserved as separate audit evidence`, pass: audit.source_distribution && audit.document_version_distribution && typeof audit.source_distribution === 'object' && typeof audit.document_version_distribution === 'object' }); }
    for (const domain of ['Race','Subclass','DnDClass','Feat','Spell','Equipment','MagicItem','Monster','DnDCondition']) results.push({ name: `${domain}: renderer smoke resolves the domain display contract`, pass: auditRecords(domain, rows[domain]).display.usable_count >= 0 });
    for (const domain of DOMAIN_NAMES) { const after = await paginateCatalog(base44, domain, 173); const afterHash = await hashAuditValue(after.records.map((r) => ({ id:r.id, updated_date:r.updated_date || null }))); results.push({ name: `${domain}: count and catalog timestamps remain unchanged after dry run`, pass: after.records.length === rows[domain].length && afterHash === before[domain] }); }
    const protectedState = await protectedUnchanged(db, beforeProtected); results.push({ name: 'pure read-only catalog gate leaves no fixture records to clean', pass: cleanup.cleanup_absent && cleanup.created === 0 });
    const summary = resultSummary(results, cleanup, protectedState); return Response.json({ deployment_id: 'content-completeness-full-gate-v1', acceptance_surface: { domains: DOMAIN_NAMES, prior_evidence_floor: '59/59', renderer_smoke: '9/9', writes: 0 }, ...summary }, { status: summary.all_pass && results.length >= 42 ? 200 : 500 });
  } catch (error) { return Response.json({ error:error.message, ...resultSummary(results, cleanup, { unchanged:false }) }, { status:500 }); }
}