import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { normalizeChoiceCheckDisplay } from '../../shared/story/choiceCheckDisplay.js';
import { hashValue, PROTECTED_DND_IDS, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const marker = 'data-choice-dc-render-version';
const fetchText = async (url) => { const response = await fetch(url, { cache:'no-store', headers:{'cache-control':'no-cache, no-store',pragma:'no-cache'}, signal:AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`); return response.text(); };
const refs = (text) => [...text.matchAll(/["']([^"']+\.js(?:\?[^"']*)?)["']/gi)].map((m) => m[1]);
const duplicateAppend = (code) => /skill_check.{0,60}["'`]\s*DC\s*["'`].{0,60}(?:\.dc|\["dc"\])/i.test(code);

export default async function testChoiceDcDeployedBundleRegression(req) {
  const base44 = createClientFromRequest(req); const db = base44.asServiceRole; const payload = await req.json().catch(() => ({})); const before = await hashValue(await readProtectedDndState(db));
  try {
    const deployedUrl = String(payload.deployed_url || '').trim(); const expectedAppId = String(payload.expected_app_id || '').trim(); if (!/^https:\/\//i.test(deployedUrl) || !expectedAppId) throw new Error('deployed_url (https) and expected_app_id are required');
    const pageUrl = new URL(deployedUrl); pageUrl.searchParams.set('__choice_dc_gate',String(Date.now())); const html = await fetchText(pageUrl.href); const match = html.match(/<script[^>]+src=["']([^"']*\/index-[A-Za-z0-9_-]+\.js(?:\?[^"']*)?)["']/i); if (!match) throw new Error('index.html does not reference index-<hash>.js');
    const indexUrl = new URL(match[1],pageUrl); const indexCode = await fetchText(indexUrl.href); const bodies = new Map([[indexUrl.href,indexCode]]); const queue = refs(`${html}\n${indexCode}`).map((ref)=>new URL(ref,indexUrl).href);
    while(queue.length && bodies.size<50){const url=queue.shift();if(bodies.has(url)||new URL(url).origin!==pageUrl.origin)continue;const code=await fetchText(url);bodies.set(url,code);refs(code).forEach((ref)=>queue.push(new URL(ref,url).href));}
    const allCode=[...bodies.values()].join('\n'); const badgeTexts=[['Investigation DC16','DC16'],['Survival DC16','DC16'],['Arcana DC15','DC15'],['Athletics DC14','DC14']].map(([skill_check,dc])=>normalizeChoiceCheckDisplay({skill_check,dc}).badgeText); const oneDc=(text)=>(text.match(/\bDC\b/gi)||[]).length===1;
    const after=await hashValue(await readProtectedDndState(db)); const response={deployment_id:'choice-dc-deployed-bundle-v4',real_index_asset:match[1].split('?')[0].split('/').pop(),marker_found_in_exact_asset:indexCode.includes(marker),expected_app_id_verified:allCode.includes(expectedAppId),duplicate_pattern_absent:![...bodies.values()].some(duplicateAppend),production_render_site_count:indexCode.split(marker).length-1,canonical_formatter_found:indexCode.includes('choice_dc_conflict'),rendered_badge_texts:badgeTexts,rendered_badges_valid:badgeTexts.every(oneDc),protected_ids:PROTECTED_DND_IDS,protected_hash_evidence:{before,after,unchanged:before===after},writes:0,live_records_mutated:false}; response.all_pass=response.marker_found_in_exact_asset&&response.expected_app_id_verified&&response.duplicate_pattern_absent&&response.production_render_site_count===1&&response.canonical_formatter_found&&response.rendered_badges_valid&&response.protected_hash_evidence.unchanged; return Response.json(response,{status:response.all_pass?200:500});
  } catch(error) { const after=await hashValue(await readProtectedDndState(db)); return Response.json({error:error.message,real_index_asset:null,marker_found_in_exact_asset:false,duplicate_pattern_absent:false,production_render_site_count:0,rendered_badge_texts:[],protected_ids:PROTECTED_DND_IDS,protected_hash_evidence:{before,after,unchanged:before===after},writes:0,live_records_mutated:false,all_pass:false},{status:500}); }
}