import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { normalizeChoiceCheckDisplay } from '../../shared/story/choiceCheckDisplay.js';
import { hashValue, PROTECTED_DND_IDS, readProtectedDndState } from '../../shared/tests/liveProtection.ts';

const marker = 'data-choice-dc-render-version';
const fetchText = async (url) => { const response = await fetch(url, { cache:'no-store', headers:{'cache-control':'no-cache, no-store',pragma:'no-cache'}, signal:AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`); return response.text(); };
const extractProductionIndexCandidates = (html, pageUrl) => {
  const scriptSources = [...html.matchAll(/<script\b[^>]*\bsrc\s*=\s*(["'])([^"']+)\1[^>]*>/gi)].map((match) => match[2]);
  const candidates = scriptSources.map((source) => ({ source, url:new URL(source, pageUrl) })).filter(({ url }) => url.origin === pageUrl.origin && /^\/assets\/index-[A-Za-z0-9_-]+\.js$/.test(url.pathname));
  return { scriptSources, candidates };
};
const duplicateAppend = (code) => /skill_check.{0,60}["'`]\s*DC\s*["'`].{0,60}(?:\.dc|\["dc"\])/i.test(code);

export default async function testChoiceDcDeployedBundleRegression(req) {
  const base44 = createClientFromRequest(req); const db = base44.asServiceRole; const payload = await req.json().catch(() => ({})); const before = await hashValue(await readProtectedDndState(db)); let assetDiagnostics = { script_sources:[], index_candidates:[] };
  try {
    const deployedUrl = String(payload.deployed_url || '').trim(); const expectedAppId = String(payload.expected_app_id || '').trim(); if (!/^https:\/\//i.test(deployedUrl) || !expectedAppId) throw new Error('deployed_url (https) and expected_app_id are required');
    const pageUrl = new URL(deployedUrl); pageUrl.searchParams.set('__choice_dc_gate',String(Date.now())); const html = await fetchText(pageUrl.href); const parsed = extractProductionIndexCandidates(html, pageUrl); assetDiagnostics = { script_sources:parsed.scriptSources, index_candidates:parsed.candidates.map(({ source, url }) => ({ source, url:url.href })) }; if (parsed.candidates.length !== 1) throw new Error(`Expected exactly one production hashed index script src; found ${parsed.candidates.length}`);
    const { source:indexSource, url:indexUrl } = parsed.candidates[0]; const indexCode = await fetchText(indexUrl.href); const badgeTexts=[['Investigation DC16','DC16'],['Survival DC16','DC16'],['Arcana DC15','DC15'],['Athletics DC14','DC14']].map(([skill_check,dc])=>normalizeChoiceCheckDisplay({skill_check,dc}).badgeText); const oneDc=(text)=>(text.match(/\bDC\b/gi)||[]).length===1;
    const after=await hashValue(await readProtectedDndState(db)); const response={deployment_id:'choice-dc-deployed-bundle-v5',real_index_asset:new URL(indexSource,pageUrl).pathname.split('/').pop(),asset_diagnostics:assetDiagnostics,marker_found_in_exact_asset:indexCode.includes(marker),expected_app_id_verified:indexCode.includes(expectedAppId),duplicate_pattern_absent:!duplicateAppend(indexCode),production_render_site_count:indexCode.split(marker).length-1,canonical_formatter_found:indexCode.includes('choice_dc_conflict'),rendered_badge_texts:badgeTexts,rendered_badges_valid:badgeTexts.every(oneDc),protected_ids:PROTECTED_DND_IDS,protected_hash_evidence:{before,after,unchanged:before===after},writes:0,live_records_mutated:false}; response.all_pass=response.marker_found_in_exact_asset&&response.expected_app_id_verified&&response.duplicate_pattern_absent&&response.production_render_site_count===1&&response.canonical_formatter_found&&response.rendered_badges_valid&&response.protected_hash_evidence.unchanged; return Response.json(response,{status:response.all_pass?200:500});
  } catch(error) { const after=await hashValue(await readProtectedDndState(db)); return Response.json({error:error.message,real_index_asset:null,asset_diagnostics:assetDiagnostics,marker_found_in_exact_asset:false,duplicate_pattern_absent:false,production_render_site_count:0,rendered_badge_texts:[],protected_ids:PROTECTED_DND_IDS,protected_hash_evidence:{before,after,unchanged:before===after},writes:0,live_records_mutated:false,all_pass:false},{status:500}); }
}